CREATE TRIGGER PRT_GEN_KEY_DISPLAY_TRIG BEFORE INSERT ON PRT_GEN_KEY_DISPLAY
FOR EACH ROW 
BEGIN

if (:NEW.PRT_GEN_KEY_DISPLAY_PK IS NULL) then
SELECT PRT_GEN_KEY_DISPLAY_SEQ.NEXTVAL INTO :NEW.PRT_GEN_KEY_DISPLAY_PK FROM DUAL;
end if;
END;
/
