CREATE TABLE "WCPCUSTOM"."PRT_REPORT_INFORMATION"
  (
    "S_NO"        VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "REPORT_PAGE" VARCHAR2(30 BYTE),
    "COLUMN_NAME" VARCHAR2(200 BYTE),
    "EN"          VARCHAR2(4000 BYTE),
    "NO_NO"       VARCHAR2(4000 BYTE),
    "DK"          VARCHAR2(4000 BYTE),
    "SE"          VARCHAR2(4000 BYTE),
    "LV"          VARCHAR2(4000 BYTE),
    "LT"          VARCHAR2(4000 BYTE),
    "ET"          VARCHAR2(4000 BYTE),
    "PL"          VARCHAR2(4000 BYTE),
    "MODIFIED_BY" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "MODIFIED_DATE" TIMESTAMP (6) NOT NULL ENABLE,
    "EN_US" VARCHAR2(4000 BYTE),
    CONSTRAINT "PRT_REPORT_INFORMATION" PRIMARY KEY ("S_NO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "WCPCUSTOM" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "WCPCUSTOM" ;
CREATE OR REPLACE TRIGGER "WCPCUSTOM"."PRT_REPORT_INFORMATION_TRIG" BEFORE
  INSERT ON PRT_REPORT_INFORMATION FOR EACH ROW BEGIN IF
    (
      :NEW.S_NO IS NULL
    )
    THEN
  SELECT PRT_REPORT_INFORMATION_SEQ.NEXTVAL INTO :NEW.S_NO FROM DUAL;
END IF;
END;
/
ALTER TRIGGER "WCPCUSTOM"."PRT_REPORT_INFORMATION_TRIG" ENABLE;