CREATE TABLE PRT_CARD_USER_ROLE_MAPPING 
( 
  US_ROLE_ID NUMBER NOT NULL 
, COUNTRY_CODE VARCHAR2(2 BYTE) 
, USER_EMAIL VARCHAR2(100 BYTE) 
, USER_ROLE VARCHAR2(25 BYTE) NOT NULL 
, ASSOCIATION_TYPE VARCHAR2(20 BYTE) NOT NULL 
, USER_ASSOCIATION VARCHAR2(20 BYTE) NOT NULL 
, PARTNER_ID VARCHAR2(8 BYTE)
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_CARD_USER_ROLE_MAPPIN_PK PRIMARY KEY 
  (
    US_ROLE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE PRT_CARD_USER_ROLE_MAPPING
ADD CONSTRAINT PRT_CARD_USER_ROLE_MAPPIN_FK1 FOREIGN KEY
(
  USER_EMAIL 
, COUNTRY_CODE 
)
REFERENCES PRT_CARD_USER_INFORMATION
(
  USER_EMAIL 
, COUNTRY_CODE 
)
ENABLE;
