CREATE TRIGGER PRT_VIEW_CARDS_TRIG AFTER INSERT OR UPDATE 
   ON PRT_CARD_TRANSACTION_HEADER
   FOR EACH ROW 
BEGIN
UPDATE PRT_CARD SET 
PRT_CARD.LAST_UPDATED = :NEW.TRANSACTION_TIME
WHERE PRT_CARD.PRT_CARD_PK= :NEW.KSID  AND PRT_CARD.COUNTRY_CODE = :NEW.PALS_COUNTRY_CODE AND PRT_CARD.PARTNER_ID= :NEW.PARTNER_ID AND PRT_CARD.ACCOUNT_ID= :NEW.ACCOUNT_ID ;

END;
/
