CREATE OR REPLACE TRIGGER PRT_CARD_USER_ROLE_MAP_TRIG BEFORE INSERT ON  PRT_CARD_USER_ROLE_MAPPING
FOR EACH ROW 
BEGIN
if (:NEW.US_ROLE_ID  IS NULL) then
SELECT PRT_CARD_USER_ROLE_MAPPING_SEQ.NEXTVAL INTO :NEW.US_ROLE_ID FROM DUAL;
end if;
END;
/


