create or replace
TRIGGER PRT_PCM_FEEDS_TRIG BEFORE INSERT ON PRT_PCM_FEEDS
FOR EACH ROW 
BEGIN

if (:NEW.PRT_PCM_FEEDS_PK IS NULL) then
SELECT PRT_PCM_FEEDS_SEQ.NEXTVAL INTO :NEW.PRT_PCM_FEEDS_PK FROM DUAL;
end if;
END;