<?binding.jca DeleteTxnHeaderPortalDBAdapterV1_db.jca?>
<wsdl:definitions name="DeleteTxnHeaderPortalDBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E007PALSTransactionHeadertoPortalApp/E007PALSTransactionHeadertoPortal/DeleteTxnHeaderPortalDBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E007PALSTransactionHeadertoPortalApp/E007PALSTransactionHeadertoPortal/DeleteTxnHeaderPortalDBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DeleteTxnHeaderPortalDBAdapterV1">
    <plt:partnerLinkType name="DeleteTxnHeaderPortalDBAdapterV1_plt">
        <plt:role name="DeleteTxnHeaderPortalDBAdapterV1_role">
            <plt:portType name="tns:DeleteTxnHeaderPortalDBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DeleteTxnHeaderPortalDBAdapterV1" schemaLocation="xsd/DeleteTxnHeaderPortalDBAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PrtCardTransactionHeaderCollection_msg">
        <wsdl:part name="PrtCardTransactionHeaderCollection" element="top:PrtCardTransactionHeaderCollection"/>
    </wsdl:message>
    <wsdl:portType name="DeleteTxnHeaderPortalDBAdapterV1_ptt">
        <wsdl:operation name="delete">
            <wsdl:input message="tns:PrtCardTransactionHeaderCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
