<?binding.jca InsertTxnHeaderSOAErrorLogDBAdapterV1_db.jca?>
<wsdl:definitions name="InsertTxnHeaderSOAErrorLogDBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E007PALSTransactionHeadertoPortalApp/E007PALSTransactionHeadertoPortal/InsertTxnHeaderSOAErrorLogDBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E007PALSTransactionHeadertoPortalApp/E007PALSTransactionHeadertoPortal/InsertTxnHeaderSOAErrorLogDBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertTxnHeaderSOAErrorLogDBAdapterV1">
    <plt:partnerLinkType name="InsertTxnHeaderSOAErrorLogDBAdapterV1_plt">
        <plt:role name="InsertTxnHeaderSOAErrorLogDBAdapterV1_role">
            <plt:portType name="tns:InsertTxnHeaderSOAErrorLogDBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertTxnHeaderSOAErrorLogDBAdapterV1" schemaLocation="xsd/InsertTxnHeaderSOAErrorLogDBAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EngageSoaTxnheaderErrorlogCollection_msg">
        <wsdl:part name="EngageSoaTxnheaderErrorlogCollection" element="top:EngageSoaTxnheaderErrorlogCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertTxnHeaderSOAErrorLogDBAdapterV1_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:EngageSoaTxnheaderErrorlogCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
