<?binding.jca MergeTxnHeaderPortalDBAdapterV1_db.jca?>
<wsdl:definitions name="MergeTxnHeaderPortalDBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E007PALSTransactionHeadertoPortalApp/E007PALSTransactionHeadertoPortal/MergeTxnHeaderPortalDBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E007PALSTransactionHeadertoPortalApp/E007PALSTransactionHeadertoPortal/MergeTxnHeaderPortalDBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeTxnHeaderPortalDBAdapterV1">
    <plt:partnerLinkType name="MergeTxnHeaderPortalDBAdapterV1_plt">
        <plt:role name="MergeTxnHeaderPortalDBAdapterV1_role">
            <plt:portType name="tns:MergeTxnHeaderPortalDBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeTxnHeaderPortalDBAdapterV1" schemaLocation="xsd/MergeTxnHeaderPortalDBAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PrtCardTransactionHeaderCollection_msg">
        <wsdl:part name="PrtCardTransactionHeaderCollection" element="top:PrtCardTransactionHeaderCollection"/>
    </wsdl:message>
    <wsdl:portType name="MergeTxnHeaderPortalDBAdapterV1_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:PrtCardTransactionHeaderCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
