<?binding.jca SelectDeltaTSSOADBAdapterV1_db.jca?>
<wsdl:definitions name="SelectDeltaTSSOADBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E007PALSTransactionHeadertoPortalApp/E007PALSTransactionHeadertoPortal/SelectDeltaTSSOADBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E007PALSTransactionHeadertoPortalApp/E007PALSTransactionHeadertoPortal/SelectDeltaTSSOADBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectDeltaTSSOADBAdapterV1">
    <plt:partnerLinkType name="SelectDeltaTSSOADBAdapterV1_plt">
        <plt:role name="SelectDeltaTSSOADBAdapterV1_role">
            <plt:portType name="tns:SelectDeltaTSSOADBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectDeltaTSSOADBAdapterV1" schemaLocation="xsd/SelectDeltaTSSOADBAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SelectDeltaTSSOADBAdapterV1Select_inputParameters">
        <wsdl:part name="SelectDeltaTSSOADBAdapterV1Select_inputParameters" element="top:SelectDeltaTSSOADBAdapterV1Select_Interface_ID_Country_CodeInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EngageSoaDeltatableCollection_msg">
        <wsdl:part name="EngageSoaDeltatableCollection" element="top:EngageSoaDeltatableCollection"/>
    </wsdl:message>
    <wsdl:portType name="SelectDeltaTSSOADBAdapterV1_ptt">
        <wsdl:operation name="SelectDeltaTSSOADBAdapterV1Select">
            <wsdl:input message="tns:SelectDeltaTSSOADBAdapterV1Select_inputParameters"/>
            <wsdl:output message="tns:EngageSoaDeltatableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
