<?binding.jca UpdateTxnHeaderPortalDBAdapterV1_db.jca?>
<wsdl:definitions name="UpdateTxnHeaderPortalDBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E007PALSTransactionHeadertoPortalApp/E007PALSTransactionHeadertoPortal/UpdateTxnHeaderPortalDBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E007PALSTransactionHeadertoPortalApp/E007PALSTransactionHeadertoPortal/UpdateTxnHeaderPortalDBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateTxnHeaderPortalDBAdapterV1">
    <plt:partnerLinkType name="UpdateTxnHeaderPortalDBAdapterV1_plt">
        <plt:role name="UpdateTxnHeaderPortalDBAdapterV1_role">
            <plt:portType name="tns:UpdateTxnHeaderPortalDBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateTxnHeaderPortalDBAdapterV1" schemaLocation="xsd/UpdateTxnHeaderPortalDBAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PrtCardTransactionHeaderCollection_msg">
        <wsdl:part name="PrtCardTransactionHeaderCollection" element="top:PrtCardTransactionHeaderCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateTxnHeaderPortalDBAdapterV1_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:PrtCardTransactionHeaderCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
