<?binding.jca GetPALSDB2CountDBAdapter_db.jca?>
<wsdl:definitions name="GetPALSDB2CountDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E004AccountPALStoPortal/E004AccountPALStoPortal/GetPALSDB2CountDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetPALSDB2CountDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E004AccountPALStoPortal/E004AccountPALStoPortal/GetPALSDB2CountDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="GetPALSDB2CountDBAdapter_plt">
        <plt:role name="GetPALSDB2CountDBAdapter_role">
            <plt:portType name="tns:GetPALSDB2CountDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetPALSDB2CountDBAdapter" schemaLocation="xsd/GetPALSDB2CountDBAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GetPALSDB2CountDBAdapterInput_msg">
        <wsdl:part name="GetPALSDB2CountDBAdapterInput_msg" element="db:GetPALSDB2CountDBAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="GetPALSDB2CountDBAdapterOutputCollection_msg">
        <wsdl:part name="GetPALSDB2CountDBAdapterOutputCollection" element="db:GetPALSDB2CountDBAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetPALSDB2CountDBAdapter_ptt">
        <wsdl:operation name="GetPALSDB2CountDBAdapter">
            <wsdl:input message="tns:GetPALSDB2CountDBAdapterInput_msg"/>
            <wsdl:output message="tns:GetPALSDB2CountDBAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
