<?binding.jca InsertPALSDataToTempAccountPortalDBAdapter_db.jca?>
<wsdl:definitions name="InsertPALSDataToTempAccountPortalDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E004AccountPALStoPortal/E004AccountPALStoPortal/InsertPALSDataToTempAccountPortalDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E004AccountPALStoPortal/E004AccountPALStoPortal/InsertPALSDataToTempAccountPortalDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertPALSDataToTempAccountPortalDBAdapter">
    <plt:partnerLinkType name="InsertPALSDataToTempAccountPortalDBAdapter_plt">
        <plt:role name="InsertPALSDataToTempAccountPortalDBAdapter_role">
            <plt:portType name="tns:InsertPALSDataToTempAccountPortalDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertPALSDataToTempAccountPortalDBAdapter" schemaLocation="xsd/InsertPALSDataToTempAccountPortalDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SoaAccountTempCollection_msg">
        <wsdl:part name="SoaAccountTempCollection" element="top:SoaAccountTempCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertPALSDataToTempAccountPortalDBAdapter_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:SoaAccountTempCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
