<?binding.jca MergeAccountPortalDBAdapter_db.jca?>
<wsdl:definitions name="MergeAccountPortalDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E004AccountPALStoPortal/E004AccountPALStoPortal/MergeAccountPortalDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E004AccountPALStoPortal/E004AccountPALStoPortal/MergeAccountPortalDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeAccountPortalDBAdapter">
    <plt:partnerLinkType name="MergeAccountPortalDBAdapter_plt">
        <plt:role name="MergeAccountPortalDBAdapter_role">
            <plt:portType name="tns:MergeAccountPortalDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeAccountPortalDBAdapter" schemaLocation="xsd/MergeAccountPortalDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PrtAccountCollection_msg">
        <wsdl:part name="PrtAccountCollection" element="top:PrtAccountCollection"/>
    </wsdl:message>
    <wsdl:portType name="MergeAccountPortalDBAdapter_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:PrtAccountCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
