<?binding.jca SelectInValidDataTempAccountPortalDBAdapter_db.jca?>
<wsdl:definitions name="SelectInValidDataTempAccountPortalDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E004AccountPALStoPortal/E004AccountPALStoPortal/SelectInValidDataTempAccountPortalDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/SelectInValidDataTempAccountPortalDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E004AccountPALStoPortal/E004AccountPALStoPortal/SelectInValidDataTempAccountPortalDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="SelectInValidDataTempAccountPortalDBAdapter_plt">
        <plt:role name="SelectInValidDataTempAccountPortalDBAdapter_role">
            <plt:portType name="tns:SelectInValidDataTempAccountPortalDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SelectInValidDataTempAccountPortalDBAdapter" schemaLocation="xsd/SelectInValidDataTempAccountPortalDBAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SelectInValidDataTempAccountPortalDBAdapterInput_msg">
        <wsdl:part name="SelectInValidDataTempAccountPortalDBAdapterInput_msg" element="db:SelectInValidDataTempAccountPortalDBAdapterInput"/>
    </wsdl:message>
    <wsdl:message name="SelectInValidDataTempAccountPortalDBAdapterOutputCollection_msg">
        <wsdl:part name="SelectInValidDataTempAccountPortalDBAdapterOutputCollection" element="db:SelectInValidDataTempAccountPortalDBAdapterOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="SelectInValidDataTempAccountPortalDBAdapter_ptt">
        <wsdl:operation name="SelectInValidDataTempAccountPortalDBAdapter">
            <wsdl:input message="tns:SelectInValidDataTempAccountPortalDBAdapterInput_msg"/>
            <wsdl:output message="tns:SelectInValidDataTempAccountPortalDBAdapterOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
