<?binding.jca TruncateTempAccountPortalDBAdapter_db.jca?>
<wsdl:definitions name="TruncateTempAccountPortalDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E004AccountPALStoPortal/E004AccountPALStoPortal/TruncateTempAccountPortalDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/TruncateTempAccountPortalDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E004AccountPALStoPortal/E004AccountPALStoPortal/TruncateTempAccountPortalDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="TruncateTempAccountPortalDBAdapter_plt">
        <plt:role name="TruncateTempAccountPortalDBAdapter_role">
            <plt:portType name="tns:TruncateTempAccountPortalDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TruncateTempAccountPortalDBAdapter" schemaLocation="xsd/TruncateTempAccountPortalDBAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="TruncateTempAccountPortalDBAdapterInput_msg">
        <wsdl:part name="TruncateTempAccountPortalDBAdapterInput_msg" element="db:TruncateTempAccountPortalDBAdapterInput"/>
    </wsdl:message>
    <wsdl:portType name="TruncateTempAccountPortalDBAdapter_ptt">
        <wsdl:operation name="TruncateTempAccountPortalDBAdapter">
            <wsdl:input message="tns:TruncateTempAccountPortalDBAdapterInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
