package com.sfr.engage.services.client.alertsSubscription;

import javax.xml.ws.WebFault;

@WebFault(faultBean = "alertsTrialType.FaultType", targetNamespace = "http://www.lntinfotech.com/integration/SOARuleEngineSubscription", name = "Fault")
public class FaultResponseMessage extends Exception {
    private com.sfr.engage.services.client.alertsSubscription.type.FaultType faultInfo;

    public FaultResponseMessage(String message, com.sfr.engage.services.client.alertsSubscription.type.FaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    public FaultResponseMessage(String message, com.sfr.engage.services.client.alertsSubscription.type.FaultType faultInfo, Throwable t) {
        super(message, t);
        this.faultInfo = faultInfo;
    }

    public com.sfr.engage.services.client.alertsSubscription.type.FaultType getFaultInfo() {
        return faultInfo;
    }

    public void setFaultInfo(com.sfr.engage.services.client.alertsSubscription.type.FaultType faultInfo) {
        this.faultInfo = faultInfo;
    }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)
