CREATE TRIGGER PRT_TRUCK_INFORMATION_TRIG BEFORE INSERT ON PRT_TRUCK_INFORMATION
FOR EACH ROW 
BEGIN

if (:NEW.PRT_TRUCK_INFORMATION_PK IS NULL) then
SELECT PRT_TRUCK_INFORMATION_SEQ.NEXTVAL INTO :NEW.PRT_TRUCK_INFORMATION_PK FROM DUAL;
end if;
END;
/
