<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../selectTransactionDBAdapterV1.wsdl"/>
      <rootElement name="PrtCardTransactionHeaderCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/selectTransactionDBAdapterV1"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../insertCardNotificationsDBAdpterV1.wsdl"/>
      <rootElement name="PrtCardNotificationsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertCardNotificationDBAdpterV1"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [FRI SEP 12 21:19:42 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertCardNotificationDBAdpterV1"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/selectTransactionDBAdapterV1"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/E013BusinessHourRuleApp/E013BusinessHourRule/insertCardNotificationsDBAdpterV1"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E013BusinessHourRuleApp/E013BusinessHourRule/selectTransactionDBAdapterV1"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt wsdl top xsd tns ns1 ns0 aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns1:PrtCardNotificationsCollection>
      <ns1:PrtCardNotifications>
        <ns1:countryCode>
          <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:palsCountryCode"/>
        </ns1:countryCode>
        <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:partnerId">
          <ns1:partner>
            <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:partnerId/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:partnerId/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:partnerId"/>
          </ns1:partner>
        </xsl:if>
        <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:accountId">
          <ns1:accountId>
            <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:accountId/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:accountId/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:accountId"/>
          </ns1:accountId>
        </xsl:if>
        <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupMainType">
          <ns1:cardgroupMain>
            <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupMainType/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupMainType/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupMainType"/>
          </ns1:cardgroupMain>
        </xsl:if>
        <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupSubType">
          <ns1:cardgroupSub>
            <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupSubType/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupSubType/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupSubType"/>
          </ns1:cardgroupSub>
        </xsl:if>
        <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupSeq">
          <ns1:cardgroupSeq>
            <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupSeq/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupSeq/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:cardgroupSeq"/>
          </ns1:cardgroupSeq>
        </xsl:if>
        <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:ksid">
          <ns1:cardPk>
            <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:ksid/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:ksid/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:ksid"/>
          </ns1:cardPk>
        </xsl:if>
        <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:card1_Id">
          <ns1:embossCardNum>
            <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:card1_Id/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:card1_Id/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:card1_Id"/>
          </ns1:embossCardNum>
        </xsl:if>
        <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:transactionTime">
          <ns1:transactionTime>
            <xsl:if test="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:transactionTime/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:transactionTime/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:transactionTime"/>
          </ns1:transactionTime>
        </xsl:if>
        <ns1:modifiedBy>
          <xsl:value-of select="/top:PrtCardTransactionHeaderCollection/top:PrtCardTransactionHeader/top:modifiedBy"/>
        </ns1:modifiedBy>
      </ns1:PrtCardNotifications>
    </ns1:PrtCardNotificationsCollection>
  </xsl:template>
</xsl:stylesheet>
