ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  DROP COLUMN SUBSCR_STARTDATE;
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  DROP COLUMN SUBSCR_ENDDATE;
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  DROP COLUMN REPORT_CATEGORY;
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  DROP COLUMN REPORT_FORMAT;
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  DROP COLUMN REPORT_FREQUENCY;
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  DROP COLUMN RECEPIENT_EMAIL;
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  DROP COLUMN REPORT_DESCRIPTION;