package com.sfr.engage.services.client.alertsSubscription;


import com.sfr.engage.services.client.alertsSubscription.type.UnsubscribeCollectionType;
import com.sfr.engage.services.client.alertsSubscription.type.UnsubscribeRequestType;
import com.sfr.engage.services.client.alertsSubscription.type.UnsubscribeResponseCollectionType;
import com.sfr.engage.services.client.alertsSubscription.type.UnsubscribeResponseType;
import com.sfr.engage.services.core.dao.factory.DAOFactory;

import java.util.List;

import javax.xml.ws.WebServiceRef;


// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

public class Subscription_ptClient {
    @WebServiceRef
    private static Subscription_client_ep subscription_client_ep;
    // private Subscription subint;

    public static void main(String[] args) {


        /*
        SubscribeCollectionType request = new SubscribeCollectionType();
        CustomerType req2 = new CustomerType();
        req2.setCustomerID("1212");
        req2.setEmailID("hiten.karam@gmail.com");
        req2.setFirstName("first");
        req2.setLastName("last");
        BigInteger bigint2 = new BigInteger("98888888000");
        req2.setMobileNumber(bigint2);

        request.setCustomer(req2);


        request.setIdentifier("12");
        request.setNotificationChannel("DAILY");
        request.setNotificationFormat("EXCEL");
        BigInteger bigint = new BigInteger("1");
        request.setRuleID(bigint);


        SubscribeFrequencyType SubscribeFrequencyTypeobj = new SubscribeFrequencyType();
        SubscribeFrequencyTypeobj.setScheduleFrequency("DAILY");
        request.setSubscribeFrequency(SubscribeFrequencyTypeobj);

        SubscribeRequestType newReq = new SubscribeRequestType();

        newReq.getSubscribeCollection().add(request);

        Subscription subint = null;
        DAOFactory factory = new DAOFactory();
        subint = factory.getAlertSubscriptionService();
        SubscribeResponseType responseobj = new SubscribeResponseType();
        try {
            responseobj = subint.subscribe(newReq);
        } catch (FaultResponseMessage e) {
            System.out.println("Exception");
        }
        // SubscribeResponseType responseobj = new SubscribeResponseType();
        SubscribeResponseCollectionType responseCollObj = new SubscribeResponseCollectionType();
        List<SubscribeResponseCollectionType> responseLIst = responseobj.getSubscribeCollection();
        //responseCollObj = (SubscribeResponseCollectionType)responseobj.getSubscribeCollection();

        for (int i = 0; i < responseLIst.size(); i++)

        {
            System.out.println("subs id " + responseLIst.get(i).getSubscriptionID());
        }

*/

        UnsubscribeCollectionType UnsubscribeCollectionTypeObj = new UnsubscribeCollectionType();
        UnsubscribeCollectionTypeObj.setSubscriptionID("125");
        UnsubscribeCollectionTypeObj.setCustomerID("hiten.karam@gmail.com");

        UnsubscribeRequestType UnsubscribeRequestTypeObj = new UnsubscribeRequestType();
        UnsubscribeRequestTypeObj.getUnsubscribeCollection().add(UnsubscribeCollectionTypeObj);

        Subscription subint = null;
        DAOFactory factory = new DAOFactory();
        subint = factory.getAlertSubscriptionService();
        UnsubscribeResponseType UnsubscribeResponseTypeObj = new UnsubscribeResponseType();
        try {
            UnsubscribeResponseTypeObj = subint.unsubscribe(UnsubscribeRequestTypeObj);
        } catch (FaultResponseMessage e) {
            System.out.println("Exception");
        }


        List<UnsubscribeResponseCollectionType> responseUnsubscribe = UnsubscribeResponseTypeObj.getUnsubscribeCollection();

        for (int i = 0; i < responseUnsubscribe.size(); i++) {
            System.out.println("status " + responseUnsubscribe.get(i).getStatus());
        }


    }
}
