package com.sfr.services.client.proxy.user;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebServiceClient(wsdlLocation="http://elb1cn12.statoilfuelretail.com:10021/OIMWebServices_ENGAGE/OIMUserManagermentImplPort?WSDL",
  targetNamespace="http://ws.oim.sfr.com/", name="OIMUserManagermentImpl")
public class OIMUserManagermentImpl_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.sfr.services.client.proxy.user.OIMUserManagermentImpl_Service");
      URL baseUrl = OIMUserManagermentImpl_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            OIMUserManagermentImpl_Service.class.getResource("http://elb1cn12.statoilfuelretail.com:10021/OIMWebServices_ENGAGE/OIMUserManagermentImplPort?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://elb1cn12.statoilfuelretail.com:10021/OIMWebServices_ENGAGE/OIMUserManagermentImplPort?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://elb1cn12.statoilfuelretail.com:10021/OIMWebServices_ENGAGE/OIMUserManagermentImplPort?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://elb1cn12.statoilfuelretail.com:10021/OIMWebServices_ENGAGE/OIMUserManagermentImplPort?WSDL",
          e);
    }
  }

  public OIMUserManagermentImpl_Service()
  {
    super(wsdlLocationURL,
          new QName("http://ws.oim.sfr.com/", "OIMUserManagermentImpl"));
  }

  public OIMUserManagermentImpl_Service(URL wsdlLocation,
                                        QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="OIMUserManagermentImplPort")
  public com.sfr.services.client.proxy.user.OIMUserManagermentImpl getOIMUserManagermentImplPort()
  {
    return (com.sfr.services.client.proxy.user.OIMUserManagermentImpl) super.getPort(new QName("http://ws.oim.sfr.com/",
                                                                                               "OIMUserManagermentImplPort"),
                                                                                     com.sfr.services.client.proxy.user.OIMUserManagermentImpl.class);
  }

  @WebEndpoint(name="OIMUserManagermentImplPort")
  public com.sfr.services.client.proxy.user.OIMUserManagermentImpl getOIMUserManagermentImplPort(WebServiceFeature... features)
  {
    return (com.sfr.services.client.proxy.user.OIMUserManagermentImpl) super.getPort(new QName("http://ws.oim.sfr.com/",
                                                                                               "OIMUserManagermentImplPort"),
                                                                                     com.sfr.services.client.proxy.user.OIMUserManagermentImpl.class,
                                                                                     features);
  }
}
