ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  ADD SUBSCR_STARTDATE DATE;
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  ADD SUBSCR_ENDDATE DATE;
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  ADD REPORT_CATEGORY varchar2(20);
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  ADD REPORT_FORMAT char(3);
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  ADD REPORT_FREQUENCY varchar2(20);
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  ADD RECEPIENT_EMAIL varchar2(100);
  
ALTER TABLE PRT_CARD_RULE_SUBSCRIPTION
  ADD REPORT_DESCRIPTION varchar2(50);