CREATE TRIGGER PRT_USER_PREFERRED_LANG_TRIG BEFORE INSERT ON PRT_USER_PREFERRED_LANG
FOR EACH ROW 
BEGIN
if (:NEW.S_NO IS NULL) then
SELECT PRT_USER_PREFERRED_LANG_SEQ.NEXTVAL INTO :NEW.S_NO FROM DUAL;
end if;
END;
/
