<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../SOAErrorLogDBAdapter.wsdl"/>
      <rootElement name="EngagePalsCardDtaErrorlogCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SOAErrorLogDBAdapter"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../E006CardPALSToPortal.wsdl"/>
      <rootElement name="Card" namespace="http://www.statoilfuelretail.com/integration/engage"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [THU MAY 15 20:15:55 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SOAErrorLogDBAdapter"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://www.statoilfuelretail.com/integration/engage"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E006CardPALSToPortal/E006CardPALSToPortal/SOAErrorLogDBAdapter"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:client="http://www.statoilfuelretail.com/integration/engage/E006CardPALSToPortal/E006CardPALSToPortal/E006CardPALSToPortal"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl top plt wsdl tns xsd ns1 client aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns1:Card>
      <xsl:for-each select="/top:EngagePalsCardDtaErrorlogCollection/top:EngagePalsCardDtaErrorlog">
        <ns1:FieldsDetails>
          <ns1:Delta_TS>
            <xsl:value-of select='concat(concat("Delta_TS: ",top:deltaTs," Country Code: ",top:countryCode," PARTNER_ID: ",top:partnerId," CARDGROUP_MAIN_TYPE: ",top:cardgroupMainType," CARDGROUP_SUB_TYPE: ",top:cardgroupSubType," CARDGROUP_SEQ: ",top:cardgroupSeq," PRT_CARD_PK: ",top:prtCardPk," CARD_IDENTIFIER: ",top:cardIdentifier," CARD_TYPE: ",top:cardType," MAGNETIC_CODE: ",top:magneticCode),concat(" CARD_EMBOSS_NUM: ",top:cardEmbossNum,"INVOICE_INFORMATION: ",top:invoiceInformation," CARD_EXPIRY: ",top:cardExpiry," BLOCK_TYPE: ",top:blockType," BLOCK_CODE: ",top:blockCode," BLOCK_ACTION: ",top:blockAction," BLOCK_DATE: ",top:blockDate," BLOCK_TIME: ",top:blockTime," BLOCK_LEVEL: ",top:blockLevel," MANUFACTURED_DATE: ",top:manufacturedDate),concat(" ROUTEX_CUSTOMER_NUMBER: ",top:routexCustomerNumber," INVOICE_ADDR1: ",top:invoiceAddr1," INVOICE_ADDR2: ",top:invoiceAddr2," INVOICE_POSTAL_CODE: ",top:invoicePostalCode," INVOICE_CITY: ",top:invoiceCity," ADDR_SEQ: ",top:addrSeq," INVOICE_COUNTRY: ",top:invoiceCountry," INVOICE_ADDR_LEVEL: ",top:invoiceAddrLevel," INVOICE_ADDR_TYPE: ",top:invoiceAddrType,"&lt;br/>"))'/>
          </ns1:Delta_TS>
        </ns1:FieldsDetails>
      </xsl:for-each>
    </ns1:Card>
  </xsl:template>
</xsl:stylesheet>
