<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="E011InvoiceDetailsPALStoPortalBPEL"
     targetNamespace="http://www.statoilfuelretail.com/integration/engage/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortalBPEL"
     xmlns:ns2="http://www.statoilfuelretail.com/integration/engage/"
     xmlns:ns1="http://www.statoilfuelretail.com/integration/engage/E011/E011InvocationReqMsg"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://www.statoilfuelretail.com/integration/engage/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortalBPEL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="E011InvoiceDetailsPALStoPortalBPEL">
        <plnk:role name="E011InvoiceDetailsPALStoPortalBPELProvider">
            <plnk:portType name="client:E011InvoiceDetailsPALStoPortalBPEL"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://www.statoilfuelretail.com/integration/engage/"
             xmlns:ns1="http://www.statoilfuelretail.com/integration/engage/E011/E011InvocationReqMsg"
             xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://www.statoilfuelretail.com/integration/engage/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortalBPEL"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <import namespace="http://www.statoilfuelretail.com/integration/engage/E011/E011InvocationReqMsg"
                 schemaLocation="xsd/E011InvocationReqMsg.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://www.statoilfuelretail.com/integration/engage/"
             xmlns:ns1="http://www.statoilfuelretail.com/integration/engage/E011/E011InvocationReqMsg"
             xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://www.statoilfuelretail.com/integration/engage/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortalBPEL"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <xsd:import namespace="http://www.statoilfuelretail.com/integration/engage/" schemaLocation="xsd/InvoiceDetailsValidationPayload.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="E011InvoiceDetailsPALStoPortalBPELRequestMessage">
        <wsdl:part name="payload" element="ns1:invocationMsg"/>
    </wsdl:message>
    <wsdl:portType name="E011InvoiceDetailsPALStoPortalBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:E011InvoiceDetailsPALStoPortalBPELRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
