<?binding.jca MergeInvoiceDetailsPortalDBAdapter_db.jca?>
<wsdl:definitions name="MergeInvoiceDetailsPortalDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortal/MergeInvoiceDetailsPortalDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortal/MergeInvoiceDetailsPortalDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeInvoiceDetailsPortalDBAdapter">
    <plt:partnerLinkType name="MergeInvoiceDetailsPortalDBAdapter_plt">
        <plt:role name="MergeInvoiceDetailsPortalDBAdapter_role">
            <plt:portType name="tns:MergeInvoiceDetailsPortalDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeInvoiceDetailsPortalDBAdapter" schemaLocation="xsd/MergeInvoiceDetailsPortalDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PrtCardInvoiceDetailsCollection_msg">
        <wsdl:part name="PrtCardInvoiceDetailsCollection" element="top:PrtCardInvoiceDetailsCollection"/>
    </wsdl:message>
    <wsdl:portType name="MergeInvoiceDetailsPortalDBAdapter_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:PrtCardInvoiceDetailsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
