<?binding.jca SelectDeltaTSDBAdapter_db.jca?>
<wsdl:definitions name="SelectDeltaTSDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortal/SelectDeltaTSDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E011InvoiceDetailsPALStoPortal/E011InvoiceDetailsPALStoPortal/SelectDeltaTSDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectDeltaTSDBAdapter">
    <plt:partnerLinkType name="SelectDeltaTSDBAdapter_plt">
        <plt:role name="SelectDeltaTSDBAdapter_role">
            <plt:portType name="tns:SelectDeltaTSDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectDeltaTSDBAdapter" schemaLocation="xsd/SelectDeltaTSDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SelectDeltaTSDBAdapterSelect_inputParameters">
        <wsdl:part name="SelectDeltaTSDBAdapterSelect_inputParameters" element="top:SelectDeltaTSDBAdapterSelect_CountryCode_InterfaceIDInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EngageSoaDeltatableCollection_msg">
        <wsdl:part name="EngageSoaDeltatableCollection" element="top:EngageSoaDeltatableCollection"/>
    </wsdl:message>
    <wsdl:portType name="SelectDeltaTSDBAdapter_ptt">
        <wsdl:operation name="SelectDeltaTSDBAdapterSelect">
            <wsdl:input message="tns:SelectDeltaTSDBAdapterSelect_inputParameters"/>
            <wsdl:output message="tns:EngageSoaDeltatableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
