ALTER TABLE PRT_PARTNER
  ADD PARTNER_TELEPHONE float;
  
ALTER TABLE PRT_PARTNER
  ADD PARTNER_CREDIT_LIMIT varchar2(15);
  
ALTER TABLE PRT_PARTNER
  DROP COLUMN PARTNER_ADDR_SEQ;
  
ALTER TABLE PRT_PARTNER
  DROP COLUMN PARTNER_ADDR_LEVEL;