ALTER TABLE PRT_CARD
  ADD CARD_PURCHASE_PROFILE varchar2(3);
  
ALTER TABLE PRT_CARD
  ADD CARD_TEXTLINE_1 varchar2(45);
  
ALTER TABLE PRT_CARD
  ADD CARD_INVOICE_EMAIL varchar2(80);
  
  
ALTER TABLE PRT_CARD
  DROP COLUMN CARD_IDENTIFIER;
    
ALTER TABLE PRT_CARD
  DROP COLUMN MAGNETIC_CODE;
    
ALTER TABLE PRT_CARD
  DROP COLUMN ROUTEX_CUSTOMER_NUMBER;
    
ALTER TABLE PRT_CARD
  DROP COLUMN ADDR_SEQ;
  
ALTER TABLE PRT_CARD
modify 
(CARD_TEXTLINE_2  varchar2(45));