<?binding.jca MergeTransactionDetailErrorLogDatabaseAdapterV1_db.jca?>
<wsdl:definitions name="MergeTransactionDetailErrorLogDatabaseAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E008TransactionDetailPALStoPortalApp/E008TransactionDetailPALStoPortal/MergeTransactionDetailErrorLogDatabaseAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E008TransactionDetailPALStoPortalApp/E008TransactionDetailPALStoPortal/MergeTransactionDetailErrorLogDatabaseAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeTransactionDetailErrorLogDatabaseAdapterV1">
    <plt:partnerLinkType name="MergeTransactionDetailErrorLogDatabaseAdapterV1_plt">
        <plt:role name="MergeTransactionDetailErrorLogDatabaseAdapterV1_role">
            <plt:portType name="tns:MergeTransactionDetailErrorLogDatabaseAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeTransactionDetailErrorLogDatabaseAdapterV1" schemaLocation="xsd/MergeTransactionDetailErrorLogDatabaseAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EngageSoaTxndtlErrorlogCollection_msg">
        <wsdl:part name="EngageSoaTxndtlErrorlogCollection" element="top:EngageSoaTxndtlErrorlogCollection"/>
    </wsdl:message>
    <wsdl:portType name="MergeTransactionDetailErrorLogDatabaseAdapterV1_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:EngageSoaTxndtlErrorlogCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
