<?binding.jca SelectDeltaTSDatabaseAdapterV1_db.jca?>
<wsdl:definitions name="SelectDeltaTSDatabaseAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E008TransactionDetailPALStoPortalApp/E008TransactionDetailPALStoPortal/SelectDeltaTSDatabaseAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E008TransactionDetailPALStoPortalApp/E008TransactionDetailPALStoPortal/SelectDeltaTSDatabaseAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectDeltaTSDatabaseAdapterV1">
    <plt:partnerLinkType name="SelectDeltaTSDatabaseAdapterV1_plt">
        <plt:role name="SelectDeltaTSDatabaseAdapterV1_role">
            <plt:portType name="tns:SelectDeltaTSDatabaseAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectDeltaTSDatabaseAdapterV1" schemaLocation="xsd/SelectDeltaTSDatabaseAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SelectDeltaTSDatabaseAdapterV1Select_inputParameters">
        <wsdl:part name="SelectDeltaTSDatabaseAdapterV1Select_inputParameters" element="top:SelectDeltaTSDatabaseAdapterV1Select_interfaceID_countryCodeInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EngageSoaDeltatableCollection_msg">
        <wsdl:part name="EngageSoaDeltatableCollection" element="top:EngageSoaDeltatableCollection"/>
    </wsdl:message>
    <wsdl:portType name="SelectDeltaTSDatabaseAdapterV1_ptt">
        <wsdl:operation name="SelectDeltaTSDatabaseAdapterV1Select">
            <wsdl:input message="tns:SelectDeltaTSDatabaseAdapterV1Select_inputParameters"/>
            <wsdl:output message="tns:EngageSoaDeltatableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
