<?binding.jca SelectPALSDB2DatabaseAdapterV1_db.jca?>
<wsdl:definitions name="SelectPALSDB2DatabaseAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E008TransactionDetailPALStoPortalApp/E008TransactionDetailPALStoPortal/SelectPALSDB2DatabaseAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E008TransactionDetailPALStoPortalApp/E008TransactionDetailPALStoPortal/SelectPALSDB2DatabaseAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectPALSDB2DatabaseAdapterV1">
    <plt:partnerLinkType name="SelectPALSDB2DatabaseAdapterV1_plt">
        <plt:role name="SelectPALSDB2DatabaseAdapterV1_role">
            <plt:portType name="tns:SelectPALSDB2DatabaseAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectPALSDB2DatabaseAdapterV1" schemaLocation="xsd/SelectPALSDB2DatabaseAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SelectPALSDB2DatabaseAdapterV1Select_inputParameters">
        <wsdl:part name="SelectPALSDB2DatabaseAdapterV1Select_inputParameters" element="top:SelectPALSDB2DatabaseAdapterV1Select_DELTA_TS_BatchSizeInputParameters"/>
    </wsdl:message>
    <wsdl:message name="Cc078Vs1CssolnjDtaCollection_msg">
        <wsdl:part name="Cc078Vs1CssolnjDtaCollection" element="top:Cc078Vs1CssolnjDtaCollection"/>
    </wsdl:message>
    <wsdl:portType name="SelectPALSDB2DatabaseAdapterV1_ptt">
        <wsdl:operation name="SelectPALSDB2DatabaseAdapterV1Select">
            <wsdl:input message="tns:SelectPALSDB2DatabaseAdapterV1Select_inputParameters"/>
            <wsdl:output message="tns:Cc078Vs1CssolnjDtaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
