<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../Subscription.wsdl"/>
      <rootElement name="SubscribeRequest" namespace="http://www.lntinfotech.com/integration/SOARuleEngineSubscription"/>
    </source>
    <source type="WSDL">
      <schema location="../InsertRuleEngineSubscriptionsDBAdapterV1.wsdl"/>
      <rootElement name="RuleengineRulesubscribersCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertRuleEngineSubscriptionsDBAdapterV1"/>
      <param name="InsertRuleEngineSubscriptionsDBAdapterV1_OV.RuleengineRulesubscribersCollection" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../Subscription.wsdl"/>
      <rootElement name="SubscribeResponse" namespace="http://www.lntinfotech.com/integration/SOARuleEngineSubscription"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [TUE SEP 09 18:12:09 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns1="http://www.lntinfotech.com/integration/SOARuleEngineSubscription"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertRuleEngineSubscriptionsDBAdapterV1"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://www.lntinfotech.com/integration/SOARuleEngineSubscription/Subscription"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOARuleEngineSubscriptionApp/SOARuleEngineSubscription/InsertRuleEngineSubscriptionsDBAdapterV1"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 plt wsdl top plnk client xsd tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="InsertRuleEngineSubscriptionsDBAdapterV1_OV.RuleengineRulesubscribersCollection"/>
  <xsl:template match="/">
    <ns1:SubscribeResponse>
      <xsl:for-each select="$InsertRuleEngineSubscriptionsDBAdapterV1_OV.RuleengineRulesubscribersCollection/top:RuleengineRulesubscribersCollection/top:RuleengineRulesubscribers">
         <xsl:variable name="CountPosition">
            <xsl:value-of select="position()"/>
          </xsl:variable>
        <SubscriptionCollection>
          <Identifier>
            <xsl:value-of select="/ns1:SubscribeRequest/SubscriptionCollection[position()=$CountPosition]/Identifier"/>
          </Identifier>
          <RuleID>
            <xsl:value-of select="top:rrsRrmRuleid"/>
          </RuleID>
          <CustomerID>
            <xsl:value-of select="top:rrsRcmCustomerid"/>
          </CustomerID>
          <SubscriptionID>
            <xsl:value-of select="top:rrsId"/>
          </SubscriptionID>
        </SubscriptionCollection>
      </xsl:for-each>
    </ns1:SubscribeResponse>
  </xsl:template>
</xsl:stylesheet>
