<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../Subscription.wsdl"/>
      <rootElement name="SubscribeRequest" namespace="http://www.lntinfotech.com/integration/SOARuleEngineSubscription"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../InsertRuleEngineSubscriptionsDBAdapterV1.wsdl"/>
      <rootElement name="RuleengineRulesubscribersCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertRuleEngineSubscriptionsDBAdapterV1"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [TUE SEP 09 17:44:08 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns1="http://www.lntinfotech.com/integration/SOARuleEngineSubscription"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertRuleEngineSubscriptionsDBAdapterV1"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:client="http://www.lntinfotech.com/integration/SOARuleEngineSubscription/Subscription"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOARuleEngineSubscriptionApp/SOARuleEngineSubscription/InsertRuleEngineSubscriptionsDBAdapterV1"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 wsdl client plnk xsd plt top tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <top:RuleengineRulesubscribersCollection>
      <xsl:for-each select="/ns1:SubscribeRequest/SubscribeCollection">
        <top:RuleengineRulesubscribers>
          <top:rrsRrmRuleid>
            <xsl:value-of select="RuleID"/>
          </top:rrsRrmRuleid>
          <top:rrsRcmCustomerid>
            <xsl:value-of select="Customer/CustomerID"/>
          </top:rrsRcmCustomerid>
          <top:rrsFrequency>
            <xsl:value-of select="SubscribeFrequency/ScheduleFrequency"/>
          </top:rrsFrequency>
          <top:rrsScheduleday>
            <xsl:value-of select="SubscribeFrequency/ScheduleDay"/>
          </top:rrsScheduleday>
          <top:rrsScheduledate>
            <xsl:value-of select="SubscribeFrequency/ScheduleDate"/>
          </top:rrsScheduledate>
          <top:rrsSchedulemonth>
            <xsl:value-of select="SubscribeFrequency/ScheduleMonth"/>
          </top:rrsSchedulemonth>
          <top:rrsChannelprotocol>
            <xsl:value-of select="NotificationChannel"/>
          </top:rrsChannelprotocol>
          <top:rrsFileformat>
            <xsl:value-of select="NotificationFormat"/>
          </top:rrsFileformat>
          <top:rrsStatus>
            <xsl:text disable-output-escaping="no">N</xsl:text>
          </top:rrsStatus>
          <top:rrsLastmailsent>
            <xsl:text disable-output-escaping="no">2000-01-01T12:00:00.0+05:30</xsl:text>
          </top:rrsLastmailsent>
          <top:rrsParameters>
            <xsl:value-of select="oraext:get-content-as-string(Parameters)"/>
          </top:rrsParameters>
          <top:rrsCustom1>
            <xsl:value-of select="Custom1"/>
          </top:rrsCustom1>
          <top:rrsCustom2>
            <xsl:value-of select="Custom2"/>
          </top:rrsCustom2>
          <top:rrsCustom3>
            <xsl:value-of select="Custom3"/>
          </top:rrsCustom3>
          <top:rrsCustom4>
            <xsl:value-of select="Custom4"/>
          </top:rrsCustom4>
          <top:rrsCustom5>
            <xsl:value-of select="Custom5"/>
          </top:rrsCustom5>
          <!--top:rrsRcmCustomerid>
            <top:rcmCustomerid>
              <xsl:value-of select="Customer/CustomerID"/>
            </top:rcmCustomerid>
            <top:rcmFirstname>
              <xsl:value-of select="Customer/FirstName"/>
            </top:rcmFirstname>
            <top:rcmLastname>
              <xsl:value-of select="Customer/LastName"/>
            </top:rcmLastname>
            <top:rcmEmailid>
              <xsl:value-of select="Customer/EmailID"/>
            </top:rcmEmailid>
            <top:rcmMobilenumber>
              <xsl:value-of select="Customer/MobileNumber"/>
            </top:rcmMobilenumber>
            <top:rcmCustom1>
              <xsl:value-of select="Customer/Custom1"/>
            </top:rcmCustom1>
            <top:rcmCustom2>
              <xsl:value-of select="Customer/Custom2"/>
            </top:rcmCustom2>
            <top:rcmCustom3>
              <xsl:value-of select="Customer/Custom3"/>
            </top:rcmCustom3>
            <top:rcmCustom4>
              <xsl:value-of select="Customer/Custom4"/>
            </top:rcmCustom4>
            <top:rcmCustom5>
              <xsl:value-of select="Customer/Custom5"/>
            </top:rcmCustom5>
          </top:rrsRcmCustomerid-->
        </top:RuleengineRulesubscribers>
      </xsl:for-each>
    </top:RuleengineRulesubscribersCollection>
  </xsl:template>
</xsl:stylesheet>
