<?binding.jca DeleteTransactionDetailsTemp_db.jca?>
<wsdl:definitions name="DeleteTransactionDetailsTemp" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E008TransactionDetailPALStoPortalApp/E008TransactionDetailPALStoPortal/DeleteTransactionDetailsTemp" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteTransactionDetailsTemp" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E008TransactionDetailPALStoPortalApp/E008TransactionDetailPALStoPortal/DeleteTransactionDetailsTemp" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="DeleteTransactionDetailsTemp_plt">
        <plt:role name="DeleteTransactionDetailsTemp_role">
            <plt:portType name="tns:DeleteTransactionDetailsTemp_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteTransactionDetailsTemp" schemaLocation="xsd/DeleteTransactionDetailsTemp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="DeleteTransactionDetailsTempInput_msg">
        <wsdl:part name="DeleteTransactionDetailsTempInput_msg" element="db:DeleteTransactionDetailsTempInput"/>
    </wsdl:message>
    <wsdl:portType name="DeleteTransactionDetailsTemp_ptt">
        <wsdl:operation name="DeleteTransactionDetailsTemp">
            <wsdl:input message="tns:DeleteTransactionDetailsTempInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
