CREATE TRIGGER PRT_LIST_PRICES_TRIG BEFORE INSERT ON  PRT_LIST_PRICES
FOR EACH ROW 
BEGIN

if (:NEW.PRT_LIST_PRICE_PK  IS NULL) then
SELECT PRT_LIST_PRICES_SEQ.NEXTVAL INTO :NEW.PRT_LIST_PRICE_PK FROM DUAL;
end if;
END;
/
