<?binding.jca InsertPALSDataToTempCardPortalDBAdapter_db.jca?>
<wsdl:definitions name="InsertPALSDataToTempCardPortalDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E006CardPALSToPortal/E006CardPALSToPortal/InsertPALSDataToTempCardPortalDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E006CardPALSToPortal/E006CardPALSToPortal/InsertPALSDataToTempCardPortalDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertPALSDataToTempCardPortalDBAdapter">
    <plt:partnerLinkType name="InsertPALSDataToTempCardPortalDBAdapter_plt">
        <plt:role name="InsertPALSDataToTempCardPortalDBAdapter_role">
            <plt:portType name="tns:InsertPALSDataToTempCardPortalDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertPALSDataToTempCardPortalDBAdapter" schemaLocation="xsd/InsertPALSDataToTempCardPortalDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SoaPrtCardTempCollection_msg">
        <wsdl:part name="SoaPrtCardTempCollection" element="top:SoaPrtCardTempCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertPALSDataToTempCardPortalDBAdapter_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:SoaPrtCardTempCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
