<?binding.jca SOAErrorDBAdapter_db.jca?>
<wsdl:definitions name="SOAErrorDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E006CardPALSToPortal/E006CardPALSToPortal/SOAErrorDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E006CardPALSToPortal/E006CardPALSToPortal/SOAErrorDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SOAErrorDBAdapter">
    <plt:partnerLinkType name="SOAErrorDBAdapter_plt">
        <plt:role name="SOAErrorDBAdapter_role">
            <plt:portType name="tns:SOAErrorDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SOAErrorDBAdapter" schemaLocation="xsd/SOAErrorDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EngagePalsCardDtaErrorlogCollection_msg">
        <wsdl:part name="EngagePalsCardDtaErrorlogCollection" element="top:EngagePalsCardDtaErrorlogCollection"/>
    </wsdl:message>
    <wsdl:portType name="SOAErrorDBAdapter_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:EngagePalsCardDtaErrorlogCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
