<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../SelectPALSDB2DatabaseAdapterV1.wsdl"/>
      <rootElement name="Cc074Vs1CssfakDtaCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectPALSDB2DatabaseAdapterV1"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../SelectDeltaTSDatabaseAdapterV1.wsdl"/>
      <rootElement name="ValidationPayload" namespace="http://www.statoilfuelretail.com/integration/E009/ValidateDB2Data"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [THU MAY 22 12:26:14 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/E009PALSInvoicetoPortalApp/E009PALSInvoicetoPortal/SelectDeltaTSDatabaseAdapterV1"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E009PALSInvoicetoPortalApp/E009PALSInvoicetoPortal/SelectPALSDB2DatabaseAdapterV1"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectPALSDB2DatabaseAdapterV1"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="http://www.statoilfuelretail.com/integration/E009/ValidateDB2Data"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectDeltaTSDatabaseAdapterV1"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns plt wsdl top xsd ns0 ns1 ns2 aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns1:ValidationPayload>
      <xsl:for-each select="/top:Cc074Vs1CssfakDtaCollection/top:Cc074Vs1CssfakDta">
        <ns1:ValidationData>
          <ns1:INVOICE_NUMBER>
            <xsl:value-of select="top:fakturaNr"/>
          </ns1:INVOICE_NUMBER>
          <ns1:COLLECTIVE_INVOICE_NUMBER>
            <xsl:value-of select="top:faksmndNr"/>
          </ns1:COLLECTIVE_INVOICE_NUMBER>
          <ns1:INVOICE_DATE>
            <xsl:value-of select="top:fakturaDt"/>
          </ns1:INVOICE_DATE>
          <ns1:INVOICED_CARD>
            <xsl:value-of select="top:kjopsalgId"/>
          </ns1:INVOICED_CARD>
          <ns1:CARD_TYPE>
            <xsl:value-of select="top:bevisTp"/>
          </ns1:CARD_TYPE>
          <ns1:MAGNETIC_CODE>
            <xsl:value-of select="top:eksternId"/>
          </ns1:MAGNETIC_CODE>
          <ns1:ROUTEX_VAT_INVOICE_NUMBER>
            <xsl:value-of select="top:rtxmvafakNr"/>
          </ns1:ROUTEX_VAT_INVOICE_NUMBER>
          <ns1:INVOICE_INFORMATION>
            <xsl:value-of select="top:fakturaTx"/>
          </ns1:INVOICE_INFORMATION>
          <ns1:INVOICE_DELIVERY_ADDRESS>
            <xsl:value-of select="top:faklevstedadr"/>
          </ns1:INVOICE_DELIVERY_ADDRESS>
          <ns1:NET_INVOICE_CODE>
            <xsl:value-of select="top:netfakKd"/>
          </ns1:NET_INVOICE_CODE>
          <ns1:ORIGINAL_INVOICE_NUMBER>
            <xsl:value-of select="top:opprfakturaNr"/>
          </ns1:ORIGINAL_INVOICE_NUMBER>
          <ns1:CORRECTION_PRESENTATION>
            <xsl:value-of select="top:fakkorprsTp"/>
          </ns1:CORRECTION_PRESENTATION>
          <ns1:INV_TOTAL_GROSS_AMT_FOREIGN>
            <xsl:value-of select="top:faktotutlBel"/>
          </ns1:INV_TOTAL_GROSS_AMT_FOREIGN>
          <ns1:INV_TOTAL_NET_VAT_MANDATORY>
            <xsl:value-of select="top:fakmvapBel"/>
          </ns1:INV_TOTAL_NET_VAT_MANDATORY>
          <ns1:INV_TOTAL_NET_VAT_FREE>
            <xsl:value-of select="top:fakmvaiBel"/>
          </ns1:INV_TOTAL_NET_VAT_FREE>
          <ns1:INV_TOTAL_VAT_AMT>
            <xsl:value-of select="top:fakmvaBel"/>
          </ns1:INV_TOTAL_VAT_AMT>
          <ns1:INV_TOTAL_GROSS_AMT>
            <xsl:value-of select="top:faktotbrtBel"/>
          </ns1:INV_TOTAL_GROSS_AMT>
          <ns1:CURR_TOTAL_NET_VAT_MANDATORY>
            <xsl:value-of select="top:intmvapBel"/>
          </ns1:CURR_TOTAL_NET_VAT_MANDATORY>
          <ns1:CURR_TOTAL_NET_VAT_FREE>
            <xsl:value-of select="top:intmvaiBel"/>
          </ns1:CURR_TOTAL_NET_VAT_FREE>
          <ns1:CURR_TOTAL_VAT_AMT>
            <xsl:value-of select="top:intmvaBel"/>
          </ns1:CURR_TOTAL_VAT_AMT>
          <ns1:CURR_TOTAL_GROSS_AMT>
            <xsl:value-of select="top:inttotbrtBel"/>
          </ns1:CURR_TOTAL_GROSS_AMT>
          <ns1:CURR_TOTAL_GROSS_AMT_FOREIGN>
            <xsl:value-of select="top:intutlbrtBel"/>
          </ns1:CURR_TOTAL_GROSS_AMT_FOREIGN>
        </ns1:ValidationData>
      </xsl:for-each>
    </ns1:ValidationPayload>
  </xsl:template>
</xsl:stylesheet>
