<?binding.jca InsertErrorloggingDBAdapterV1_db.jca?>
<wsdl:definitions name="InsertErrorloggingDBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ErrorHandlingFramework/Common_ErrorHandler_Notification/InsertErrorloggingDBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ErrorHandlingFramework/Common_ErrorHandler_Notification/InsertErrorloggingDBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertErrorloggingDBAdapterV1">
    <plt:partnerLinkType name="InsertErrorloggingDBAdapterV1_plt">
        <plt:role name="InsertErrorloggingDBAdapterV1_role">
            <plt:portType name="tns:InsertErrorloggingDBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertErrorloggingDBAdapterV1" schemaLocation="xsd/InsertErrorloggingDBAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EngageSoaErrorLogsCollection_msg">
        <wsdl:part name="EngageSoaErrorLogsCollection" element="top:EngageSoaErrorLogsCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertErrorloggingDBAdapterV1_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:EngageSoaErrorLogsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
