package com.sfr.engage.model.queries.rvo;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 16 15:16:30 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrtExportInfoRVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        TotalColumns {
            public Object get(PrtExportInfoRVORowImpl obj) {
                return obj.getTotalColumns();
            }

            public void put(PrtExportInfoRVORowImpl obj, Object value) {
                obj.setTotalColumns((String)value);
            }
        }
        ,
        PrePopulatedColumns {
            public Object get(PrtExportInfoRVORowImpl obj) {
                return obj.getPrePopulatedColumns();
            }

            public void put(PrtExportInfoRVORowImpl obj, Object value) {
                obj.setPrePopulatedColumns((String)value);
            }
        }
        ,
        ExtraColumns {
            public Object get(PrtExportInfoRVORowImpl obj) {
                return obj.getExtraColumns();
            }

            public void put(PrtExportInfoRVORowImpl obj, Object value) {
                obj.setExtraColumns((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PrtExportInfoRVORowImpl object);

        public abstract void put(PrtExportInfoRVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TOTALCOLUMNS = AttributesEnum.TotalColumns.index();
    public static final int PREPOPULATEDCOLUMNS = AttributesEnum.PrePopulatedColumns.index();
    public static final int EXTRACOLUMNS = AttributesEnum.ExtraColumns.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrtExportInfoRVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute TotalColumns.
     * @return the TotalColumns
     */
    public String getTotalColumns() {
        return (String) getAttributeInternal(TOTALCOLUMNS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalColumns.
     * @param value value to set the  TotalColumns
     */
    public void setTotalColumns(String value) {
        setAttributeInternal(TOTALCOLUMNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrePopulatedColumns.
     * @return the PrePopulatedColumns
     */
    public String getPrePopulatedColumns() {
        return (String) getAttributeInternal(PREPOPULATEDCOLUMNS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrePopulatedColumns.
     * @param value value to set the  PrePopulatedColumns
     */
    public void setPrePopulatedColumns(String value) {
        setAttributeInternal(PREPOPULATEDCOLUMNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExtraColumns.
     * @return the ExtraColumns
     */
    public String getExtraColumns() {
        return (String) getAttributeInternal(EXTRACOLUMNS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExtraColumns.
     * @param value value to set the  ExtraColumns
     */
    public void setExtraColumns(String value) {
        setAttributeInternal(EXTRACOLUMNS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
