create or replace
TRIGGER PRT_CARD_TYPE_NAME_MAP_TRIG BEFORE INSERT ON PRT_CARD_TYPE_NAME_MAP
FOR EACH ROW 
BEGIN

if (:NEW.PRT_CARD_TYPE_NAME_MAP_PK IS NULL) then
SELECT PRT_CARD_TYPE_NAME_MAP_SEQ.NEXTVAL INTO :NEW.PRT_CARD_TYPE_NAME_MAP_PK FROM DUAL;
end if;
END;