CREATE TABLE PRT_CARD_INVOICE 
(
  COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, INVOICE_NUMBER VARCHAR2(9 BYTE) NOT NULL 
, COLLECTIVE_INVOICE_NUMBER VARCHAR2(9 BYTE) 
, INVOICE_DATE DATE 
, INVOICED_CARD VARCHAR2(10 BYTE) 
, CARD_TYPE VARCHAR2(3 BYTE) 
, MAGNETIC_CODE VARCHAR2(20 BYTE) 
, ROUTEX_VAT_INVOICE_NUMBER VARCHAR2(10 BYTE) 
, INVOICE_INFORMATION VARCHAR2(90 BYTE) 
, INVOICE_DELIVERY_ADDRESS VARCHAR2(110 BYTE) 
, NET_INVOICE_CODE VARCHAR2(3 BYTE) 
, ORIGINAL_INVOICE_NUMBER VARCHAR2(9 BYTE) 
, CORRECTION_PRESENTATION VARCHAR2(3 BYTE) 
, INV_TOTAL_GROSS_AMT_FOREIGN FLOAT(126) 
, INV_TOTAL_NET_VAT_MANDATORY FLOAT(126) 
, INV_TOTAL_NET_VAT_FREE FLOAT(126) 
, INV_TOTAL_VAT_AMT FLOAT(126) 
, INV_TOTAL_GROSS_AMT FLOAT(126) 
, CURR_TOTAL_NET_VAT_MANDATORY FLOAT(126) 
, CURR_TOTAL_NET_VAT_FREE FLOAT(126) 
, CURR_TOTAL_VAT_AMT FLOAT(126) 
, CURR_TOTAL_GROSS_AMT FLOAT(126) 
, CURR_TOTAL_GROSS_AMT_FOREIGN FLOAT(126) 
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_CARD_INVOICE_PK PRIMARY KEY 
  (
    COUNTRY_CODE 
  , INVOICE_NUMBER 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
PARTITION BY LIST (COUNTRY_CODE) 
(
  PARTITION PRT_CARD_INVOICE_SWEDEN VALUES ('SE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_INVOICE_NORWAY VALUES ('NO') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_INVOICE_DENMARK VALUES ('DK') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_INVOICE_LATVIA VALUES ('LV') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_INVOICE_LITHUANIA VALUES ('LT') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_INVOICE_ESTONIA VALUES ('EE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_INVOICE_POLAND VALUES ('PL') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
);
