CREATE TABLE PRT_GEN_HELP 
(
  ID NUMBER NOT NULL 
, KEY_QUEST VARCHAR2(100 BYTE) 
, KEY_ANSWER VARCHAR2(1024 BYTE) 
, LANG_CODE VARCHAR2(20 BYTE) 
, COUNTRY_CODE VARCHAR2(20 BYTE) 
, PORTAL_NAME VARCHAR2(20 BYTE) 
, MODIFIED_BY VARCHAR2(20 BYTE) 
, MODIFIED_DATE DATE 
, CONSTRAINT PRT_GEN_HELP_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);
