package com.sfr.engage.services.client.alertsSubscription;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebServiceClient(wsdlLocation="http://10.24.240.15:7021/soa-infra/services/CommonUtilities/SOARuleEngineSubscription/subscription_client_ep?WSDL",
  targetNamespace="http://www.lntinfotech.com/integration/SOARuleEngineSubscription/Subscription",
  name="subscription_client_ep")
public class Subscription_client_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.sfr.engage.services.client.alertsSubscription.Subscription_client_ep");
      URL baseUrl = Subscription_client_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            Subscription_client_ep.class.getResource("http://10.24.240.15:7021/soa-infra/services/CommonUtilities/SOARuleEngineSubscription/subscription_client_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://10.24.240.15:7021/soa-infra/services/CommonUtilities/SOARuleEngineSubscription/subscription_client_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://10.24.240.15:7021/soa-infra/services/CommonUtilities/SOARuleEngineSubscription/subscription_client_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://10.24.240.15:7021/soa-infra/services/CommonUtilities/SOARuleEngineSubscription/subscription_client_ep?WSDL",
          e);
    }
  }

  public Subscription_client_ep()
  {
    super(wsdlLocationURL,
          new QName("http://www.lntinfotech.com/integration/SOARuleEngineSubscription/Subscription",
                    "subscription_client_ep"));
  }

  public Subscription_client_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="Subscription_pt")
  public com.sfr.engage.services.client.alertsSubscription.Subscription getSubscription_pt()
  {
    return (com.sfr.engage.services.client.alertsSubscription.Subscription) super.getPort(new QName("http://www.lntinfotech.com/integration/SOARuleEngineSubscription/Subscription",
                                                                                                    "Subscription_pt"),
                                                                                          com.sfr.engage.services.client.alertsSubscription.Subscription.class);
  }

  @WebEndpoint(name="Subscription_pt")
  public com.sfr.engage.services.client.alertsSubscription.Subscription getSubscription_pt(WebServiceFeature... features)
  {
    return (com.sfr.engage.services.client.alertsSubscription.Subscription) super.getPort(new QName("http://www.lntinfotech.com/integration/SOARuleEngineSubscription/Subscription",
                                                                                                    "Subscription_pt"),
                                                                                          com.sfr.engage.services.client.alertsSubscription.Subscription.class,
                                                                                          features);
  }
}
