<?binding.jca MergePortalDataDBAdapterV1_db.jca?>
<wsdl:definitions name="MergePortalDataDBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E003AccountSummaryPALStoPortalApp/E003AccountSummaryPALStoPortal/MergePortalDataDBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E003AccountSummaryPALStoPortalApp/E003AccountSummaryPALStoPortal/MergePortalDataDBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergePortalDataDBAdapterV1">
    <plt:partnerLinkType name="MergePortalDataDBAdapterV1_plt">
        <plt:role name="MergePortalDataDBAdapterV1_role">
            <plt:portType name="tns:MergePortalDataDBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergePortalDataDBAdapterV1" schemaLocation="xsd/MergePortalDataDBAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PrtPartnerCollection_msg">
        <wsdl:part name="PrtPartnerCollection" element="top:PrtPartnerCollection"/>
    </wsdl:message>
    <wsdl:portType name="MergePortalDataDBAdapterV1_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:PrtPartnerCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
