<?binding.jca SelectPALSDB2DBAdapterV1_db.jca?>
<wsdl:definitions name="SelectPALSDB2DBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E003AccountSummaryPALStoPortalApp/E003AccountSummaryPALStoPortal/SelectPALSDB2DBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E003AccountSummaryPALStoPortalApp/E003AccountSummaryPALStoPortal/SelectPALSDB2DBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectPALSDB2DBAdapterV1">
    <plt:partnerLinkType name="SelectPALSDB2DBAdapterV1_plt">
        <plt:role name="SelectPALSDB2DBAdapterV1_role">
            <plt:portType name="tns:SelectPALSDB2DBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectPALSDB2DBAdapterV1" schemaLocation="xsd/SelectPALSDB2DBAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SelectPALSDB2DBAdapterV1Select_inputParameters">
        <wsdl:part name="SelectPALSDB2DBAdapterV1Select_inputParameters" element="top:SelectPALSDB2DBAdapterV1Select_DeltaTimeStamp_BatchSizeInputParameters"/>
    </wsdl:message>
    <wsdl:message name="Cc070Vs1CssparDtaCollection_msg">
        <wsdl:part name="Cc070Vs1CssparDtaCollection" element="top:Cc070Vs1CssparDtaCollection"/>
    </wsdl:message>
    <wsdl:portType name="SelectPALSDB2DBAdapterV1_ptt">
        <wsdl:operation name="SelectPALSDB2DBAdapterV1Select">
            <wsdl:input message="tns:SelectPALSDB2DBAdapterV1Select_inputParameters"/>
            <wsdl:output message="tns:Cc070Vs1CssparDtaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
