CREATE TABLE PRT_CARD_TRANSACTION_DETAIL 
(
  DELTA_TIMESTAMP DATE 
, UREF_TRANSACTION_ID VARCHAR2(10 BYTE) NOT NULL 
, PALS_COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, DETAIL_NO VARCHAR2(5 BYTE) 
, PALS_P_GROUP_ID VARCHAR2(2 BYTE) 
, PALS_P_GROUP_SUBGROUP_ID VARCHAR2(3 BYTE) 
, FUEL_YN VARCHAR2(1 BYTE) 
, PRODUCT_NAME VARCHAR2(30 BYTE) 
, QUANTITY NUMBER 
, UNIT_OF_MEASURE VARCHAR2(10 BYTE) 
, VAT_RATE NUMBER 
, CURRENCY_VAT FLOAT(126) 
, INVOICED_VAT FLOAT(126) 
, CURRENCY_UNIT_PRICE FLOAT(126) 
, INVOICED_UNIT_PRICE FLOAT(126) 
, CURRENCY_GROSS_AMOUNT FLOAT(126) 
, INVOICED_GROSS_AMOUNT FLOAT(126) 
, CURRENCY_NET_AMOUNT FLOAT(126) 
, INVOICED_NET_AMOUNT FLOAT(126) 
, CURRENCY_DISCOUNT_AMOUNT FLOAT(126) 
, INVOICE_DISCOUNT_AMOUNT FLOAT(126) 
, VAT_REFUNDABLE_YN VARCHAR2(1 BYTE) 
, SURCHARGE_YN VARCHAR2(1 BYTE) 
, AT_IABF538A_PRPSL_KD VARCHAR2(3 BYTE) 
, AS_IABF538A_PRPSLSATS NUMBER 
, CONSTRAINT PRT_CARD_TRANSACTION_DETA_PK PRIMARY KEY 
  (
    UREF_TRANSACTION_ID 
  , PALS_COUNTRY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE PRT_CARD_TRANSACTION_DETAIL
ADD CONSTRAINT PRT_CARD_TRANSACTION_DETA_FK1 FOREIGN KEY
(
  UREF_TRANSACTION_ID 
, PALS_COUNTRY_CODE 
)
REFERENCES PRT_CARD_TRANSACTION_HEADER
(
  UREF_TRANSACTION_ID 
, PALS_COUNTRY_CODE 
)
ON DELETE CASCADE ENABLE;
