CREATE TABLE PRT_CARD_TYPE_NAME_MAP 
(
  PRT_CARD_TYPE_NAME_MAP_PK NUMBER NOT NULL 
, CARD_TYPE VARCHAR2(20 BYTE) NOT NULL 
, TYPE_NAME VARCHAR2(20 BYTE) NOT NULL 
, COUNTRY VARCHAR2(2 BYTE) NOT NULL 
, MODIFIED_BY VARCHAR2(20 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_CARD_TYPE_NAME_MAP_PK PRIMARY KEY 
  (
    PRT_CARD_TYPE_NAME_MAP_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);
