CREATE TABLE PRT_PARTNER 
(
  COUNTRY_CODE VARCHAR2(8 BYTE) NOT NULL 
, PARTNER_ID VARCHAR2(8 BYTE) NOT NULL 
, LASTNAME_1 VARCHAR2(20 BYTE) 
, LASTNAME_2 VARCHAR2(5 BYTE) 
, LASTNAME VARCHAR2(25 BYTE) 
, SHORT_NAME VARCHAR2(30 BYTE) 
, PARTNER_TYPE VARCHAR2(3 BYTE) 
, PARTNER_CUSTOMER_GRP VARCHAR2(3 BYTE) 
, CREDIT_BLOCK_CODE VARCHAR2(3 BYTE) 
, PARTNER_ALFA1 VARCHAR2(5 BYTE) 
, PARTNER_ALFA2 VARCHAR2(10 BYTE) 
, CREATION_DATE DATE 
, CREATED_BY VARCHAR2(6 BYTE) 
, CHANGE_DATE DATE 
, CHANGE_BY VARCHAR2(6 BYTE) 
, PHONE_NUMBER VARCHAR2(15 BYTE) 
, FAX_NUMBER VARCHAR2(15 BYTE) 
, PARTNER_BLOCK_CODE VARCHAR2(3 BYTE) 
, PARTNER_DELETE_CODE VARCHAR2(3 BYTE) 
, WRITE_OFF_REASON VARCHAR2(3 BYTE) 
, CREDIT_LIMIT VARCHAR2(3 BYTE) 
, MARKETING_CODE VARCHAR2(3 BYTE) 
, COMPANY_TYPE VARCHAR2(3 BYTE) 
, ORG_ID VARCHAR2(10 BYTE) 
, ESTB_YEAR VARCHAR2(4 BYTE) 
, DOB DATE 
, GENDER VARCHAR2(1 BYTE) 
, FIRSTNAME_1 VARCHAR2(10 BYTE) 
, FIRSTNAME_2 VARCHAR2(15 BYTE) 
, FIRSTNAME VARCHAR2(25 BYTE) 
, PERSON_TITLE VARCHAR2(25 BYTE) 
, NAME_DESC VARCHAR2(15 BYTE) 
, RATING_CODE VARCHAR2(3 BYTE) 
, RATING_DATE DATE 
, VERSION_NUMBER NUMBER(*, 0) 
, ACCOUNT_BLOCK VARCHAR2(3 BYTE) 
, PHONE_NUMBER2 VARCHAR2(15 BYTE) 
, CREDIT_WARNING_CODE VARCHAR2(3 BYTE) 
, FIRST_LAST_NAME VARCHAR2(40 BYTE) 
, VAT_REG_NUMBER VARCHAR2(20 BYTE) 
, NACE_CODE VARCHAR2(10 BYTE) 
, LOYALTY_MEMBER_CODE VARCHAR2(3 BYTE) 
, MOBILE_NUMBER VARCHAR2(15 BYTE) 
, PERSON_NUMBER VARCHAR2(15 BYTE) 
, CUSTOMER_BLOCK_DATE DATE 
, CUSTOMER_BLOCK_TIME TIMESTAMP(6) 
, GUARANTEE_TYPE VARCHAR2(3 BYTE) 
, CUSTOMER_LIMIT_AMOUNT NUMBER(4, 0) 
, CREDIT_EXPOSURE_CODE VARCHAR2(3 BYTE) 
, MODIFIED_BY VARCHAR2(20 BYTE) 
, MODIFIED_DATE TIMESTAMP(6) 
, CONSTRAINT PRT_PARTNER_PK PRIMARY KEY 
  (
    COUNTRY_CODE 
  , PARTNER_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
PARTITION BY LIST (COUNTRY_CODE) 
(
  PARTITION PRT_PARTNER_SE VALUES ('se_SE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_PARTNER_NO VALUES ('no_NO') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 8388608 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
);
