CREATE TABLE PRT_PCM_FEEDS 
(
  PRT_PCM_FEEDS_PK NUMBER NOT NULL 
, CUSTOMER_TYPE VARCHAR2(20 BYTE) NOT NULL 
, INFORMATION_TYPE VARCHAR2(20 BYTE) NOT NULL 
, PROMOTION_CHECK CHAR(3 BYTE) NOT NULL 
, EFFECTIVE_DATE DATE NOT NULL 
, END_DATE DATE NOT NULL 
, MESSAGE_LANG VARCHAR2(150 BYTE) NOT NULL 
, MESSAGE_ENGLISH VARCHAR2(150 BYTE) 
, COUNTRY_CODE VARCHAR2(8 BYTE) NOT NULL 
, MODIFIED_BY VARCHAR2(20 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_PCM_FEEDS_PK PRIMARY KEY 
  (
    PRT_PCM_FEEDS_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);
