CREATE TABLE PRT_CARD_TRANSACTION_DETAIL 
(
  DELTA_TIMESTAMP TIMESTAMP(6) 
, UREF_TRANSACTION_ID VARCHAR2(10 BYTE) NOT NULL 
, PALS_COUNTRY_CODE VARCHAR2(8 BYTE) NOT NULL 
, DETAIL_NO VARCHAR2(5 BYTE) NOT NULL 
, PALS_P_GROUP_ID VARCHAR2(2 BYTE) 
, PALS_P_GROUP_SUBGROUP_ID VARCHAR2(3 BYTE) 
, FUEL_YN VARCHAR2(1 BYTE) 
, PRODUCT_NAME VARCHAR2(30 BYTE) 
, QUANTITY NUMBER 
, UNIT_OF_MEASURE VARCHAR2(10 BYTE) 
, VAT_RATE NUMBER 
, CURRENCY_VAT FLOAT(126) 
, INVOICED_VAT FLOAT(126) 
, CURRENCY_UNIT_PRICE FLOAT(126) 
, INVOICED_UNIT_PRICE FLOAT(126) 
, CURRENCY_GROSS_AMOUNT FLOAT(126) 
, INVOICED_GROSS_AMOUNT FLOAT(126) 
, CURRENCY_NET_AMOUNT FLOAT(126) 
, INVOICED_NET_AMOUNT FLOAT(126) 
, CURRENCY_DISCOUNT_AMOUNT FLOAT(126) 
, INVOICE_DISCOUNT_AMOUNT FLOAT(126) 
, VAT_REFUNDABLE_YN VARCHAR2(1 BYTE) 
, SURCHARGE_YN VARCHAR2(1 BYTE) 
, AT_IABF538A_PRPSL_KD VARCHAR2(3 BYTE) 
, AS_IABF538A_PRPSLSATS NUMBER 
, CURRENCY_VAT_REBATED FLOAT(126) 
, INVOIVED_VAT_REBATED FLOAT(126) 
, CURRENCY_UNIT_PRICE_REBATED FLOAT(126) 
, INVOICED_UNIT_PRICE_REBATED FLOAT(126) 
, CURRENCY_GROSS_AMOUNT_REBATED FLOAT(126) 
, INVOICED_GROSS_AMOUNT_REBATED FLOAT(126) 
, CURRENCY_NET_AMOUNT_REBATED FLOAT(126) 
, INVOICED_NET_AMOUNT_RABETED FLOAT(126) 
, CONSTRAINT PRT_CARD_TRANSACTION_DETA_PK PRIMARY KEY 
  (
    UREF_TRANSACTION_ID 
  , PALS_COUNTRY_CODE 
  , DETAIL_NO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 8 
  NEXT 128 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
PARTITION BY LIST (PALS_COUNTRY_CODE) 
(
  PARTITION PRT_CARD_TRANSACTION_DETAIL_SE VALUES ('se_SE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_TRANSACTION_DETAIL_NO VALUES ('no_NO') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
);

ALTER TABLE PRT_CARD_TRANSACTION_DETAIL
ADD CONSTRAINT PRT_CARD_TRANSACTION_DETA_FK1 FOREIGN KEY
(
  UREF_TRANSACTION_ID 
, PALS_COUNTRY_CODE 
)
REFERENCES PRT_CARD_TRANSACTION_HEADER
(
  UREF_TRANSACTION_ID 
, PALS_COUNTRY_CODE 
)
ON DELETE CASCADE ENABLE;
