CREATE TABLE PRT_CARD_NOTIFICATIONS 
(
  COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, NOTI_ID NUMBER NOT NULL 
, RULE_ID VARCHAR2(20 BYTE) NOT NULL 
, RULE_ISENABLED CHAR(3 BYTE) NOT NULL 
, SUB_ID VARCHAR2(20 BYTE) NOT NULL 
, USER_ID VARCHAR2(50 BYTE) NOT NULL 
, PARTNER VARCHAR2(8 BYTE) 
, ACCOUNT_ID VARCHAR2(10 BYTE) 
, CARDGROUP_MAIN VARCHAR2(3 BYTE) 
, CARDGROUP_SUB VARCHAR2(3 BYTE) 
, CARDGROUP_SEQ VARCHAR2(5 BYTE) 
, CARD_PK VARCHAR2(20 BYTE) 
, EMBOSS_CARD_NUM VARCHAR2(20 BYTE) 
, TRANSACTION_TIME TIMESTAMP(6) 
, NOTI_CREATED TIMESTAMP(6) 
, NOTI_CATEGORY VARCHAR2(30 BYTE) 
, NOTI_SUBCATEGORY VARCHAR2(30 BYTE) 
, SHOW_FLAG CHAR(3 BYTE) NOT NULL 
, NOTI_DESCRIPTION VARCHAR2(50 BYTE) 
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_CARD_NOTIFICATIONS_PK PRIMARY KEY 
  (
   NOTI_ID 
  )
  ENABLE 
) 

PARTITION BY LIST(COUNTRY_CODE) (
    PARTITION PRT_CARD_NOTIFI_SWEDEN VALUES ('SE'),
    PARTITION PRT_CARD_NOTIFI_NORWAY VALUES ('NO'),
    PARTITION PRT_CARD_NOTIFI_DENMARK VALUES ('DK'),
    PARTITION PRT_CARD_NOTIFI_LATVIA VALUES ('LV'),
    PARTITION PRT_CARD_NOTIFI_LITHUANIA VALUES ('LT'),
    PARTITION PRT_CARD_NOTIFI_ESTONIA VALUES ('EE'),
    PARTITION PRT_CARD_NOTIFI_POLAND VALUES ('PL')
)

LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);
