CREATE TABLE PRT_ACCOUNT 
(
  COUNTRY_CODE VARCHAR2(8 BYTE) NOT NULL 
, ACCOUNT_ID VARCHAR2(10 BYTE) NOT NULL 
, PARTNER_ID VARCHAR2(8 BYTE) 
, CREATED_DATE DATE 
, CREATED_BY VARCHAR2(6 BYTE) 
, CHANGE_DATE DATE 
, CHANGE_BY VARCHAR2(6 BYTE) 
, ACCOUNT_RECON_CODE VARCHAR2(1 BYTE) 
, ACCOUNT_STMT_CODE VARCHAR2(1 BYTE) 
, INTEREST_CODE VARCHAR2(1 BYTE) 
, ACCOUNT_GROUP VARCHAR2(2 BYTE) 
, BLOCK_CODE VARCHAR2(3 BYTE) 
, ACCOUNT_DESC VARCHAR2(20 BYTE) 
, CREDIT_BLOCK_CODE VARCHAR2(3 BYTE) 
, VERSION_NUMBER NUMBER(*, 0) 
, DUNNING_LEVEL_CODE VARCHAR2(3 BYTE) 
, CREDIT_BLOCK_DATE DATE 
, CREDIT_BLOCK_TIME TIMESTAMP(6) 
, ACCOUNT_BLOCK_DATE DATE 
, ACCOUNT_BLOCK_TIME TIMESTAMP(6) 
, DUNNING_PROC_ID VARCHAR2(4 BYTE) 
, GIRO_NUMBER VARCHAR2(16 BYTE) 
, MODIFIED_BY VARCHAR2(20 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_ACCOUNT_PK PRIMARY KEY 
  (
    COUNTRY_CODE 
  , ACCOUNT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 2 
  NEXT 1 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
PARTITION BY LIST (COUNTRY_CODE) 
(
  PARTITION PRT_ACCOUNT_SE VALUES ('se_SE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_ACCOUNT_NO VALUES ('no_NO') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
);

ALTER TABLE PRT_ACCOUNT
ADD CONSTRAINT PRT_ACCOUNT_PRT_PARTNER_FK1 FOREIGN KEY
(
  COUNTRY_CODE 
, PARTNER_ID 
)
REFERENCES PRT_PARTNER
(
  COUNTRY_CODE 
, PARTNER_ID 
)
ENABLE;
