CREATE TABLE PRT_PCM_FEEDS 
(
  PRT_PCM_FEEDS_PK NUMBER NOT NULL 
, CUSTOMER_TYPE VARCHAR2(20 BYTE) NOT NULL 
, INFORMATION_TYPE VARCHAR2(20 BYTE) NOT NULL 
, PROMOTION_CHECK CHAR(3 BYTE) 
, EFFECTIVE_DATE DATE NOT NULL 
, END_DATE DATE NOT NULL 
, MESSAGE_LANG VARCHAR2(1024 BYTE) NOT NULL 
, MESSAGE_ENGLISH VARCHAR2(1024 BYTE) 
, COUNTRY_CODE VARCHAR2(8 BYTE) NOT NULL 
, MODIFIED_BY VARCHAR2(20 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, TITLE VARCHAR2(200 BYTE) 
, SHOW_FLAG CHAR(3 BYTE) 
, CONSTRAINT PRT_PCM_FEEDS_PK PRIMARY KEY 
  (
    PRT_PCM_FEEDS_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);
