CREATE TABLE PRT_DRIVER_INFORMATION 
(
  PRT_DRIVER_INFORMATION_PK VARCHAR2(20 BYTE) NOT NULL 
, COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, ACCOUNT_NUMBER VARCHAR2(10 BYTE) NOT NULL 
, CARD_NUMBER VARCHAR2(30 BYTE) 
, DRIVER_NUMBER VARCHAR2(20 BYTE) NOT NULL 
, DRIVER_NAME VARCHAR2(30 BYTE) NOT NULL 
, NATIONALITY VARCHAR2(15 BYTE) 
, MOBILE_NUMBER NUMBER 
, REMARKS VARCHAR2(30 BYTE) 
, PASSPORT_NUMBER VARCHAR2(20 BYTE) 
, PASSPORT_EXPIRY DATE 
, LICENSE_NUMBER VARCHAR2(20 BYTE) 
, LICENSE_EXPIRY DATE 
, EMPLOY_START DATE 
, EMPLOY_END DATE 
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, REFERENCE_NUMBER VARCHAR2(10 BYTE) 
, CONSTRAINT PRT_DRIVER_INFORMATION_PK PRIMARY KEY 
  (
    PRT_DRIVER_INFORMATION_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
PARTITION BY LIST (COUNTRY_CODE) 
(
  PARTITION PRT_DRIVER_INFO_SWEDEN VALUES ('SE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 8388608 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_DRIVER_INFO_NORWAY VALUES ('NO') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 8388608 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_DRIVER_INFO_DENMARK VALUES ('DK') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 8388608 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_DRIVER_INFO_LATVIA VALUES ('LV') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_DRIVER_INFO_LITHUANIA VALUES ('LT') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_DRIVER_INFO_ESTONIA VALUES ('EE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_DRIVER_INFO_POLAND VALUES ('PL') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
);
