CREATE TABLE PRT_ACCOUNT_AUDIT 
(
  AUDIT_ID NUMBER NOT NULL 
, COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, ACCOUNT_ID VARCHAR2(10 BYTE) NOT NULL 
, OLD_PARTNER_ID VARCHAR2(8 BYTE) 
, OLD_CUSTOMER_GROUP VARCHAR2(2 BYTE) 
, OLD_MODIFIED_BY VARCHAR2(50 BYTE) 
, OLD_MODIFIED_DATE TIMESTAMP(6) 
, NEW_PARTNER_ID VARCHAR2(8 BYTE) 
, NEW_CUSTOMER_GROUP VARCHAR2(2 BYTE) 
, NEW_MODIFIED_BY VARCHAR2(50 BYTE) 
, NEW_MODIFIED_DATE TIMESTAMP(6) 
, U_ID VARCHAR2(50 BYTE) 
, ACTION VARCHAR2(20 BYTE) 
, NEW_TIMESTAMP DATE 


, CONSTRAINT PRT_ACCOUNT_AUDIT_PK PRIMARY KEY 
  (
   AUDIT_ID 
  )
  ENABLE 
) 

PARTITION BY LIST(COUNTRY_CODE) (
    PARTITION PRT_ACCOUNT_AUDIT_SWEDEN VALUES ('SE'),
    PARTITION PRT_ACCOUNT_AUDIT_NORWAY VALUES ('NO'),
    PARTITION PRT_ACCOUNT_AUDIT_DENMARK VALUES ('DK'),
    PARTITION PRT_ACCOUNT_AUDIT_LATVIA VALUES ('LV'),
    PARTITION PRT_ACCOUNT_AUDIT_LITHUANIA VALUES ('LT'),
    PARTITION PRT_ACCOUNT_AUDIT_ESTONIA VALUES ('EE'),
    PARTITION PRT_ACCOUNT_AUDIT_POLAND VALUES ('PL')
);

