CREATE TABLE PRT_CARDGROUP 
(
  COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, PARTNER_ID VARCHAR2(8 BYTE) NOT NULL 
, ACCOUNT_ID VARCHAR2(10 BYTE) NOT NULL 
, CARDGROUP_MAIN_TYPE VARCHAR2(3 BYTE) NOT NULL 
, CARDGROUP_SUB_TYPE VARCHAR2(3 BYTE) NOT NULL 
, CARDGROUP_SEQ VARCHAR2(5 BYTE) NOT NULL
, CARDGROUP_DESCRIPTION VARCHAR2(45 BYTE)
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 

, ESTB_GROUP VARCHAR2(3 BYTE) 
, BUSI_RELATION_GROUP VARCHAR2(3 BYTE) 
, CREATED_DATE DATE 
, CREATED_BY VARCHAR2(6 BYTE) 
, CHANGE_DATE DATE 
, CHANGE_BY VARCHAR2(6 BYTE) 
, PAY_PROOF VARCHAR2(1 BYTE) 
, DELETE_CODE VARCHAR2(3 BYTE) 
, MARKETING_CODE VARCHAR2(3 BYTE) 
, ARCHIVE_REF VARCHAR2(10 BYTE) 
, NOT_AVG_FROM VARCHAR2(4 BYTE) 
, NOT_AVG_TO VARCHAR2(4 BYTE) 
, PAY_DOC_LEVEL VARCHAR2(3 BYTE) 
, BUSI_RELATION_NACE VARCHAR2(10 BYTE) 
, DEBIT_BANK_ACCOUNT VARCHAR2(16 BYTE) 
, DEBIT_REF_NUMBER VARCHAR2(15 BYTE) 
, BUSI_RELATION_DESC VARCHAR2(30 BYTE) 
, PURCHASE_LIMIT_CODE VARCHAR2(3 BYTE) 
, BLOCK_CODE VARCHAR2(3 BYTE) 
, BLOCK_DATE DATE 
, BLOCK_TIME TIMESTAMP(6) 
, CONSTRAINT PRT_CARDGROUP_PK PRIMARY KEY 
  (
    PARTNER_ID 
  , CARDGROUP_MAIN_TYPE 
  , CARDGROUP_SUB_TYPE 
  , CARDGROUP_SEQ 
  , COUNTRY_CODE 
  )
  ENABLE 
) 

PARTITION BY LIST(COUNTRY_CODE) (
    PARTITION PRT_CARDGROUP_SWEDEN VALUES ('SE'),
    PARTITION PRT_CARDGROUP_NORWAY VALUES ('NO'),
    PARTITION PRT_CARDGROUP_DENMARK VALUES ('DK'),
    PARTITION PRT_CARDGROUP_LATVIA VALUES ('LV'),
    PARTITION PRT_CARDGROUP_LITHUANIA VALUES ('LT'),
    PARTITION PRT_CARDGROUP_ESTONIA VALUES ('EE'),
    PARTITION PRT_CARDGROUP_POLAND VALUES ('PL')
)

LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE PRT_CARDGROUP
ADD CONSTRAINT PRT_CARDGROUP_PRT_ACCOUNT_FK1 FOREIGN KEY
(
  COUNTRY_CODE 
, ACCOUNT_ID 
)
REFERENCES PRT_ACCOUNT
(
  COUNTRY_CODE 
, ACCOUNT_ID 
)
ENABLE;

ALTER TABLE PRT_CARDGROUP
ADD CONSTRAINT PRT_CARDGROUP_PRT_PARTNER_FK1 FOREIGN KEY
(
  COUNTRY_CODE 
, PARTNER_ID 
)
REFERENCES PRT_PARTNER
(
  COUNTRY_CODE 
, PARTNER_ID 
)
ENABLE;
