CREATE TABLE PRT_CARD_PAYMENT_DOC 
(
  COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, INVOICE_DOC_NUMBER VARCHAR2(9 BYTE) NOT NULL 
, INVOICE_DOC_TYPE VARCHAR2(3 BYTE) NOT NULL 
, PARTNER_ID VARCHAR2(8 BYTE) NOT NULL
, COMPANY_TYPE VARCHAR2(3 BYTE) 
, ACCOUNT_ID VARCHAR2(10 BYTE) 
, CARDGROUP_MAIN_TYPE VARCHAR2(3 BYTE) 
, CARDGROUP_SUB_TYPE VARCHAR2(3 BYTE) 
, CARDGROUP_SEQ VARCHAR2(5 BYTE) 
, INVOICING_DATE DATE 
, INVOICING_DUE_DATE DATE 
, INVOICE_LEVEL VARCHAR2(3 BYTE) 
, PAYMENT_CODE VARCHAR2(3 BYTE) 
, ELECTRONIC_INVOICE_TYPE VARCHAR2(3 BYTE) 
, INVOICE_LANG_CODE VARCHAR2(3 BYTE) 
, GROUPING_INVOICE_TYPE VARCHAR2(3 BYTE) 
, PRINT_INVOICE VARCHAR2(1 BYTE) 
, PARTNER_SHORTNAME VARCHAR2(45 BYTE) 
, INVOICE_ADDR1 VARCHAR2(60 BYTE) 
, INVOICE_ADDR2 VARCHAR2(60 BYTE) 
, INVOICE_ADDR3 VARCHAR2(60 BYTE) 
, INVOICE_COUNTRY VARCHAR2(45 BYTE) 
, INVOICE_RECEIVER VARCHAR2(60 BYTE) 
, COMPANY_NAME VARCHAR2(60 BYTE) 
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_CARD_PAYMENT_DOC_PK PRIMARY KEY 
  (
    COUNTRY_CODE 
  , INVOICE_DOC_NUMBER 
  , INVOICE_DOC_TYPE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
PARTITION BY LIST (COUNTRY_CODE) 
(
  PARTITION PRT_CARD_PAYMENT_DOC_SWEDEN VALUES ('SE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_PAYMENT_DOC_NORWAY VALUES ('NO') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_PAYMENT_DOC_DENMARK VALUES ('DK') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_PAYMENT_DOC_LATVIA VALUES ('LV') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_PAYMENT_DOC_LITHUANIA VALUES ('LT') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_PAYMENT_DOC_ESTONIA VALUES ('EE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_PAYMENT_DOC_POLAND VALUES ('PL') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
);
