CREATE TABLE PRT_CARD 
(
  COUNTRY_CODE VARCHAR2(8 BYTE) NOT NULL 
, PARTNER_ID VARCHAR2(8 BYTE) NOT NULL 
, ACCOUNT_ID VARCHAR2(10 BYTE) 
, CARDGROUP_MAIN_TYPE VARCHAR2(3 BYTE) NOT NULL 
, CARDGROUP_SUB_TYPE VARCHAR2(3 BYTE) NOT NULL 
, CARDGROUP_SEQ VARCHAR2(5 BYTE) NOT NULL 
, PRT_CARD_PK VARCHAR2(10 BYTE) NOT NULL 
, CREATED_DATE DATE 
, CREATED_BY VARCHAR2(6 BYTE) 
, CHANGE_DATE DATE 
, CHANGE_BY VARCHAR2(6 BYTE) 
, BLOCK_CODE VARCHAR2(3 BYTE) 
, VERSION_NUMBER NUMBER(*, 0) 
, MODIFIED_BY VARCHAR2(20 BYTE) 
, MODIFIED_DATE TIMESTAMP(6) 
, CARD_TYPE VARCHAR2(3 BYTE) 
, CUSTOMER_GROUP VARCHAR2(2 BYTE) 
, PREV_CARD_ID VARCHAR2(10 BYTE) 
, PHYSICAL_CARD_ID VARCHAR2(10 BYTE) 
, CARD_ISSUE_DATE DATE 
, CARD_RETURN_DATE DATE 
, CARD_EXPIRY DATE 
, PURCHASE_PROFILE_CODE VARCHAR2(3 BYTE) 
, NUM_PRINTLINES NUMBER(*, 0) 
, CARD_APP_ID VARCHAR2(7 BYTE) 
, GEO_USE_REF VARCHAR2(10 BYTE) 
, CARD_STATUS_CODE VARCHAR2(3 BYTE) 
, EXT_CARD_NUM VARCHAR2(20 BYTE) NOT NULL 
, CARD_RENEW_DATE DATE 
, CARD_EMBOSS_NUM VARCHAR2(20 BYTE) 
, CARD_RENEW_BLOCK VARCHAR2(1 BYTE) 
, PIN_OFFSET NUMBER(4, 0) 
, CARD_DESIGN_CODE VARCHAR2(6 BYTE) 
, CARD_CREATED_BY VARCHAR2(6 BYTE) 
, CARD_COPIES NUMBER(*, 0) 
, CARD_SEARCH_ID VARCHAR2(20 BYTE) 
, MAGNETIC_CODE VARCHAR2(3 BYTE) 
, DEBIT_BANK_ACCOUNT VARCHAR2(16 BYTE) 
, DEBIT_AGREE_REF VARCHAR2(15 BYTE) 
, BLOCK_DATE DATE 
, BLOCK_TIME TIMESTAMP(6) 
, DELETION_CODE VARCHAR2(3 BYTE) 
, SPERREBEH_KD VARCHAR2(3 BYTE) 
, SPERRELISTE_DT DATE 
, SPESIALBEST_JN VARCHAR2(1 BYTE) 
, CONSTRAINT PRT_CARD_PK PRIMARY KEY 
  (
    COUNTRY_CODE 
  , PRT_CARD_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
PARTITION BY LIST (COUNTRY_CODE) 
(
  PARTITION PRT_CARD_SE VALUES ('se_SE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_NO VALUES ('no_NO') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 8388608 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
);

ALTER TABLE PRT_CARD
ADD CONSTRAINT PRT_CARD_PRT_ACCOUNT_FK1 FOREIGN KEY
(
  COUNTRY_CODE 
, ACCOUNT_ID 
)
REFERENCES PRT_ACCOUNT
(
  COUNTRY_CODE 
, ACCOUNT_ID 
)
ENABLE;

ALTER TABLE PRT_CARD
ADD CONSTRAINT PRT_CARD_PRT_CARDGROUP_FK1 FOREIGN KEY
(
  PARTNER_ID 
, CARDGROUP_MAIN_TYPE 
, CARDGROUP_SUB_TYPE 
, CARDGROUP_SEQ 
, COUNTRY_CODE 
)
REFERENCES PRT_CARDGROUP
(
  PARTNER_ID 
, CARDGROUP_MAIN_TYPE 
, CARDGROUP_SUB_TYPE 
, CARDGROUP_SEQ 
, COUNTRY_CODE 
)
ENABLE;

ALTER TABLE PRT_CARD
ADD CONSTRAINT PRT_CARD_PRT_PARTNER_FK1 FOREIGN KEY
(
  COUNTRY_CODE 
, PARTNER_ID 
)
REFERENCES PRT_PARTNER
(
  COUNTRY_CODE 
, PARTNER_ID 
)
ENABLE;
