CREATE TABLE PRT_INVOICE 
(
  INVOICE_NUMBER VARCHAR2(20 BYTE) NOT NULL 
, COUNTRY_CODE VARCHAR2(8 BYTE) NOT NULL 
, CURRENCY_CODE VARCHAR2(8 BYTE) NOT NULL 
, INVOICE_DATE DATE NOT NULL 
, INVOICE_TYPE VARCHAR2(10 BYTE) NOT NULL 
, INVOICE_SUB_TYPE VARCHAR2(15 BYTE) NOT NULL 
, INVOICE_DUE_DATE DATE NOT NULL 
, NET NUMBER NOT NULL 
, VAT NUMBER NOT NULL 
, TOTAL_AMOUNT NUMBER NOT NULL 
, ACCOUNT_ID VARCHAR2(10 BYTE) 
, INVOICE_UCM_TYPE VARCHAR2(15 BYTE) NOT NULL 
, INVOICE_GROUPING VARCHAR2(20 BYTE) NOT NULL 
, PARTNER_ID VARCHAR2(8 BYTE) NOT NULL 
, CARDGROUP_MAIN_TYPE VARCHAR2(3 BYTE) 
, CARDGROUP_SUB_TYPE VARCHAR2(3 BYTE) 
, CARDGROUP_SEQ VARCHAR2(5 BYTE) 
, CARD_INTERNAL_ID VARCHAR2(20 BYTE) 
, ADDRESS_1 VARCHAR2(20 BYTE) 
, INVOICE_PAY_REF NUMBER NOT NULL 
, PRT_CARD_PK VARCHAR2(10 BYTE) NOT NULL 
, ADDRESS_2 VARCHAR2(20 BYTE) 
, CITY VARCHAR2(20 BYTE) 
, POSTAL_CODE VARCHAR2(20 BYTE) 
, CONSTRAINT PRT_INVOICE_PK PRIMARY KEY 
  (
    INVOICE_NUMBER 
  , COUNTRY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
PARTITION BY LIST (COUNTRY_CODE) 
(
  PARTITION PRT_INVOICE_SE VALUES ('se_SE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_INVOICE_NO VALUES ('no_NO') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
);
