CREATE TABLE PRT_CARD_TYPE_NAME_MAP 
(
  PRT_CARD_TYPE_NAME_MAP_PK NUMBER NOT NULL 
, CARD_TYPE VARCHAR2(20 BYTE) NOT NULL 
, TYPE_NAME VARCHAR2(50 BYTE) NOT NULL 
, COUNTRY VARCHAR2(2 BYTE) NOT NULL 
, MODIFIED_BY VARCHAR2(20 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_CARD_TYPE_NAME_MAP_PK PRIMARY KEY 
  (
    PRT_CARD_TYPE_NAME_MAP_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);


CREATE SEQUENCE PRT_CARD_TYPE_NAME_MAP_SEQ INCREMENT BY 1 MAXVALUE 999999 MINVALUE 1 CACHE 20;


CREATE TRIGGER PRT_CARD_TYPE_NAME_MAP_TRIG BEFORE INSERT ON PRT_CARD_TYPE_NAME_MAP
FOR EACH ROW 
BEGIN

if (:NEW.PRT_CARD_TYPE_NAME_MAP_PK IS NULL) then
SELECT PRT_CARD_TYPE_NAME_MAP_SEQ.NEXTVAL INTO :NEW.PRT_CARD_TYPE_NAME_MAP_PK FROM DUAL;
end if;
END;
/
