CREATE TABLE PRT_CARDGROUP_AUDIT
(
  AUDIT_ID NUMBER NOT NULL 
, COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, OLD_PARTNER_ID VARCHAR2(8 BYTE)  
, OLD_ACCOUNT_ID VARCHAR2(10 BYTE)  
, OLD_CARDGROUP_MAIN_TYPE VARCHAR2(3 BYTE)  
, OLD_CARDGROUP_SUB_TYPE VARCHAR2(3 BYTE)  
, OLD_CARDGROUP_SEQ VARCHAR2(5 BYTE) 
, OLD_CARDGROUP_DESCRIPTION VARCHAR2(45 BYTE)
, OLD_MODIFIED_BY VARCHAR2(50 BYTE)  
, OLD_MODIFIED_DATE TIMESTAMP(6)  
, NEW_PARTNER_ID VARCHAR2(8 BYTE)  
, NEW_ACCOUNT_ID VARCHAR2(10 BYTE)  
, NEW_CARDGROUP_MAIN_TYPE VARCHAR2(3 BYTE)  
, NEW_CARDGROUP_SUB_TYPE VARCHAR2(3 BYTE)  
, NEW_CARDGROUP_SEQ VARCHAR2(5 BYTE) 
, NEW_CARDGROUP_DESCRIPTION VARCHAR2(45 BYTE)
, NEW_MODIFIED_BY VARCHAR2(50 BYTE)  
, NEW_MODIFIED_DATE TIMESTAMP(6) 
, U_ID VARCHAR2(50 BYTE) 
, ACTION VARCHAR2(20 BYTE) 
, NEW_TIMESTAMP DATE 

, CONSTRAINT PRT_CARDGROUP_AUDIT_PK PRIMARY KEY 
  (
     AUDIT_ID 
  )
  ENABLE 
) 

PARTITION BY LIST(COUNTRY_CODE) (
    PARTITION PRT_CARDGROUP_AUDIT_SWEDEN VALUES ('SE'),
    PARTITION PRT_CARDGROUP_AUDIT_NORWAY VALUES ('NO'),
    PARTITION PRT_CARDGROUP_AUDIT_DENMARK VALUES ('DK'),
    PARTITION PRT_CARDGROUP_AUDIT_LATVIA VALUES ('LV'),
    PARTITION PRT_CARDGROUP_AUDIT_LITHUANIA VALUES ('LT'),
    PARTITION PRT_CARDGROUP_AUDIT_ESTONIA VALUES ('EE'),
    PARTITION PRT_CARDGROUP_AUDIT_POLAND VALUES ('PL')
);

