
  CREATE TABLE "WCPCUSTOM"."RULEENGINE_CUSTOMER_MASTER" 
   (	"CUSTOMERID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(100 BYTE), 
	"MAILID" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"MOBILENUMBER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CUSTOM1" VARCHAR2(500 BYTE), 
	"CUSTOM2" VARCHAR2(500 BYTE), 
	"CUSTOM3" VARCHAR2(500 BYTE), 
	 CONSTRAINT "RULEENGINE_CUSTOMER_MASTE_PK" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "WCPCUSTOM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WCPCUSTOM" ;
