<wsdl:definitions
     name="LogDeltaReceiptPalsMQEnqueueDequeueV1"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/mq/SOAPalsNotificationApp/SOAPalsNotification/LogDeltaReceiptPalsMQEnqueueDequeueV1"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/mq/SOAPalsNotificationApp/SOAPalsNotification/LogDeltaReceiptPalsMQEnqueueDequeueV1"
     xmlns:msg_in_out="http://statoilfuelretail.com/integration/PALsMQLogDeltaReceipt"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="EnqueueDequeue_plt" >
    <plt:role name="EnqueueDequeue_role" >
      <plt:portType name="tns:EnqueueDequeue_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://statoilfuelretail.com/integration/PALsMQLogDeltaReceipt" schemaLocation="xsd/PALsMQLogDeltaReceipt.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EnqueueDequeue_msg_out">
        <wsdl:part name="PALsMQRequest" element="msg_in_out:PALsMQRequest"/>
    </wsdl:message>
    <wsdl:message name="EnqueueDequeue_msg_in">
        <wsdl:part name="PALsMQResponse" element="msg_in_out:PALsMQResponse"/>
    </wsdl:message>
    <wsdl:portType name="EnqueueDequeue_ptt">
        <wsdl:operation name="EnqueueDequeue">
            <wsdl:input message="tns:EnqueueDequeue_msg_out"/>
            <wsdl:output message="tns:EnqueueDequeue_msg_in"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
