<?binding.jca SelectEngaeSOAErrorStatusDatabaseAdapterV1_db.jca?>
<wsdl:definitions name="SelectEngaeSOAErrorStatusDatabaseAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAPalsNotificationApp/SOAPalsNotification/SelectEngaeSOAErrorStatusDatabaseAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAPalsNotificationApp/SOAPalsNotification/SelectEngaeSOAErrorStatusDatabaseAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectEngaeSOAErrorStatusDatabaseAdapterV1">
    <plt:partnerLinkType name="SelectEngaeSOAErrorStatusDatabaseAdapterV1_plt">
        <plt:role name="SelectEngaeSOAErrorStatusDatabaseAdapterV1_role">
            <plt:portType name="tns:SelectEngaeSOAErrorStatusDatabaseAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelectEngaeSOAErrorStatusDatabaseAdapterV1" schemaLocation="xsd/SelectEngaeSOAErrorStatusDatabaseAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SelectEngaeSOAErrorStatusDatabaseAdapterV1Select_inputParameters">
        <wsdl:part name="SelectEngaeSOAErrorStatusDatabaseAdapterV1Select_inputParameters" element="top:SelectEngaeSOAErrorStatusDatabaseAdapterV1Select_interfaceid_countrycodeInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EngageSoaErrorstatusCollection_msg">
        <wsdl:part name="EngageSoaErrorstatusCollection" element="top:EngageSoaErrorstatusCollection"/>
    </wsdl:message>
    <wsdl:portType name="SelectEngaeSOAErrorStatusDatabaseAdapterV1_ptt">
        <wsdl:operation name="SelectEngaeSOAErrorStatusDatabaseAdapterV1Select">
            <wsdl:input message="tns:SelectEngaeSOAErrorStatusDatabaseAdapterV1Select_inputParameters"/>
            <wsdl:output message="tns:EngageSoaErrorstatusCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
