<?binding.jca SelectValidCardGroupTempDatabaseAdapterV1_db.jca?>
<wsdl:definitions name="SelectValidCardGroupTempDatabaseAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E005CardGroupPALStoPortalApp/E005CardGroupPALStoPortal/SelectValidCardGroupTempDatabaseAdapterV1" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/SelectValidCardGroupTempDatabaseAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E005CardGroupPALStoPortalApp/E005CardGroupPALStoPortal/SelectValidCardGroupTempDatabaseAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="SelectValidCardGroupTempDatabaseAdapterV1_plt">
        <plt:role name="SelectValidCardGroupTempDatabaseAdapterV1_role">
            <plt:portType name="tns:SelectValidCardGroupTempDatabaseAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SelectValidCardGroupTempDatabaseAdapterV1" schemaLocation="xsd/SelectValidCardGroupTempDatabaseAdapterV1.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SelectValidCardGroupTempDatabaseAdapterV1Input_msg">
        <wsdl:part name="SelectValidCardGroupTempDatabaseAdapterV1Input_msg" element="db:SelectValidCardGroupTempDatabaseAdapterV1Input"/>
    </wsdl:message>
    <wsdl:message name="SelectValidCardGroupTempDatabaseAdapterV1OutputCollection_msg">
        <wsdl:part name="SelectValidCardGroupTempDatabaseAdapterV1OutputCollection" element="db:SelectValidCardGroupTempDatabaseAdapterV1OutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="SelectValidCardGroupTempDatabaseAdapterV1_ptt">
        <wsdl:operation name="SelectValidCardGroupTempDatabaseAdapterV1">
            <wsdl:input message="tns:SelectValidCardGroupTempDatabaseAdapterV1Input_msg"/>
            <wsdl:output message="tns:SelectValidCardGroupTempDatabaseAdapterV1OutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
