CREATE TABLE PRT_CARD_REPORT_DETAILS 
(
  COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, REP_DETAIL_ID NUMBER NOT NULL 
, REPORT_ID NUMBER NOT NULL 
, SUBSCR_ID VARCHAR2(20 BYTE) NOT NULL 
, PARTNER_ID VARCHAR2(8 BYTE) 
, ACCOUNT_ID VARCHAR2(10 BYTE) 
, CARDGROUP_MAIN VARCHAR2(3 BYTE) 
, CARDGROUP_SUB VARCHAR2(3 BYTE) 
, CARDGROUP_SEQ VARCHAR2(5 BYTE) 
, CARD VARCHAR2(20 BYTE) 
, VEHICLE_NUMBER VARCHAR2(20 BYTE) 
, VEHICLE_REF_NUMBER VARCHAR2(10 BYTE) 
, DRIVER_NAME VARCHAR2(30 BYTE) 
, DRIVER_CARD_REF VARCHAR2(10 BYTE) 
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
) 

PARTITION BY LIST(COUNTRY_CODE) (
    PARTITION PRT_CARD_REPORT_DT_SWEDEN VALUES ('SE'),
    PARTITION PRT_CARD_REPORT_DT_NORWAY VALUES ('NO'),
    PARTITION PRT_CARD_REPORT_DT_DENMARK VALUES ('DK'),
    PARTITION PRT_CARD_REPORT_DT_LATVIA VALUES ('LV'),
    PARTITION PRT_CARD_REPORT_DT_LITHUANIA VALUES ('LT'),
    PARTITION PRT_CARD_REPORT_DT_ESTONIA VALUES ('EE'),
    PARTITION PRT_CARD_REPORT_DT_POLAND VALUES ('PL')
)

LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);
