CREATE TABLE PRT_LIST_PRICES 
(
  PRT_LIST_PRICE_PK NUMBER NOT NULL 
, PRICE_TYPE VARCHAR2(10 BYTE) NOT NULL 
, ITEM_NUM NUMBER(8, 0) NOT NULL 
, DESC_LINE1 NCHAR(30) 
, EFFECTIVE_DATE DATE NOT NULL 
, END_DATE DATE NOT NULL 
, UNIT_PRICE NUMBER(15, 4) NOT NULL 
, CURRENCY_CODE VARCHAR2(8 BYTE) NOT NULL 
, COUNTRY_CODE VARCHAR2(8 BYTE) NOT NULL 
, UNIT_QTY NUMBER NOT NULL 
, PRICING_UOM VARCHAR2(10 BYTE) NOT NULL 
, MODIFIED_BY VARCHAR2(20 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_LIST_PRICES_PK PRIMARY KEY 
  (
    PRICE_TYPE 
  , ITEM_NUM 
  , CURRENCY_CODE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);
