CREATE TABLE PRT_CARD_FUEL_CAPACITY 
(
  RULE_FUEL_CAP_ID NUMBER NOT NULL 
, COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, SUBSCR_ID NUMBER NOT NULL 
, RULE_ID NUMBER NOT NULL 
, FUEL_PER_DAY FLOAT(126) 
, FUEL_PER_WEEK FLOAT(126) 
, FUEL_PER_MONTH FLOAT(126) 
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_CARD_FUEL_CAPACITY_PK PRIMARY KEY 
  (
    RULE_FUEL_CAP_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE PRT_CARD_FUEL_CAPACITY
ADD CONSTRAINT PRT_CARD_FUEL_CAPACITY_PR_FK1 FOREIGN KEY
(
  SUBSCR_ID 
, COUNTRY_CODE 
)
REFERENCES PRT_CARD_RULE_SUBSCRIPTION
(
  SUBSCR_ID 
, COUNTRY_CODE 
)
ENABLE;
