CREATE TABLE PRT_GEN_KEY_DISPLAY 
(
  PRT_GEN_KEY_DISPLAY_PK NUMBER NOT NULL 
, DISPLAY_KEY VARCHAR2(20 BYTE) NOT NULL 
, DISPLAY_VALUE VARCHAR2(20 BYTE) NOT NULL 
, MODIFIED_BY VARCHAR2(20 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) 
, CONSTRAINT PRT_GEN_KEY_DISPLAY_PK PRIMARY KEY 
  (
    PRT_GEN_KEY_DISPLAY_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);
