<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions
     name="E001PortalBalanceCheckBPEL"
     targetNamespace="http://xmlns.oracle.com/E001SyncPortalBalanceChecktoCGIApp/E001SyncPortalBalanceChecktoCGI/E001PortalBalanceCheckBPEL"
     xmlns:ns2="http://www.statoilfuelretail.com/integration/E001/E001InstanceId"
     xmlns:ns1="http://www.statoilfuelretail.com/integration/E001/E001PortalBalanceCheck"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/E001SyncPortalBalanceChecktoCGIApp/E001SyncPortalBalanceChecktoCGI/E001PortalBalanceCheckBPEL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    >
    <wsdl:documentation>
        <abstractWSDL>http://10.24.240.15:7021/soa-infra/services/WMCard/E001SyncPortalBalanceChecktoCGI!1.0/E001PortalBalanceCheckBPEL.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="E001PortalBalanceCheckBPEL">
        <plnk:role name="E001PortalBalanceCheckBPELProvider">
            <plnk:portType name="client:E001PortalBalanceCheckBPEL"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.statoilfuelretail.com/integration/E001/E001PortalBalanceCheck"
                 schemaLocation="http://10.24.240.15:7021/soa-infra/services/WMCard/E001SyncPortalBalanceChecktoCGI/e001portalbalancecheckbpel_client_ep?XSD=xsd/E001PortalBalanceCheck.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.statoilfuelretail.com/integration/E001/E001InstanceId"
                 schemaLocation="http://10.24.240.15:7021/soa-infra/services/WMCard/E001SyncPortalBalanceChecktoCGI/e001portalbalancecheckbpel_client_ep?XSD=xsd/E001InstanceId.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="E001PortalBalanceCheckBPELRequestMessage">
        <wsdl:part name="payload" element="ns1:requestPayload"/>
    </wsdl:message>
    <wsdl:message name="E001PortalBalanceCheckBPELResponseMessage">
        <wsdl:part name="payload" element="ns1:responsePayload"/>
    </wsdl:message>
    <wsdl:portType name="E001PortalBalanceCheckBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:E001PortalBalanceCheckBPELRequestMessage"/>
            <wsdl:output message="client:E001PortalBalanceCheckBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="E001PortalBalanceCheckBPELBinding" type="client:E001PortalBalanceCheckBPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="e001portalbalancecheckbpel_client_ep">
        <wsdl:port name="E001PortalBalanceCheckBPEL_pt" binding="client:E001PortalBalanceCheckBPELBinding">
            <soap:address location="http://10.24.240.15:7021/soa-infra/services/WMCard/E001SyncPortalBalanceChecktoCGI/e001portalbalancecheckbpel_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="http://10.24.240.15:7021/soa-infra/services/WMCard/E001SyncPortalBalanceChecktoCGI/e001portalbalancecheckbpel_client_ep?XSD=xsd/E001PortalBalanceCheck.xsd" namespace="http://www.statoilfuelretail.com/integration/E001/E001PortalBalanceCheck" ref="E001SyncPortalBalanceChecktoCGIOSB/Resources/XMLSchema_290264560"/>
        <con:schemaRef isInclude="false" schemaLocation="http://10.24.240.15:7021/soa-infra/services/WMCard/E001SyncPortalBalanceChecktoCGI/e001portalbalancecheckbpel_client_ep?XSD=xsd/E001InstanceId.xsd" namespace="http://www.statoilfuelretail.com/integration/E001/E001InstanceId" ref="E001SyncPortalBalanceChecktoCGIOSB/Resources/XMLSchema_-1525092760"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/E001SyncPortalBalanceChecktoCGIApp/E001SyncPortalBalanceChecktoCGI/E001PortalBalanceCheckBPEL</con:targetNamespace>
</con:wsdlEntry>