CREATE OR REPLACE TRIGGER PRT_CARD_RULE_BUSI_HRS_TRIG BEFORE INSERT ON  PRT_CARD_RULE_BUSINESS_HOURS
FOR EACH ROW 
BEGIN
if (:NEW.RULE_BUSI_ID  IS NULL) then
SELECT PRT_CARD_RULE_BUSI_HRS_SEQ.NEXTVAL INTO :NEW.RULE_BUSI_ID FROM DUAL;
end if;
END;
/