CREATE TABLE PRT_CUSTOMER_CARD_MAP 
(
  PRT_CUSTOMER_CARD_MAP_PK NUMBER NOT NULL 
, CUSTOMER_TYPE VARCHAR2(20 BYTE) NOT NULL 
, CARD_TYPE VARCHAR2(20 BYTE) NOT NULL 
, MODIFIED_BY VARCHAR2(20 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_CUSTOMER_CARD_MAP_PK PRIMARY KEY 
  (
    PRT_CUSTOMER_CARD_MAP_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);
