CREATE TRIGGER "TR_PRT_GEN_IMAGE_MAP_SEQ" BEFORE

INSERT
ON PRT_GEN_IMAGE_MAP REFERENCING NEW AS NEW FOR EACH ROW

BEGIN

SELECT SEQ_ID_PRT_GEN_IMAGE_MAP.NEXTVAL INTO :NEW.ID FROM DUAL;

END;
/
