CREATE TABLE PRT_CARD_RULE_BUSINESS_HOURS 
(
  RULE_BUSI_ID NUMBER NOT NULL 
, COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, SUBSCR_ID NUMBER NOT NULL 
, RULE_ID NUMBER NOT NULL 
, BUSI_DAY VARCHAR2(20 BYTE) 
, BUSI_START_FROM VARCHAR2(20 BYTE) 
, BUSI_START_TO VARCHAR2(20 BYTE) 
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_CARD_RULE_BUSINESS_HO_PK PRIMARY KEY 
  (
    RULE_BUSI_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE PRT_CARD_RULE_BUSINESS_HOURS
ADD CONSTRAINT PRT_CARD_RULE_BUSINESS_HO_FK1 FOREIGN KEY
(
  SUBSCR_ID 
, COUNTRY_CODE 
)
REFERENCES PRT_CARD_RULE_SUBSCRIPTION
(
  SUBSCR_ID 
, COUNTRY_CODE 
)
ENABLE;
