ALTER TABLE PRT_PARTNER
  DROP COLUMN PARTNER_TELEPHONE;
  
ALTER TABLE PRT_PARTNER
  DROP COLUMN PARTNER_CREDIT_LIMIT;
  
ALTER TABLE PRT_PARTNER
  ADD PARTNER_ADDR_SEQ varchar2(5);
  
ALTER TABLE PRT_PARTNER
  ADD PARTNER_ADDR_LEVEL varchar2(3);