<?binding.jca MergeWebFuelDBAdapterV1_db.jca?>
<wsdl:definitions name="MergeWebFuelDBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E002JDEE1toWebFuelApp/E002JDEE1toWebFuel/MergeWebFuelDBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E002JDEE1toWebFuelApp/E002JDEE1toWebFuel/MergeWebFuelDBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeWebFuelDBAdapterV1">
    <plt:partnerLinkType name="MergeWebFuelDBAdapterV1_plt">
        <plt:role name="MergeWebFuelDBAdapterV1_role">
            <plt:portType name="tns:MergeWebFuelDBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeWebFuelDBAdapterV1" schemaLocation="xsd/MergeWebFuelDBAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PrtListPricesCollection_msg">
        <wsdl:part name="PrtListPricesCollection" element="top:PrtListPricesCollection"/>
    </wsdl:message>
    <wsdl:portType name="MergeWebFuelDBAdapterV1_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:PrtListPricesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
