package com.sfr.engage.model.queries.uvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 13 10:46:04 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrtNotificationVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PrtNotificationVOImpl() {
    }

    /**
     * Returns the bind variable value for userId.
     * @return bind variable value for userId
     */
    public String getuserId() {
        return (String)getNamedWhereClauseParam("userId");
    }

    /**
     * Sets <code>value</code> for bind variable userId.
     * @param value value to bind as userId
     */
    public void setuserId(String value) {
        setNamedWhereClauseParam("userId", value);
    }

    /**
     * Returns the bind variable value for countryCode.
     * @return bind variable value for countryCode
     */
    public String getcountryCode() {
        return (String)getNamedWhereClauseParam("countryCode");
    }

    /**
     * Sets <code>value</code> for bind variable countryCode.
     * @param value value to bind as countryCode
     */
    public void setcountryCode(String value) {
        setNamedWhereClauseParam("countryCode", value);
    }

    /**
     * Returns the bind variable value for showFlag.
     * @return bind variable value for showFlag
     */
    public String getshowFlag() {
        return (String)getNamedWhereClauseParam("showFlag");
    }

    /**
     * Sets <code>value</code> for bind variable showFlag.
     * @param value value to bind as showFlag
     */
    public void setshowFlag(String value) {
        setNamedWhereClauseParam("showFlag", value);
    }

    /**
     * Returns the bind variable value for categoryValue.
     * @return bind variable value for categoryValue
     */
    public String getcategoryValue() {
        return (String)getNamedWhereClauseParam("categoryValue");
    }

    /**
     * Sets <code>value</code> for bind variable categoryValue.
     * @param value value to bind as categoryValue
     */
    public void setcategoryValue(String value) {
        setNamedWhereClauseParam("categoryValue", value);
    }

    /**
     * Returns the bind variable value for fromDate.
     * @return bind variable value for fromDate
     */
    public String getfromDate() {
        return (String)getNamedWhereClauseParam("fromDate");
    }

    /**
     * Sets <code>value</code> for bind variable fromDate.
     * @param value value to bind as fromDate
     */
    public void setfromDate(String value) {
        setNamedWhereClauseParam("fromDate", value);
    }

    /**
     * Returns the bind variable value for toDate.
     * @return bind variable value for toDate
     */
    public String gettoDate() {
        return (String)getNamedWhereClauseParam("toDate");
    }

    /**
     * Sets <code>value</code> for bind variable toDate.
     * @param value value to bind as toDate
     */
    public void settoDate(String value) {
        setNamedWhereClauseParam("toDate", value);
    }
}
