CREATE TABLE "WCPCUSTOM"."PRT_EXPORT_INFORMATION"
  (
    "S_NO" 					VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "COUNTRY_CODE"          VARCHAR2(2 BYTE),
	"REPORT_PAGE"           VARCHAR2(30 BYTE),
    "REPORT_TYPE"           VARCHAR2(30 BYTE),
    "SELECT_CRITERIA"       VARCHAR2(40 BYTE),
	"TOTAL_COLUMNS"         VARCHAR2(4000 BYTE),
    "PRE_POPULATED_COLUMNS"   VARCHAR2(4000 BYTE),
    "EXTRA_COLUMNS"            VARCHAR2(3000 BYTE),    
    "MODIFIED_BY" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "MODIFIED_DATE" TIMESTAMP (6) NOT NULL ENABLE,
    CONSTRAINT "PRT_EXPORT_INFORMATION" PRIMARY KEY ("S_NO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "WCPCUSTOM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "WCPCUSTOM" PARTITION BY LIST
  (
    "COUNTRY_CODE"
  )
  (
    PARTITION "PRT_EXPORT_INFO_SWEDEN" VALUES
    (
      'SE'
    )
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "WCPCUSTOM" NOCOMPRESS ,
    PARTITION "PRT_EXPORT_INFO_NORWAY" VALUES
    (
      'NO'
    )
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "WCPCUSTOM" NOCOMPRESS ,
    PARTITION "PRT_EXPORT_INFO_DENMARK" VALUES
    (
      'DK'
    )
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "WCPCUSTOM" NOCOMPRESS ,
    PARTITION "PRT_EXPORT_INFO_LATVIA" VALUES
    (
      'LV'
    )
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "WCPCUSTOM" NOCOMPRESS ,
    PARTITION "PRT_EXPORT_INFO_LITHUANIA" VALUES
    (
      'LT'
    )
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "WCPCUSTOM" NOCOMPRESS ,
    PARTITION "PRT_EXPORT_INFO_ESTONIA" VALUES
    (
      'EE'
    )
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "WCPCUSTOM" NOCOMPRESS ,
    PARTITION "PRT_EXPORT_INFO_POLAND" VALUES
    (
      'PL'
    )
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "WCPCUSTOM" NOCOMPRESS
  ) ;
CREATE OR REPLACE TRIGGER "WCPCUSTOM"."PRT_EXPORT_INFORMATION_TRIG" BEFORE
  INSERT ON PRT_EXPORT_INFORMATION FOR EACH ROW BEGIN IF
    (
      :NEW.S_NO IS NULL
    )
    THEN
  SELECT PRT_EXPORT_INFORMATION_SEQ.NEXTVAL
  INTO :NEW.S_NO
  FROM DUAL;
END IF;
END;
/
ALTER TRIGGER "WCPCUSTOM"."PRT_EXPORT_INFORMATION_TRIG" ENABLE;