CREATE TABLE PRT_REPORT_INFORMATION 
(
  S_NO VARCHAR2(20 BYTE) NOT NULL 
, REPORT_PAGE VARCHAR2(30 BYTE) 
, COLUMN_NAME VARCHAR2(200 BYTE) 
, EN VARCHAR2(4000 BYTE) 
, NO_NO VARCHAR2(4000 BYTE) 
, DK VARCHAR2(4000 BYTE) 
, SE VARCHAR2(4000 BYTE) 
, LV VARCHAR2(4000 BYTE) 
, LT VARCHAR2(4000 BYTE) 
, ET VARCHAR2(4000 BYTE) 
, PL VARCHAR2(4000 BYTE) 
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_REPORT_INFORMATION PRIMARY KEY 
  (
    S_NO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

create or replace
TRIGGER "WCPCUSTOM"."PRT_REPORT_INFORMATION_TRIG" BEFORE
  INSERT ON PRT_REPORT_INFORMATION FOR EACH ROW BEGIN IF
    (
      :NEW.S_NO IS NULL
    )
    THEN
  SELECT PRT_REPORT_INFORMATION_SEQ.NEXTVAL
  INTO :NEW.S_NO
  FROM DUAL;
END IF;
END;
/
ALTER TRIGGER "WCPCUSTOM"."PRT_REPORT_INFORMATION_TRIG" ENABLE;
