package com.sfr.engage.model.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 24 13:52:23 IST 2014
// ---------------------------------------------------------------------
public interface EngageAppModule extends ApplicationModule {
    void deleteAllForAccount(String accountId, String type, String countryCd,
                             String regDriverValue);

    String getWebServiceErrorMessage(String errorMessage, String countryCode);

    void updateOdometerPortal(String urefTransactionId, String palsCountryCode,
                              String odoMeterPortalValue);
}
