CREATE TRIGGER PRT_DRIVER_INFORMATION_TRIG BEFORE INSERT ON PRT_DRIVER_INFORMATION
FOR EACH ROW 
BEGIN

if (:NEW.PRT_DRIVER_INFORMATION_PK IS NULL) then
SELECT PRT_DRIVER_INFORMATION_SEQ.NEXTVAL INTO :NEW.PRT_DRIVER_INFORMATION_PK FROM DUAL;
end if;
END;
/
