<?binding.jca MergeInvoiceErrorLogDatabaseAdapterV1_db.jca?>
<wsdl:definitions name="MergeInvoiceErrorLogDatabaseAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E009PALSInvoicetoPortalApp/E009PALSInvoicetoPortal/MergeInvoiceErrorLogDatabaseAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E009PALSInvoicetoPortalApp/E009PALSInvoicetoPortal/MergeInvoiceErrorLogDatabaseAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeInvoiceErrorLogDatabaseAdapterV1">
    <plt:partnerLinkType name="MergeInvoiceErrorLogDatabaseAdapterV1_plt">
        <plt:role name="MergeInvoiceErrorLogDatabaseAdapterV1_role">
            <plt:portType name="tns:MergeInvoiceErrorLogDatabaseAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeInvoiceErrorLogDatabaseAdapterV1" schemaLocation="xsd/MergeInvoiceErrorLogDatabaseAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EngageSoaInvoiceErrorlogCollection_msg">
        <wsdl:part name="EngageSoaInvoiceErrorlogCollection" element="top:EngageSoaInvoiceErrorlogCollection"/>
    </wsdl:message>
    <wsdl:portType name="MergeInvoiceErrorLogDatabaseAdapterV1_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:EngageSoaInvoiceErrorlogCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
