<?binding.jca MergeDeltaTSDatabaseAdapterV1_db.jca?>
<wsdl:definitions name="MergeDeltaTSDatabaseAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E009PALSInvoicetoPortalApp/E009PALSInvoicetoPortal/MergeDeltaTSDatabaseAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E009PALSInvoicetoPortalApp/E009PALSInvoicetoPortal/MergeDeltaTSDatabaseAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeDeltaTSDatabaseAdapterV1">
    <plt:partnerLinkType name="MergeDeltaTSDatabaseAdapterV1_plt">
        <plt:role name="MergeDeltaTSDatabaseAdapterV1_role">
            <plt:portType name="tns:MergeDeltaTSDatabaseAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeDeltaTSDatabaseAdapterV1" schemaLocation="xsd/MergeDeltaTSDatabaseAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EngageSoaDeltatableCollection_msg">
        <wsdl:part name="EngageSoaDeltatableCollection" element="top:EngageSoaDeltatableCollection"/>
    </wsdl:message>
    <wsdl:portType name="MergeDeltaTSDatabaseAdapterV1_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:EngageSoaDeltatableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
