CREATE TABLE PRT_CARD_TRANSACTION_DETAIL 
(
  PALS_COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, UREF_TRANSACTION_ID VARCHAR2(10 BYTE) NOT NULL 
, DETAIL_NO VARCHAR2(5 BYTE) NOT NULL 
, PALS_P_GROUP_ID VARCHAR2(5 BYTE) 
, PALS_P_GROUP_SUBGROUP_ID VARCHAR2(2 BYTE) 
, PRODUCT_NAME VARCHAR2(60 BYTE) 
, QUANTITY FLOAT(126) 
, VAT_RATE FLOAT(126) 
, INV_NET_UNIT_PRICE_REBATED FLOAT(126) 
, INVOICED_UNIT_PRICE_REBATED FLOAT(126) 
, INVOICED_NET_AMOUNT_REBATED FLOAT(126) 
, INVOICED_GROSS_AMOUNT_REBATED FLOAT(126) 
, INVOIVED_VAT_REBATED FLOAT(126) 
, CURRENCY_UNIT_PRICE FLOAT(126) 
, CURRENCY_GROSS_AMOUNT FLOAT(126) 
, UNIT_OF_MEASURE VARCHAR2(3 BYTE) 
, ORDER_ID VARCHAR2(10 BYTE) 
, PRELIM_ID VARCHAR2(10 BYTE) 
, ORDER_LINE_NUMBER VARCHAR2(5 BYTE) 
, PRICE_ELEMENT_CODE VARCHAR2(3 BYTE) 
, PRICE_ELEMENT_RATE FLOAT(126) 
, ORDER_LINE_REF VARCHAR2(5 BYTE) 
, FUEL_TRANS_FLAG VARCHAR2(1 BYTE) 
, PALS_MODIFIED_DATE DATE NOT NULL 
, PALS_MODIFIED_BY VARCHAR2(6 BYTE) 
, MODIFIED_BY VARCHAR2(50 BYTE) 
, PORTAL_MODIFIED_DATE DATE 
, CURRENCY_VAT FLOAT(126) 
, CURRENCY_DISCOUNT_AMOUNT FLOAT(126) 
, CURRENCY_VAT_REBATED FLOAT(126) 
, CURRENCY_UNIT_PRICE_REBATED FLOAT(126) 
, CURRENCY_GROSS_AMOUNT_REBATED FLOAT(126) 
, CURRENCY_NET_AMOUNT FLOAT(126) 
, CURRENCY_NET_AMOUNT_REBATED FLOAT(126) 
, INVOICED_VAT FLOAT(126) 
, INVOICED_UNIT_PRICE FLOAT(126) 
, INVOICED_GROSS_AMOUNT FLOAT(126) 
, INVOICED_NET_AMOUNT FLOAT(126) 
, INVOICE_DISCOUNT_AMOUNT FLOAT(126) 
, FUEL_YN VARCHAR2(1 BYTE) 
, VAT_REFUNDABLE_YN VARCHAR2(1 BYTE) 
, SOA_MODIFIED_DATE TIMESTAMP(8) NOT NULL 
, SOA_MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, CONSTRAINT PRT_CARD_TRANSACTION_DETA_PK PRIMARY KEY 
  (
    UREF_TRANSACTION_ID 
  , PALS_COUNTRY_CODE 
  , DETAIL_NO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 2 
  NEXT 1 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
PARTITION BY LIST (PALS_COUNTRY_CODE) 
(
  PARTITION PRT_CARD_TRANSACTION_DETAIL_SE VALUES ('SE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_TRANSACTION_DETAIL_NO VALUES ('NO') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_TRANSACTION_DETAIL_DK VALUES ('DK') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_TRANSACTION_DETAIL_LV VALUES ('LV') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_TRANSACTION_DETAIL_LT VALUES ('LT') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_TRANSACTION_DETAIL_EE VALUES ('EE') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION PRT_CARD_TRANSACTION_DETAIL_PL VALUES ('PL') 
  LOGGING 
  TABLESPACE "WCPCUSTOM" 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
);

ALTER TABLE PRT_CARD_TRANSACTION_DETAIL
ADD CONSTRAINT PRT_CARD_TRANSACTION_DETA_FK1 FOREIGN KEY
(
  UREF_TRANSACTION_ID 
, PALS_COUNTRY_CODE 
)
REFERENCES PRT_CARD_TRANSACTION_HEADER
(
  UREF_TRANSACTION_ID 
, PALS_COUNTRY_CODE 
)
ON DELETE CASCADE ENABLE;
