CREATE TABLE PRT_CARD 
(
  COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, PARTNER_ID VARCHAR2(8 BYTE) NOT NULL 
, ACCOUNT_ID VARCHAR2(10 BYTE) NOT NULL
, CARDGROUP_MAIN_TYPE VARCHAR2(3 BYTE) NOT NULL 
, CARDGROUP_SUB_TYPE VARCHAR2(3 BYTE) NOT NULL 
, CARDGROUP_SEQ VARCHAR2(5 BYTE) NOT NULL 
, PRT_CARD_PK VARCHAR2(10 BYTE) NOT NULL 
, CARD_IDENTIFIER VARCHAR2(3 BYTE)
, CARD_TYPE VARCHAR2(3 BYTE) NOT NULL
, MAGNETIC_CODE VARCHAR2(20 BYTE) 
, CARD_EMBOSS_NUM VARCHAR2(20 BYTE) NOT NULL
, INVOICE_INFORMATION VARCHAR2(90 BYTE)
, CARD_EXPIRY DATE 
, BLOCK_TYPE VARCHAR2(3 BYTE) 
, BLOCK_CODE VARCHAR2(3 BYTE) 
, BLOCK_ACTION VARCHAR2(1 BYTE)
, BLOCK_DATE DATE 
, BLOCK_TIME TIMESTAMP(6) 
, BLOCK_LEVEL VARCHAR2(3 BYTE)
, MANUFACTURED_DATE DATE 
, ROUTEX_CUSTOMER_NUMBER VARCHAR2(6 BYTE)
, INVOICE_ADDR1 VARCHAR2(60 BYTE)
, INVOICE_ADDR2  VARCHAR2(60 BYTE)
, INVOICE_POSTAL_CODE VARCHAR2(10 BYTE)
, INVOICE_CITY VARCHAR2(60 BYTE)
, ADDR_SEQ VARCHAR2(5 BYTE)
, INVOICE_COUNTRY VARCHAR2(2 BYTE)
, INVOICE_ADDR_LEVEL VARCHAR2(3 BYTE)
, INVOICE_ADDR_TYPE VARCHAR2(3 BYTE)
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL
, MODIFIED_DATE TIMESTAMP(6) NOT NULL

, CREATED_DATE DATE 
, CREATED_BY VARCHAR2(6 BYTE) 
, CHANGE_DATE DATE 
, CHANGE_BY VARCHAR2(6 BYTE) 
, VERSION_NUMBER NUMBER(*, 0) 
, CUSTOMER_GROUP VARCHAR2(2 BYTE) 
, PREV_CARD_ID VARCHAR2(10 BYTE) 
, PHYSICAL_CARD_ID VARCHAR2(10 BYTE) 
, CARD_ISSUE_DATE DATE 
, CARD_RETURN_DATE DATE 
, PURCHASE_PROFILE_CODE VARCHAR2(3 BYTE) 
, NUM_PRINTLINES NUMBER(*, 0) 
, CARD_APP_ID VARCHAR2(7 BYTE) 
, GEO_USE_REF VARCHAR2(10 BYTE) 
, CARD_STATUS_CODE VARCHAR2(3 BYTE) 
, EXT_CARD_NUM VARCHAR2(20 BYTE) 
, CARD_RENEW_DATE DATE 
, CARD_RENEW_BLOCK VARCHAR2(1 BYTE) 
, PIN_OFFSET NUMBER(4, 0) 
, CARD_DESIGN_CODE VARCHAR2(6 BYTE) 
, CARD_CREATED_BY VARCHAR2(6 BYTE) 
, CARD_COPIES NUMBER(*, 0) 
, CARD_SEARCH_ID VARCHAR2(20 BYTE) 
, DEBIT_BANK_ACCOUNT VARCHAR2(16 BYTE) 
, DEBIT_AGREE_REF VARCHAR2(15 BYTE) 
, DELETION_CODE VARCHAR2(3 BYTE) 
, SPERREBEH_KD VARCHAR2(3 BYTE) 
, SPERRELISTE_DT DATE 
, SPESIALBEST_JN VARCHAR2(1 BYTE) 
, CONSTRAINT PRT_CARD_PK PRIMARY KEY 
  (
    COUNTRY_CODE 
  , PRT_CARD_PK 
  )
  ENABLE 
) 

PARTITION BY LIST(COUNTRY_CODE) (
    PARTITION PRT_CARD_SWEDEN VALUES ('SE'),
    PARTITION PRT_CARD_NORWAY VALUES ('NO'),
    PARTITION PRT_CARD_DENMARK VALUES ('DK'),
    PARTITION PRT_CARD_LATVIA VALUES ('LV'),
    PARTITION PRT_CARD_LITHUANIA VALUES ('LT'),
    PARTITION PRT_CARD_ESTONIA VALUES ('EE'),
    PARTITION PRT_CARD_POLAND VALUES ('PL')
)

LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE PRT_CARD
ADD CONSTRAINT PRT_CARD_PRT_ACCOUNT_FK1 FOREIGN KEY
(
  COUNTRY_CODE 
, ACCOUNT_ID 
)
REFERENCES PRT_ACCOUNT
(
  COUNTRY_CODE 
, ACCOUNT_ID 
)
ENABLE;

ALTER TABLE PRT_CARD
ADD CONSTRAINT PRT_CARD_PRT_CARDGROUP_FK1 FOREIGN KEY
(
  PARTNER_ID 
, CARDGROUP_MAIN_TYPE 
, CARDGROUP_SUB_TYPE 
, CARDGROUP_SEQ 
, COUNTRY_CODE 
)
REFERENCES PRT_CARDGROUP
(
  PARTNER_ID 
, CARDGROUP_MAIN_TYPE 
, CARDGROUP_SUB_TYPE 
, CARDGROUP_SEQ 
, COUNTRY_CODE 
)
ENABLE;

ALTER TABLE PRT_CARD
ADD CONSTRAINT PRT_CARD_PRT_PARTNER_FK1 FOREIGN KEY
(
  COUNTRY_CODE 
, PARTNER_ID 
)
REFERENCES PRT_PARTNER
(
  COUNTRY_CODE 
, PARTNER_ID 
)
ENABLE;
