<?binding.jca SelectRecordCountPALSDBAdapterV1_db.jca?>
<wsdl:definitions name="SelectRecordCountPALSDBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E010PALSInvoicePaymentDoctoPortalApp/E010PALSInvoicePaymentDoctoPortal/SelectRecordCountPALSDBAdapterV1" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/SelectRecordCountPALSDBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E010PALSInvoicePaymentDoctoPortalApp/E010PALSInvoicePaymentDoctoPortal/SelectRecordCountPALSDBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="SelectRecordCountPALSDBAdapterV1_plt">
        <plt:role name="SelectRecordCountPALSDBAdapterV1_role">
            <plt:portType name="tns:SelectRecordCountPALSDBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SelectRecordCountPALSDBAdapterV1" schemaLocation="xsd/SelectRecordCountPALSDBAdapterV1.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SelectRecordCountPALSDBAdapterV1Input_msg">
        <wsdl:part name="SelectRecordCountPALSDBAdapterV1Input_msg" element="db:SelectRecordCountPALSDBAdapterV1Input"/>
    </wsdl:message>
    <wsdl:message name="SelectRecordCountPALSDBAdapterV1Output_msg">
        <wsdl:part name="SelectRecordCountPALSDBAdapterV1Output" element="db:SelectRecordCountPALSDBAdapterV1Output"/>
    </wsdl:message>
    <wsdl:portType name="SelectRecordCountPALSDBAdapterV1_ptt">
        <wsdl:operation name="SelectRecordCountPALSDBAdapterV1">
            <wsdl:input message="tns:SelectRecordCountPALSDBAdapterV1Input_msg"/>
            <wsdl:output message="tns:SelectRecordCountPALSDBAdapterV1Output_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
