<?binding.jca UpdateEmailFlagSOAErrorLogDBAdapterV1_db.jca?>
<wsdl:definitions name="UpdateEmailFlagSOAErrorLogDBAdapterV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/E010PALSInvoicePaymentDoctoPortalApp/E010PALSInvoicePaymentDoctoPortal/UpdateEmailFlagSOAErrorLogDBAdapterV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/E010PALSInvoicePaymentDoctoPortalApp/E010PALSInvoicePaymentDoctoPortal/UpdateEmailFlagSOAErrorLogDBAdapterV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateEmailFlagSOAErrorLogDBAdapterV1">
    <plt:partnerLinkType name="UpdateEmailFlagSOAErrorLogDBAdapterV1_plt">
        <plt:role name="UpdateEmailFlagSOAErrorLogDBAdapterV1_role">
            <plt:portType name="tns:UpdateEmailFlagSOAErrorLogDBAdapterV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateEmailFlagSOAErrorLogDBAdapterV1" schemaLocation="xsd/UpdateEmailFlagSOAErrorLogDBAdapterV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EngageSoaInvPmtErrorlogCollection_msg">
        <wsdl:part name="EngageSoaInvPmtErrorlogCollection" element="top:EngageSoaInvPmtErrorlogCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateEmailFlagSOAErrorLogDBAdapterV1_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:EngageSoaInvPmtErrorlogCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
