<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.logica.no/card/sms/soap"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://www.logica.no/card/sms/soap"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="InvokeCGIWebServiceV1">
        <plnk:role name="sms">
            <plnk:portType name="tns:sms"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.logica.no/card/sms/soap" location="sms.wsdl"/>
</wsdl:definitions>
