TRIGGER PAR_DTA_ERRORLOG_TRG 
BEFORE INSERT OR UPDATE ON ENGAGE_PALS_PAR_DTA_ERRORLOG 
FOR EACH ROW 
BEGIN
:new.UPDATED_TIMESTAMP := CURRENT_TIMESTAMP;
:new.UPDATED_BY := SYS_CONTEXT('USERENV','OS_USER');
END;