package com.sfr.engage.model.queries.rvo;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 07 15:33:10 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrtCardTransactionInvoiceRVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ProductName {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getProductName();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setProductName((String)value);
            }
        }
        ,
        Quantity {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        StationName {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getStationName();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setStationName((String)value);
            }
        }
        ,
        InvoiceNumberNonCollective {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoiceNumberNonCollective();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoiceNumberNonCollective((String)value);
            }
        }
        ,
        InvoiceNumberCollective {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoiceNumberCollective();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoiceNumberCollective((String)value);
            }
        }
        ,
        PalsCountryCode {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getPalsCountryCode();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setPalsCountryCode((String)value);
            }
        }
        ,
        Card1Id {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCard1Id();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCard1Id((String)value);
            }
        }
        ,
        InvoicedGrossAmount {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoicedGrossAmount();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoicedGrossAmount((Number)value);
            }
        }
        ,
        InvoicedNetAmount {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoicedNetAmount();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoicedNetAmount((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PrtCardTransactionInvoiceRVORowImpl object);

        public abstract void put(PrtCardTransactionInvoiceRVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PRODUCTNAME = AttributesEnum.ProductName.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int STATIONNAME = AttributesEnum.StationName.index();
    public static final int INVOICENUMBERNONCOLLECTIVE = AttributesEnum.InvoiceNumberNonCollective.index();
    public static final int INVOICENUMBERCOLLECTIVE = AttributesEnum.InvoiceNumberCollective.index();
    public static final int PALSCOUNTRYCODE = AttributesEnum.PalsCountryCode.index();
    public static final int CARD1ID = AttributesEnum.Card1Id.index();
    public static final int INVOICEDGROSSAMOUNT = AttributesEnum.InvoicedGrossAmount.index();
    public static final int INVOICEDNETAMOUNT = AttributesEnum.InvoicedNetAmount.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrtCardTransactionInvoiceRVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ProductName.
     * @return the ProductName
     */
    public String getProductName() {
        return (String) getAttributeInternal(PRODUCTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductName.
     * @param value value to set the  ProductName
     */
    public void setProductName(String value) {
        setAttributeInternal(PRODUCTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Quantity.
     * @return the Quantity
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Quantity.
     * @param value value to set the  Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StationName.
     * @return the StationName
     */
    public String getStationName() {
        return (String) getAttributeInternal(STATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StationName.
     * @param value value to set the  StationName
     */
    public void setStationName(String value) {
        setAttributeInternal(STATIONNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceNumberCollective.
     * @return the InvoiceNumberCollective
     */
    public String getInvoiceNumberCollective() {
        return (String) getAttributeInternal(INVOICENUMBERCOLLECTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceNumberCollective.
     * @param value value to set the  InvoiceNumberCollective
     */
    public void setInvoiceNumberCollective(String value) {
        setAttributeInternal(INVOICENUMBERCOLLECTIVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PalsCountryCode.
     * @return the PalsCountryCode
     */
    public String getPalsCountryCode() {
        return (String) getAttributeInternal(PALSCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PalsCountryCode.
     * @param value value to set the  PalsCountryCode
     */
    public void setPalsCountryCode(String value) {
        setAttributeInternal(PALSCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceNumberNonCollective.
     * @return the InvoiceNumberNonCollective
     */
    public String getInvoiceNumberNonCollective() {
        return (String) getAttributeInternal(INVOICENUMBERNONCOLLECTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceNumberNonCollective.
     * @param value value to set the  InvoiceNumberNonCollective
     */
    public void setInvoiceNumberNonCollective(String value) {
        setAttributeInternal(INVOICENUMBERNONCOLLECTIVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Card1Id.
     * @return the Card1Id
     */
    public String getCard1Id() {
        return (String) getAttributeInternal(CARD1ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Card1Id.
     * @param value value to set the  Card1Id
     */
    public void setCard1Id(String value) {
        setAttributeInternal(CARD1ID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoicedGrossAmount.
     * @return the InvoicedGrossAmount
     */
    public Number getInvoicedGrossAmount() {
        return (Number) getAttributeInternal(INVOICEDGROSSAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoicedGrossAmount.
     * @param value value to set the  InvoicedGrossAmount
     */
    public void setInvoicedGrossAmount(Number value) {
        setAttributeInternal(INVOICEDGROSSAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoicedNetAmount.
     * @return the InvoicedNetAmount
     */
    public Number getInvoicedNetAmount() {
        return (Number) getAttributeInternal(INVOICEDNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoicedNetAmount.
     * @param value value to set the  InvoicedNetAmount
     */
    public void setInvoicedNetAmount(Number value) {
        setAttributeInternal(INVOICEDNETAMOUNT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
