package com.sfr.engage.model.queries.rvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 22 15:38:10 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrtCardUserInformationValidationRVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PrtCardUserInformationValidationRVOImpl() {
    }

    /**
     * Returns the bind variable value for userEmail.
     * @return bind variable value for userEmail
     */
    public String getuserEmail() {
        return (String)getNamedWhereClauseParam("userEmail");
    }

    /**
     * Sets <code>value</code> for bind variable userEmail.
     * @param value value to bind as userEmail
     */
    public void setuserEmail(String value) {
        setNamedWhereClauseParam("userEmail", value);
    }
}
