package com.sfr.engage.model.queries.rvo;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 18 16:28:56 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrtCardTransactionInvoiceRVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DeltaTimestamp {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getDeltaTimestamp();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setDeltaTimestamp((Timestamp)value);
            }
        }
        ,
        LastUpdated {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getLastUpdated();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setLastUpdated((Date)value);
            }
        }
        ,
        UrefTransactionId {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getUrefTransactionId();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setUrefTransactionId((String)value);
            }
        }
        ,
        PalsCountryCode {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getPalsCountryCode();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setPalsCountryCode((String)value);
            }
        }
        ,
        PurchaseCountryCode {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getPurchaseCountryCode();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setPurchaseCountryCode((String)value);
            }
        }
        ,
        OrderId {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getOrderId();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setOrderId((String)value);
            }
        }
        ,
        PrelimId {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getPrelimId();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setPrelimId((String)value);
            }
        }
        ,
        Card1Id {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCard1Id();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCard1Id((String)value);
            }
        }
        ,
        Card2Id {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCard2Id();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCard2Id((String)value);
            }
        }
        ,
        CardId2Info {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCardId2Info();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCardId2Info((String)value);
            }
        }
        ,
        OdometerPortal {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getOdometerPortal();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setOdometerPortal((String)value);
            }
        }
        ,
        Odometer {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getOdometer();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setOdometer((String)value);
            }
        }
        ,
        TransactionDt {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getTransactionDt();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setTransactionDt((Date)value);
            }
        }
        ,
        TransactionTime {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getTransactionTime();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setTransactionTime((Timestamp)value);
            }
        }
        ,
        StationName {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getStationName();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setStationName((String)value);
            }
        }
        ,
        StationGroupId {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getStationGroupId();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setStationGroupId((String)value);
            }
        }
        ,
        StationGroupName {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getStationGroupName();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setStationGroupName((String)value);
            }
        }
        ,
        IccInvoiceNumber {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getIccInvoiceNumber();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setIccInvoiceNumber((String)value);
            }
        }
        ,
        InvoiceNumberNonCollective {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoiceNumberNonCollective();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoiceNumberNonCollective((String)value);
            }
        }
        ,
        InvoicingDate {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoicingDate();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoicingDate((Date)value);
            }
        }
        ,
        RecieptNo {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getRecieptNo();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setRecieptNo((String)value);
            }
        }
        ,
        PurchaseCurrency {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getPurchaseCurrency();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setPurchaseCurrency((String)value);
            }
        }
        ,
        ExchangeRate {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getExchangeRate();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setExchangeRate((Number)value);
            }
        }
        ,
        IccYn {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getIccYn();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setIccYn((String)value);
            }
        }
        ,
        TransactionType {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getTransactionType();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setTransactionType((String)value);
            }
        }
        ,
        PrelimStatusCode {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getPrelimStatusCode();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setPrelimStatusCode((String)value);
            }
        }
        ,
        InvoiceNumberCollective {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoiceNumberCollective();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoiceNumberCollective((String)value);
            }
        }
        ,
        Ksid {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getKsid();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setKsid((String)value);
            }
        }
        ,
        PartnerId {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getPartnerId();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setPartnerId((String)value);
            }
        }
        ,
        AccountId {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getAccountId();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setAccountId((String)value);
            }
        }
        ,
        CardgroupMainType {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCardgroupMainType();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCardgroupMainType((String)value);
            }
        }
        ,
        CardgroupSubType {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCardgroupSubType();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCardgroupSubType((String)value);
            }
        }
        ,
        CardgroupSeq {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCardgroupSeq();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCardgroupSeq((String)value);
            }
        }
        ,
        Terminal {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getTerminal();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setTerminal((String)value);
            }
        }
        ,
        DeltaTimestamp1 {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getDeltaTimestamp1();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setDeltaTimestamp1((Timestamp)value);
            }
        }
        ,
        UrefTransactionId1 {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getUrefTransactionId1();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setUrefTransactionId1((String)value);
            }
        }
        ,
        PalsCountryCode1 {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getPalsCountryCode1();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setPalsCountryCode1((String)value);
            }
        }
        ,
        DetailNo {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getDetailNo();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setDetailNo((String)value);
            }
        }
        ,
        PalsPGroupId {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getPalsPGroupId();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setPalsPGroupId((String)value);
            }
        }
        ,
        PalsPGroupSubgroupId {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getPalsPGroupSubgroupId();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setPalsPGroupSubgroupId((String)value);
            }
        }
        ,
        FuelYn {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getFuelYn();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setFuelYn((String)value);
            }
        }
        ,
        ProductName {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getProductName();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setProductName((String)value);
            }
        }
        ,
        Quantity {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        VatRate {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getVatRate();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setVatRate((Number)value);
            }
        }
        ,
        CurrencyVat {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCurrencyVat();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCurrencyVat((Number)value);
            }
        }
        ,
        InvoicedVat {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoicedVat();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoicedVat((Number)value);
            }
        }
        ,
        CurrencyUnitPrice {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCurrencyUnitPrice();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCurrencyUnitPrice((Number)value);
            }
        }
        ,
        InvoicedUnitPrice {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoicedUnitPrice();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoicedUnitPrice((Number)value);
            }
        }
        ,
        CurrencyGrossAmount {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCurrencyGrossAmount();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCurrencyGrossAmount((Number)value);
            }
        }
        ,
        InvoicedGrossAmount {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoicedGrossAmount();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoicedGrossAmount((Number)value);
            }
        }
        ,
        CurrencyNetAmount {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCurrencyNetAmount();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCurrencyNetAmount((Number)value);
            }
        }
        ,
        InvoicedNetAmount {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoicedNetAmount();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoicedNetAmount((Number)value);
            }
        }
        ,
        CurrencyDiscountAmount {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCurrencyDiscountAmount();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCurrencyDiscountAmount((Number)value);
            }
        }
        ,
        InvoiceDiscountAmount {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoiceDiscountAmount();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoiceDiscountAmount((Number)value);
            }
        }
        ,
        VatRefundableYn {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getVatRefundableYn();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setVatRefundableYn((String)value);
            }
        }
        ,
        SurchargeYn {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getSurchargeYn();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setSurchargeYn((String)value);
            }
        }
        ,
        AtIabf538aPrpslKd {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getAtIabf538aPrpslKd();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setAtIabf538aPrpslKd((String)value);
            }
        }
        ,
        AsIabf538aPrpslsats {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getAsIabf538aPrpslsats();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setAsIabf538aPrpslsats((Number)value);
            }
        }
        ,
        CurrencyVatRebated {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCurrencyVatRebated();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCurrencyVatRebated((Number)value);
            }
        }
        ,
        InvoivedVatRebated {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoivedVatRebated();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoivedVatRebated((Number)value);
            }
        }
        ,
        CurrencyUnitPriceRebated {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCurrencyUnitPriceRebated();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCurrencyUnitPriceRebated((Number)value);
            }
        }
        ,
        InvoicedUnitPriceRebated {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoicedUnitPriceRebated();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoicedUnitPriceRebated((Number)value);
            }
        }
        ,
        CurrencyGrossAmountRebated {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCurrencyGrossAmountRebated();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCurrencyGrossAmountRebated((Number)value);
            }
        }
        ,
        InvoicedGrossAmountRebated {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoicedGrossAmountRebated();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoicedGrossAmountRebated((Number)value);
            }
        }
        ,
        CurrencyNetAmountRebated {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getCurrencyNetAmountRebated();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setCurrencyNetAmountRebated((Number)value);
            }
        }
        ,
        InvoicedNetAmountRabeted {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getInvoicedNetAmountRabeted();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setInvoicedNetAmountRabeted((Number)value);
            }
        }
        ,
        UnitOfMeasure {
            public Object get(PrtCardTransactionInvoiceRVORowImpl obj) {
                return obj.getUnitOfMeasure();
            }

            public void put(PrtCardTransactionInvoiceRVORowImpl obj,
                            Object value) {
                obj.setUnitOfMeasure((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PrtCardTransactionInvoiceRVORowImpl object);

        public abstract void put(PrtCardTransactionInvoiceRVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DELTATIMESTAMP = AttributesEnum.DeltaTimestamp.index();
    public static final int LASTUPDATED = AttributesEnum.LastUpdated.index();
    public static final int UREFTRANSACTIONID = AttributesEnum.UrefTransactionId.index();
    public static final int PALSCOUNTRYCODE = AttributesEnum.PalsCountryCode.index();
    public static final int PURCHASECOUNTRYCODE = AttributesEnum.PurchaseCountryCode.index();
    public static final int ORDERID = AttributesEnum.OrderId.index();
    public static final int PRELIMID = AttributesEnum.PrelimId.index();
    public static final int CARD1ID = AttributesEnum.Card1Id.index();
    public static final int CARD2ID = AttributesEnum.Card2Id.index();
    public static final int CARDID2INFO = AttributesEnum.CardId2Info.index();
    public static final int ODOMETERPORTAL = AttributesEnum.OdometerPortal.index();
    public static final int ODOMETER = AttributesEnum.Odometer.index();
    public static final int TRANSACTIONDT = AttributesEnum.TransactionDt.index();
    public static final int TRANSACTIONTIME = AttributesEnum.TransactionTime.index();
    public static final int STATIONNAME = AttributesEnum.StationName.index();
    public static final int STATIONGROUPID = AttributesEnum.StationGroupId.index();
    public static final int STATIONGROUPNAME = AttributesEnum.StationGroupName.index();
    public static final int ICCINVOICENUMBER = AttributesEnum.IccInvoiceNumber.index();
    public static final int INVOICENUMBERNONCOLLECTIVE = AttributesEnum.InvoiceNumberNonCollective.index();
    public static final int INVOICINGDATE = AttributesEnum.InvoicingDate.index();
    public static final int RECIEPTNO = AttributesEnum.RecieptNo.index();
    public static final int PURCHASECURRENCY = AttributesEnum.PurchaseCurrency.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int ICCYN = AttributesEnum.IccYn.index();
    public static final int TRANSACTIONTYPE = AttributesEnum.TransactionType.index();
    public static final int PRELIMSTATUSCODE = AttributesEnum.PrelimStatusCode.index();
    public static final int INVOICENUMBERCOLLECTIVE = AttributesEnum.InvoiceNumberCollective.index();
    public static final int KSID = AttributesEnum.Ksid.index();
    public static final int PARTNERID = AttributesEnum.PartnerId.index();
    public static final int ACCOUNTID = AttributesEnum.AccountId.index();
    public static final int CARDGROUPMAINTYPE = AttributesEnum.CardgroupMainType.index();
    public static final int CARDGROUPSUBTYPE = AttributesEnum.CardgroupSubType.index();
    public static final int CARDGROUPSEQ = AttributesEnum.CardgroupSeq.index();
    public static final int TERMINAL = AttributesEnum.Terminal.index();
    public static final int DELTATIMESTAMP1 = AttributesEnum.DeltaTimestamp1.index();
    public static final int UREFTRANSACTIONID1 = AttributesEnum.UrefTransactionId1.index();
    public static final int PALSCOUNTRYCODE1 = AttributesEnum.PalsCountryCode1.index();
    public static final int DETAILNO = AttributesEnum.DetailNo.index();
    public static final int PALSPGROUPID = AttributesEnum.PalsPGroupId.index();
    public static final int PALSPGROUPSUBGROUPID = AttributesEnum.PalsPGroupSubgroupId.index();
    public static final int FUELYN = AttributesEnum.FuelYn.index();
    public static final int PRODUCTNAME = AttributesEnum.ProductName.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int VATRATE = AttributesEnum.VatRate.index();
    public static final int CURRENCYVAT = AttributesEnum.CurrencyVat.index();
    public static final int INVOICEDVAT = AttributesEnum.InvoicedVat.index();
    public static final int CURRENCYUNITPRICE = AttributesEnum.CurrencyUnitPrice.index();
    public static final int INVOICEDUNITPRICE = AttributesEnum.InvoicedUnitPrice.index();
    public static final int CURRENCYGROSSAMOUNT = AttributesEnum.CurrencyGrossAmount.index();
    public static final int INVOICEDGROSSAMOUNT = AttributesEnum.InvoicedGrossAmount.index();
    public static final int CURRENCYNETAMOUNT = AttributesEnum.CurrencyNetAmount.index();
    public static final int INVOICEDNETAMOUNT = AttributesEnum.InvoicedNetAmount.index();
    public static final int CURRENCYDISCOUNTAMOUNT = AttributesEnum.CurrencyDiscountAmount.index();
    public static final int INVOICEDISCOUNTAMOUNT = AttributesEnum.InvoiceDiscountAmount.index();
    public static final int VATREFUNDABLEYN = AttributesEnum.VatRefundableYn.index();
    public static final int SURCHARGEYN = AttributesEnum.SurchargeYn.index();
    public static final int ATIABF538APRPSLKD = AttributesEnum.AtIabf538aPrpslKd.index();
    public static final int ASIABF538APRPSLSATS = AttributesEnum.AsIabf538aPrpslsats.index();
    public static final int CURRENCYVATREBATED = AttributesEnum.CurrencyVatRebated.index();
    public static final int INVOIVEDVATREBATED = AttributesEnum.InvoivedVatRebated.index();
    public static final int CURRENCYUNITPRICEREBATED = AttributesEnum.CurrencyUnitPriceRebated.index();
    public static final int INVOICEDUNITPRICEREBATED = AttributesEnum.InvoicedUnitPriceRebated.index();
    public static final int CURRENCYGROSSAMOUNTREBATED = AttributesEnum.CurrencyGrossAmountRebated.index();
    public static final int INVOICEDGROSSAMOUNTREBATED = AttributesEnum.InvoicedGrossAmountRebated.index();
    public static final int CURRENCYNETAMOUNTREBATED = AttributesEnum.CurrencyNetAmountRebated.index();
    public static final int INVOICEDNETAMOUNTRABETED = AttributesEnum.InvoicedNetAmountRabeted.index();
    public static final int UNITOFMEASURE = AttributesEnum.UnitOfMeasure.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrtCardTransactionInvoiceRVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute DeltaTimestamp.
     * @return the DeltaTimestamp
     */
    public Timestamp getDeltaTimestamp() {
        return (Timestamp) getAttributeInternal(DELTATIMESTAMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DeltaTimestamp.
     * @param value value to set the  DeltaTimestamp
     */
    public void setDeltaTimestamp(Timestamp value) {
        setAttributeInternal(DELTATIMESTAMP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdated.
     * @return the LastUpdated
     */
    public Date getLastUpdated() {
        return (Date) getAttributeInternal(LASTUPDATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdated.
     * @param value value to set the  LastUpdated
     */
    public void setLastUpdated(Date value) {
        setAttributeInternal(LASTUPDATED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UrefTransactionId.
     * @return the UrefTransactionId
     */
    public String getUrefTransactionId() {
        return (String) getAttributeInternal(UREFTRANSACTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UrefTransactionId.
     * @param value value to set the  UrefTransactionId
     */
    public void setUrefTransactionId(String value) {
        setAttributeInternal(UREFTRANSACTIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PalsCountryCode.
     * @return the PalsCountryCode
     */
    public String getPalsCountryCode() {
        return (String) getAttributeInternal(PALSCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PalsCountryCode.
     * @param value value to set the  PalsCountryCode
     */
    public void setPalsCountryCode(String value) {
        setAttributeInternal(PALSCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PurchaseCountryCode.
     * @return the PurchaseCountryCode
     */
    public String getPurchaseCountryCode() {
        return (String) getAttributeInternal(PURCHASECOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PurchaseCountryCode.
     * @param value value to set the  PurchaseCountryCode
     */
    public void setPurchaseCountryCode(String value) {
        setAttributeInternal(PURCHASECOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderId.
     * @return the OrderId
     */
    public String getOrderId() {
        return (String) getAttributeInternal(ORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderId.
     * @param value value to set the  OrderId
     */
    public void setOrderId(String value) {
        setAttributeInternal(ORDERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrelimId.
     * @return the PrelimId
     */
    public String getPrelimId() {
        return (String) getAttributeInternal(PRELIMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrelimId.
     * @param value value to set the  PrelimId
     */
    public void setPrelimId(String value) {
        setAttributeInternal(PRELIMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Card1Id.
     * @return the Card1Id
     */
    public String getCard1Id() {
        return (String) getAttributeInternal(CARD1ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Card1Id.
     * @param value value to set the  Card1Id
     */
    public void setCard1Id(String value) {
        setAttributeInternal(CARD1ID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Card2Id.
     * @return the Card2Id
     */
    public String getCard2Id() {
        return (String) getAttributeInternal(CARD2ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Card2Id.
     * @param value value to set the  Card2Id
     */
    public void setCard2Id(String value) {
        setAttributeInternal(CARD2ID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CardId2Info.
     * @return the CardId2Info
     */
    public String getCardId2Info() {
        return (String) getAttributeInternal(CARDID2INFO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CardId2Info.
     * @param value value to set the  CardId2Info
     */
    public void setCardId2Info(String value) {
        setAttributeInternal(CARDID2INFO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OdometerPortal.
     * @return the OdometerPortal
     */
    public String getOdometerPortal() {
        return (String) getAttributeInternal(ODOMETERPORTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OdometerPortal.
     * @param value value to set the  OdometerPortal
     */
    public void setOdometerPortal(String value) {
        setAttributeInternal(ODOMETERPORTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Odometer.
     * @return the Odometer
     */
    public String getOdometer() {
        return (String) getAttributeInternal(ODOMETER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Odometer.
     * @param value value to set the  Odometer
     */
    public void setOdometer(String value) {
        setAttributeInternal(ODOMETER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransactionDt.
     * @return the TransactionDt
     */
    public Date getTransactionDt() {
        return (Date) getAttributeInternal(TRANSACTIONDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransactionDt.
     * @param value value to set the  TransactionDt
     */
    public void setTransactionDt(Date value) {
        setAttributeInternal(TRANSACTIONDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransactionTime.
     * @return the TransactionTime
     */
    public Timestamp getTransactionTime() {
        return (Timestamp) getAttributeInternal(TRANSACTIONTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransactionTime.
     * @param value value to set the  TransactionTime
     */
    public void setTransactionTime(Timestamp value) {
        setAttributeInternal(TRANSACTIONTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StationName.
     * @return the StationName
     */
    public String getStationName() {
        return (String) getAttributeInternal(STATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StationName.
     * @param value value to set the  StationName
     */
    public void setStationName(String value) {
        setAttributeInternal(STATIONNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StationGroupId.
     * @return the StationGroupId
     */
    public String getStationGroupId() {
        return (String) getAttributeInternal(STATIONGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StationGroupId.
     * @param value value to set the  StationGroupId
     */
    public void setStationGroupId(String value) {
        setAttributeInternal(STATIONGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StationGroupName.
     * @return the StationGroupName
     */
    public String getStationGroupName() {
        return (String) getAttributeInternal(STATIONGROUPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StationGroupName.
     * @param value value to set the  StationGroupName
     */
    public void setStationGroupName(String value) {
        setAttributeInternal(STATIONGROUPNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IccInvoiceNumber.
     * @return the IccInvoiceNumber
     */
    public String getIccInvoiceNumber() {
        return (String) getAttributeInternal(ICCINVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IccInvoiceNumber.
     * @param value value to set the  IccInvoiceNumber
     */
    public void setIccInvoiceNumber(String value) {
        setAttributeInternal(ICCINVOICENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceNumberNonCollective.
     * @return the InvoiceNumberNonCollective
     */
    public String getInvoiceNumberNonCollective() {
        return (String) getAttributeInternal(INVOICENUMBERNONCOLLECTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceNumberNonCollective.
     * @param value value to set the  InvoiceNumberNonCollective
     */
    public void setInvoiceNumberNonCollective(String value) {
        setAttributeInternal(INVOICENUMBERNONCOLLECTIVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoicingDate.
     * @return the InvoicingDate
     */
    public Date getInvoicingDate() {
        return (Date) getAttributeInternal(INVOICINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoicingDate.
     * @param value value to set the  InvoicingDate
     */
    public void setInvoicingDate(Date value) {
        setAttributeInternal(INVOICINGDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RecieptNo.
     * @return the RecieptNo
     */
    public String getRecieptNo() {
        return (String) getAttributeInternal(RECIEPTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RecieptNo.
     * @param value value to set the  RecieptNo
     */
    public void setRecieptNo(String value) {
        setAttributeInternal(RECIEPTNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PurchaseCurrency.
     * @return the PurchaseCurrency
     */
    public String getPurchaseCurrency() {
        return (String) getAttributeInternal(PURCHASECURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PurchaseCurrency.
     * @param value value to set the  PurchaseCurrency
     */
    public void setPurchaseCurrency(String value) {
        setAttributeInternal(PURCHASECURRENCY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExchangeRate.
     * @return the ExchangeRate
     */
    public Number getExchangeRate() {
        return (Number) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExchangeRate.
     * @param value value to set the  ExchangeRate
     */
    public void setExchangeRate(Number value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IccYn.
     * @return the IccYn
     */
    public String getIccYn() {
        return (String) getAttributeInternal(ICCYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IccYn.
     * @param value value to set the  IccYn
     */
    public void setIccYn(String value) {
        setAttributeInternal(ICCYN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransactionType.
     * @return the TransactionType
     */
    public String getTransactionType() {
        return (String) getAttributeInternal(TRANSACTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransactionType.
     * @param value value to set the  TransactionType
     */
    public void setTransactionType(String value) {
        setAttributeInternal(TRANSACTIONTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrelimStatusCode.
     * @return the PrelimStatusCode
     */
    public String getPrelimStatusCode() {
        return (String) getAttributeInternal(PRELIMSTATUSCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrelimStatusCode.
     * @param value value to set the  PrelimStatusCode
     */
    public void setPrelimStatusCode(String value) {
        setAttributeInternal(PRELIMSTATUSCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceNumberCollective.
     * @return the InvoiceNumberCollective
     */
    public String getInvoiceNumberCollective() {
        return (String) getAttributeInternal(INVOICENUMBERCOLLECTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceNumberCollective.
     * @param value value to set the  InvoiceNumberCollective
     */
    public void setInvoiceNumberCollective(String value) {
        setAttributeInternal(INVOICENUMBERCOLLECTIVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Ksid.
     * @return the Ksid
     */
    public String getKsid() {
        return (String) getAttributeInternal(KSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Ksid.
     * @param value value to set the  Ksid
     */
    public void setKsid(String value) {
        setAttributeInternal(KSID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PartnerId.
     * @return the PartnerId
     */
    public String getPartnerId() {
        return (String) getAttributeInternal(PARTNERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PartnerId.
     * @param value value to set the  PartnerId
     */
    public void setPartnerId(String value) {
        setAttributeInternal(PARTNERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AccountId.
     * @return the AccountId
     */
    public String getAccountId() {
        return (String) getAttributeInternal(ACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AccountId.
     * @param value value to set the  AccountId
     */
    public void setAccountId(String value) {
        setAttributeInternal(ACCOUNTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CardgroupMainType.
     * @return the CardgroupMainType
     */
    public String getCardgroupMainType() {
        return (String) getAttributeInternal(CARDGROUPMAINTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CardgroupMainType.
     * @param value value to set the  CardgroupMainType
     */
    public void setCardgroupMainType(String value) {
        setAttributeInternal(CARDGROUPMAINTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CardgroupSubType.
     * @return the CardgroupSubType
     */
    public String getCardgroupSubType() {
        return (String) getAttributeInternal(CARDGROUPSUBTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CardgroupSubType.
     * @param value value to set the  CardgroupSubType
     */
    public void setCardgroupSubType(String value) {
        setAttributeInternal(CARDGROUPSUBTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CardgroupSeq.
     * @return the CardgroupSeq
     */
    public String getCardgroupSeq() {
        return (String) getAttributeInternal(CARDGROUPSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CardgroupSeq.
     * @param value value to set the  CardgroupSeq
     */
    public void setCardgroupSeq(String value) {
        setAttributeInternal(CARDGROUPSEQ, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Terminal.
     * @return the Terminal
     */
    public String getTerminal() {
        return (String) getAttributeInternal(TERMINAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Terminal.
     * @param value value to set the  Terminal
     */
    public void setTerminal(String value) {
        setAttributeInternal(TERMINAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DeltaTimestamp1.
     * @return the DeltaTimestamp1
     */
    public Timestamp getDeltaTimestamp1() {
        return (Timestamp) getAttributeInternal(DELTATIMESTAMP1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DeltaTimestamp1.
     * @param value value to set the  DeltaTimestamp1
     */
    public void setDeltaTimestamp1(Timestamp value) {
        setAttributeInternal(DELTATIMESTAMP1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UrefTransactionId1.
     * @return the UrefTransactionId1
     */
    public String getUrefTransactionId1() {
        return (String) getAttributeInternal(UREFTRANSACTIONID1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UrefTransactionId1.
     * @param value value to set the  UrefTransactionId1
     */
    public void setUrefTransactionId1(String value) {
        setAttributeInternal(UREFTRANSACTIONID1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PalsCountryCode1.
     * @return the PalsCountryCode1
     */
    public String getPalsCountryCode1() {
        return (String) getAttributeInternal(PALSCOUNTRYCODE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PalsCountryCode1.
     * @param value value to set the  PalsCountryCode1
     */
    public void setPalsCountryCode1(String value) {
        setAttributeInternal(PALSCOUNTRYCODE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DetailNo.
     * @return the DetailNo
     */
    public String getDetailNo() {
        return (String) getAttributeInternal(DETAILNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DetailNo.
     * @param value value to set the  DetailNo
     */
    public void setDetailNo(String value) {
        setAttributeInternal(DETAILNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PalsPGroupId.
     * @return the PalsPGroupId
     */
    public String getPalsPGroupId() {
        return (String) getAttributeInternal(PALSPGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PalsPGroupId.
     * @param value value to set the  PalsPGroupId
     */
    public void setPalsPGroupId(String value) {
        setAttributeInternal(PALSPGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PalsPGroupSubgroupId.
     * @return the PalsPGroupSubgroupId
     */
    public String getPalsPGroupSubgroupId() {
        return (String) getAttributeInternal(PALSPGROUPSUBGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PalsPGroupSubgroupId.
     * @param value value to set the  PalsPGroupSubgroupId
     */
    public void setPalsPGroupSubgroupId(String value) {
        setAttributeInternal(PALSPGROUPSUBGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FuelYn.
     * @return the FuelYn
     */
    public String getFuelYn() {
        return (String) getAttributeInternal(FUELYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FuelYn.
     * @param value value to set the  FuelYn
     */
    public void setFuelYn(String value) {
        setAttributeInternal(FUELYN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductName.
     * @return the ProductName
     */
    public String getProductName() {
        return (String) getAttributeInternal(PRODUCTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductName.
     * @param value value to set the  ProductName
     */
    public void setProductName(String value) {
        setAttributeInternal(PRODUCTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Quantity.
     * @return the Quantity
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Quantity.
     * @param value value to set the  Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VatRate.
     * @return the VatRate
     */
    public Number getVatRate() {
        return (Number) getAttributeInternal(VATRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VatRate.
     * @param value value to set the  VatRate
     */
    public void setVatRate(Number value) {
        setAttributeInternal(VATRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyVat.
     * @return the CurrencyVat
     */
    public Number getCurrencyVat() {
        return (Number) getAttributeInternal(CURRENCYVAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyVat.
     * @param value value to set the  CurrencyVat
     */
    public void setCurrencyVat(Number value) {
        setAttributeInternal(CURRENCYVAT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoicedVat.
     * @return the InvoicedVat
     */
    public Number getInvoicedVat() {
        return (Number) getAttributeInternal(INVOICEDVAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoicedVat.
     * @param value value to set the  InvoicedVat
     */
    public void setInvoicedVat(Number value) {
        setAttributeInternal(INVOICEDVAT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyUnitPrice.
     * @return the CurrencyUnitPrice
     */
    public Number getCurrencyUnitPrice() {
        return (Number) getAttributeInternal(CURRENCYUNITPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyUnitPrice.
     * @param value value to set the  CurrencyUnitPrice
     */
    public void setCurrencyUnitPrice(Number value) {
        setAttributeInternal(CURRENCYUNITPRICE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoicedUnitPrice.
     * @return the InvoicedUnitPrice
     */
    public Number getInvoicedUnitPrice() {
        return (Number) getAttributeInternal(INVOICEDUNITPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoicedUnitPrice.
     * @param value value to set the  InvoicedUnitPrice
     */
    public void setInvoicedUnitPrice(Number value) {
        setAttributeInternal(INVOICEDUNITPRICE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyGrossAmount.
     * @return the CurrencyGrossAmount
     */
    public Number getCurrencyGrossAmount() {
        return (Number) getAttributeInternal(CURRENCYGROSSAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyGrossAmount.
     * @param value value to set the  CurrencyGrossAmount
     */
    public void setCurrencyGrossAmount(Number value) {
        setAttributeInternal(CURRENCYGROSSAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoicedGrossAmount.
     * @return the InvoicedGrossAmount
     */
    public Number getInvoicedGrossAmount() {
        return (Number) getAttributeInternal(INVOICEDGROSSAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoicedGrossAmount.
     * @param value value to set the  InvoicedGrossAmount
     */
    public void setInvoicedGrossAmount(Number value) {
        setAttributeInternal(INVOICEDGROSSAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyNetAmount.
     * @return the CurrencyNetAmount
     */
    public Number getCurrencyNetAmount() {
        return (Number) getAttributeInternal(CURRENCYNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyNetAmount.
     * @param value value to set the  CurrencyNetAmount
     */
    public void setCurrencyNetAmount(Number value) {
        setAttributeInternal(CURRENCYNETAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoicedNetAmount.
     * @return the InvoicedNetAmount
     */
    public Number getInvoicedNetAmount() {
        return (Number) getAttributeInternal(INVOICEDNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoicedNetAmount.
     * @param value value to set the  InvoicedNetAmount
     */
    public void setInvoicedNetAmount(Number value) {
        setAttributeInternal(INVOICEDNETAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyDiscountAmount.
     * @return the CurrencyDiscountAmount
     */
    public Number getCurrencyDiscountAmount() {
        return (Number) getAttributeInternal(CURRENCYDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyDiscountAmount.
     * @param value value to set the  CurrencyDiscountAmount
     */
    public void setCurrencyDiscountAmount(Number value) {
        setAttributeInternal(CURRENCYDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceDiscountAmount.
     * @return the InvoiceDiscountAmount
     */
    public Number getInvoiceDiscountAmount() {
        return (Number) getAttributeInternal(INVOICEDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceDiscountAmount.
     * @param value value to set the  InvoiceDiscountAmount
     */
    public void setInvoiceDiscountAmount(Number value) {
        setAttributeInternal(INVOICEDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VatRefundableYn.
     * @return the VatRefundableYn
     */
    public String getVatRefundableYn() {
        return (String) getAttributeInternal(VATREFUNDABLEYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VatRefundableYn.
     * @param value value to set the  VatRefundableYn
     */
    public void setVatRefundableYn(String value) {
        setAttributeInternal(VATREFUNDABLEYN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SurchargeYn.
     * @return the SurchargeYn
     */
    public String getSurchargeYn() {
        return (String) getAttributeInternal(SURCHARGEYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SurchargeYn.
     * @param value value to set the  SurchargeYn
     */
    public void setSurchargeYn(String value) {
        setAttributeInternal(SURCHARGEYN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AtIabf538aPrpslKd.
     * @return the AtIabf538aPrpslKd
     */
    public String getAtIabf538aPrpslKd() {
        return (String) getAttributeInternal(ATIABF538APRPSLKD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AtIabf538aPrpslKd.
     * @param value value to set the  AtIabf538aPrpslKd
     */
    public void setAtIabf538aPrpslKd(String value) {
        setAttributeInternal(ATIABF538APRPSLKD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AsIabf538aPrpslsats.
     * @return the AsIabf538aPrpslsats
     */
    public Number getAsIabf538aPrpslsats() {
        return (Number) getAttributeInternal(ASIABF538APRPSLSATS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AsIabf538aPrpslsats.
     * @param value value to set the  AsIabf538aPrpslsats
     */
    public void setAsIabf538aPrpslsats(Number value) {
        setAttributeInternal(ASIABF538APRPSLSATS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyVatRebated.
     * @return the CurrencyVatRebated
     */
    public Number getCurrencyVatRebated() {
        return (Number) getAttributeInternal(CURRENCYVATREBATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyVatRebated.
     * @param value value to set the  CurrencyVatRebated
     */
    public void setCurrencyVatRebated(Number value) {
        setAttributeInternal(CURRENCYVATREBATED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoivedVatRebated.
     * @return the InvoivedVatRebated
     */
    public Number getInvoivedVatRebated() {
        return (Number) getAttributeInternal(INVOIVEDVATREBATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoivedVatRebated.
     * @param value value to set the  InvoivedVatRebated
     */
    public void setInvoivedVatRebated(Number value) {
        setAttributeInternal(INVOIVEDVATREBATED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyUnitPriceRebated.
     * @return the CurrencyUnitPriceRebated
     */
    public Number getCurrencyUnitPriceRebated() {
        return (Number) getAttributeInternal(CURRENCYUNITPRICEREBATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyUnitPriceRebated.
     * @param value value to set the  CurrencyUnitPriceRebated
     */
    public void setCurrencyUnitPriceRebated(Number value) {
        setAttributeInternal(CURRENCYUNITPRICEREBATED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoicedUnitPriceRebated.
     * @return the InvoicedUnitPriceRebated
     */
    public Number getInvoicedUnitPriceRebated() {
        return (Number) getAttributeInternal(INVOICEDUNITPRICEREBATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoicedUnitPriceRebated.
     * @param value value to set the  InvoicedUnitPriceRebated
     */
    public void setInvoicedUnitPriceRebated(Number value) {
        setAttributeInternal(INVOICEDUNITPRICEREBATED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyGrossAmountRebated.
     * @return the CurrencyGrossAmountRebated
     */
    public Number getCurrencyGrossAmountRebated() {
        return (Number) getAttributeInternal(CURRENCYGROSSAMOUNTREBATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyGrossAmountRebated.
     * @param value value to set the  CurrencyGrossAmountRebated
     */
    public void setCurrencyGrossAmountRebated(Number value) {
        setAttributeInternal(CURRENCYGROSSAMOUNTREBATED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoicedGrossAmountRebated.
     * @return the InvoicedGrossAmountRebated
     */
    public Number getInvoicedGrossAmountRebated() {
        return (Number) getAttributeInternal(INVOICEDGROSSAMOUNTREBATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoicedGrossAmountRebated.
     * @param value value to set the  InvoicedGrossAmountRebated
     */
    public void setInvoicedGrossAmountRebated(Number value) {
        setAttributeInternal(INVOICEDGROSSAMOUNTREBATED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrencyNetAmountRebated.
     * @return the CurrencyNetAmountRebated
     */
    public Number getCurrencyNetAmountRebated() {
        return (Number) getAttributeInternal(CURRENCYNETAMOUNTREBATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyNetAmountRebated.
     * @param value value to set the  CurrencyNetAmountRebated
     */
    public void setCurrencyNetAmountRebated(Number value) {
        setAttributeInternal(CURRENCYNETAMOUNTREBATED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoicedNetAmountRabeted.
     * @return the InvoicedNetAmountRabeted
     */
    public Number getInvoicedNetAmountRabeted() {
        return (Number) getAttributeInternal(INVOICEDNETAMOUNTRABETED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoicedNetAmountRabeted.
     * @param value value to set the  InvoicedNetAmountRabeted
     */
    public void setInvoicedNetAmountRabeted(Number value) {
        setAttributeInternal(INVOICEDNETAMOUNTRABETED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UnitOfMeasure.
     * @return the UnitOfMeasure
     */
    public String getUnitOfMeasure() {
        return (String) getAttributeInternal(UNITOFMEASURE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UnitOfMeasure.
     * @param value value to set the  UnitOfMeasure
     */
    public void setUnitOfMeasure(String value) {
        setAttributeInternal(UNITOFMEASURE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
