CREATE TABLE PRT_USER_PREFERRED_LANG 
(
  S_NO VARCHAR2(20 BYTE) NOT NULL 
, USER_ID VARCHAR2(100 BYTE) NOT NULL 
, PREFERRED_LANG VARCHAR2(10 BYTE) NOT NULL 
, MODIFIED_BY VARCHAR2(50 BYTE) NOT NULL 
, MODIFIED_DATE TIMESTAMP(6) NOT NULL 
, CONSTRAINT PRT_USER_PREFERRED_LANG_PK PRIMARY KEY 
  (
    S_NO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);
