CREATE TABLE PRT_CARD_AUDIT
(
  AUDIT_ID NUMBER NOT NULL 
, COUNTRY_CODE VARCHAR2(2 BYTE) NOT NULL 
, PRT_CARD_PK VARCHAR2(10 BYTE) NOT NULL
, OLD_PARTNER_ID VARCHAR2(8 BYTE) 
, OLD_ACCOUNT_ID VARCHAR2(10 BYTE) 
, OLD_CARDGROUP_MAIN_TYPE VARCHAR2(3 BYTE)  
, OLD_CARDGROUP_SUB_TYPE VARCHAR2(3 BYTE) 
, OLD_CARDGROUP_SEQ VARCHAR2(5 BYTE) 
, OLD_CARD_IDENTIFIER VARCHAR2(3 BYTE)
, OLD_CARD_TYPE VARCHAR2(3 BYTE) 
, OLD_MAGNETIC_CODE VARCHAR2(20 BYTE) 
, OLD_CARD_EMBOSS_NUM VARCHAR2(20 BYTE) 
, OLD_INVOICE_INFORMATION VARCHAR2(90 BYTE)
, OLD_CARD_EXPIRY DATE 
, OLD_BLOCK_TYPE VARCHAR2(3 BYTE) 
, OLD_BLOCK_CODE VARCHAR2(3 BYTE) 
, OLD_BLOCK_ACTION VARCHAR2(1 BYTE)
, OLD_BLOCK_DATE DATE 
, OLD_BLOCK_TIME TIMESTAMP(6) 
, OLD_BLOCK_LEVEL VARCHAR2(3 BYTE)
, OLD_MANUFACTURED_DATE DATE 
, OLD_ROUTEX_CUSTOMER_NUMBER VARCHAR2(6 BYTE)
, OLD_INVOICE_ADDR1 VARCHAR2(60 BYTE)
, OLD_INVOICE_ADDR2  VARCHAR2(60 BYTE)
, OLD_INVOICE_POSTAL_CODE VARCHAR2(10 BYTE)
, OLD_INVOICE_CITY VARCHAR2(60 BYTE)
, OLD_ADDR_SEQ VARCHAR2(5 BYTE)
, OLD_INVOICE_COUNTRY VARCHAR2(2 BYTE)
, OLD_INVOICE_ADDR_LEVEL VARCHAR2(3 BYTE)
, OLD_INVOICE_ADDR_TYPE VARCHAR2(3 BYTE)
, OLD_MODIFIED_BY VARCHAR2(50 BYTE) 
, OLD_MODIFIED_DATE TIMESTAMP(6) 
, NEW_PARTNER_ID VARCHAR2(8 BYTE)  
, NEW_ACCOUNT_ID VARCHAR2(10 BYTE) 
, NEW_CARDGROUP_MAIN_TYPE VARCHAR2(3 BYTE)  
, NEW_CARDGROUP_SUB_TYPE VARCHAR2(3 BYTE) 
, NEW_CARDGROUP_SEQ VARCHAR2(5 BYTE) 
, NEW_CARD_IDENTIFIER VARCHAR2(3 BYTE)
, NEW_CARD_TYPE VARCHAR2(3 BYTE) 
, NEW_MAGNETIC_CODE VARCHAR2(20 BYTE) 
, NEW_CARD_EMBOSS_NUM VARCHAR2(20 BYTE) 
, NEW_INVOICE_INFORMATION VARCHAR2(90 BYTE)
, NEW_CARD_EXPIRY DATE 
, NEW_BLOCK_TYPE VARCHAR2(3 BYTE) 
, NEW_BLOCK_CODE VARCHAR2(3 BYTE) 
, NEW_BLOCK_ACTION VARCHAR2(1 BYTE)
, NEW_BLOCK_DATE DATE 
, NEW_BLOCK_TIME TIMESTAMP(6) 
, NEW_BLOCK_LEVEL VARCHAR2(3 BYTE)
, NEW_MANUFACTURED_DATE DATE 
, NEW_ROUTEX_CUSTOMER_NUMBER VARCHAR2(6 BYTE)
, NEW_INVOICE_ADDR1 VARCHAR2(60 BYTE)
, NEW_INVOICE_ADDR2  VARCHAR2(60 BYTE)
, NEW_INVOICE_POSTAL_CODE VARCHAR2(10 BYTE)
, NEW_INVOICE_CITY VARCHAR2(60 BYTE)
, NEW_ADDR_SEQ VARCHAR2(5 BYTE)
, NEW_INVOICE_COUNTRY VARCHAR2(2 BYTE)
, NEW_INVOICE_ADDR_LEVEL VARCHAR2(3 BYTE)
, NEW_INVOICE_ADDR_TYPE VARCHAR2(3 BYTE)
, NEW_MODIFIED_BY VARCHAR2(50 BYTE) 
, NEW_MODIFIED_DATE TIMESTAMP(6) 
, U_ID VARCHAR2(50 BYTE) 
, ACTION VARCHAR2(20 BYTE) 
, NEW_TIMESTAMP DATE 

, CONSTRAINT PRT_CARD_AUDIT_PK PRIMARY KEY 
  (
    AUDIT_ID 
   )
  ENABLE 
) 

PARTITION BY LIST(COUNTRY_CODE) (
    PARTITION PRT_CARD_AUDIT_SWEDEN VALUES ('SE'),
    PARTITION PRT_CARD_AUDIT_NORWAY VALUES ('NO'),
    PARTITION PRT_CARD_AUDIT_DENMARK VALUES ('DK'),
    PARTITION PRT_CARD_AUDIT_LATVIA VALUES ('LV'),
    PARTITION PRT_CARD_AUDIT_LITHUANIA VALUES ('LT'),
    PARTITION PRT_CARD_AUDIT_ESTONIA VALUES ('EE'),
    PARTITION PRT_CARD_AUDIT_POLAND VALUES ('PL')
);
