CREATE TABLE PRT_GEN_IMAGE_MAP 
(
  ID NUMBER NOT NULL 
, FEATURE_NAME VARCHAR2(200 BYTE) 
, FEATURE_VALUE VARCHAR2(200 BYTE) 
, CONTROL_ATTR VARCHAR2(200 BYTE) 
, CONTROL_ATTR_VALUE VARCHAR2(200 BYTE) 
, IMAGEID VARCHAR2(512 BYTE) 
, MODIFIED_BY VARCHAR2(30 BYTE) 
, MODIFIED_DATE TIMESTAMP(6) 
, LANG VARCHAR2(10 BYTE) 
, CONSTRAINT PRT_GEN_IMAGE_MAP_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "WCPCUSTOM" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 1048576 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);
