<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="E001PortalBalanceCheckBPEL"
     targetNamespace="http://xmlns.oracle.com/E001SyncPortalBalanceChecktoCGIApp/E001SyncPortalBalanceChecktoCGI/E001PortalBalanceCheckBPEL"
     xmlns:ns2="http://www.statoilfuelretail.com/integration/E001/E001InstanceId"
     xmlns:ns1="http://www.statoilfuelretail.com/integration/E001/E001PortalBalanceCheck"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/E001SyncPortalBalanceChecktoCGIApp/E001SyncPortalBalanceChecktoCGI/E001PortalBalanceCheckBPEL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="E001PortalBalanceCheckBPEL">
        <plnk:role name="E001PortalBalanceCheckBPELProvider">
            <plnk:portType name="client:E001PortalBalanceCheckBPEL"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.statoilfuelretail.com/integration/E001/E001PortalBalanceCheck"
                 schemaLocation="xsd/E001PortalBalanceCheck.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.statoilfuelretail.com/integration/E001/E001InstanceId"
                 schemaLocation="xsd/E001InstanceId.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="E001PortalBalanceCheckBPELRequestMessage">
        <wsdl:part name="payload" element="ns1:requestPayload"/>
    </wsdl:message>
    <wsdl:message name="E001PortalBalanceCheckBPELResponseMessage">
        <wsdl:part name="payload" element="ns1:responsePayload"/>
    </wsdl:message>
    <wsdl:portType name="E001PortalBalanceCheckBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:E001PortalBalanceCheckBPELRequestMessage"/>
            <wsdl:output message="client:E001PortalBalanceCheckBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
