
  CREATE TABLE "SOACUSTOM"."ENGAGE_SOA_INVOICE_ERRORLOG" 
   (	"DELTA_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"INVOICE_NUMBER" VARCHAR2(20 BYTE), 
	"COLLECTIVE_INVOICE_NUMBER" VARCHAR2(20 BYTE), 
	"INVOICE_DATE" DATE, 
	"INVOICED_CARD" VARCHAR2(20 BYTE), 
	"CARD_TYPE" VARCHAR2(20 BYTE), 
	"MAGNETIC_CODE" VARCHAR2(50 BYTE), 
	"ROUTEX_VAT_INVOICE_NUMBER" VARCHAR2(50 BYTE), 
	"INVOICE_INFORMATION" VARCHAR2(200 BYTE), 
	"INVOICE_DELIVERY_ADDRESS" VARCHAR2(200 BYTE), 
	"NET_INVOICE_CODE" VARCHAR2(20 BYTE), 
	"ORIGINAL_INVOICE_NUMBER" VARCHAR2(20 BYTE), 
	"CORRECTION_PRESENTATION" VARCHAR2(20 BYTE), 
	"INV_TOTAL_GROSS_AMT_FOREIGN" FLOAT(126), 
	"INV_TOTAL_NET_VAT_MANDATORY" FLOAT(126), 
	"INV_TOTAL_NET_VAT_FREE" FLOAT(126), 
	"INV_TOTAL_VAT_AMT" FLOAT(126), 
	"INV_TOTAL_GROSS_AMT" FLOAT(126), 
	"CURR_TOTAL_NET_VAT_MANDATORY" FLOAT(126), 
	"CURR_TOTAL_NET_VAT_FREE" FLOAT(126), 
	"CURR_TOTAL_VAT_AMT" FLOAT(126), 
	"CURR_TOTAL_GROSS_AMT" FLOAT(126), 
	"CURR_TOTAL_GROSS_AMT_FOREIGN" FLOAT(126), 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"SOA_ERROR_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SOA_ERROR_DESC" VARCHAR2(20 BYTE), 
	"EMAIL_FLAG" NUMBER(*,0), 
	"DELTA_RECIPT_FLAG" NUMBER(*,0), 
	 CONSTRAINT "ENGAGE_SOA_INVOICE_ERRORL_PK" PRIMARY KEY ("DELTA_TS", "SOA_ERROR_CODE", "COUNTRY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SOACUSTOM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SOACUSTOM" ;

  CREATE OR REPLACE TRIGGER "SOACUSTOM"."INVOICE_ERRORLOG_TRIG" 
BEFORE INSERT OR UPDATE ON ENGAGE_SOA_INVOICE_ERRORLOG 
FOR EACH ROW 
BEGIN
 :new.MODIFIED_DATE := CURRENT_TIMESTAMP;
 :new.MODIFIED_BY := SYS_CONTEXT('USERENV','OS_USER');
END;
/
ALTER TRIGGER "SOACUSTOM"."INVOICE_ERRORLOG_TRIG" ENABLE;
