<!--To be run in SOA DB-->

CREATE TABLE "SOACUSTOM"."ENGAGE_PALS_CARD_DTA_ERRORLOG"
  (
    "DELTA_TS"            VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "COUNTRY_CODE"        VARCHAR2(2 BYTE),
    "PARTNER_ID"          VARCHAR2(20 BYTE),
    "CARDGROUP_MAIN_TYPE" VARCHAR2(20 BYTE),
    "CARDGROUP_SUB_TYPE"  VARCHAR2(20 BYTE),
    "CARDGROUP_SEQ"       VARCHAR2(20 BYTE),
    "PRT_CARD_PK"         VARCHAR2(20 BYTE),
    "CARD_IDENTIFIER"     VARCHAR2(20 BYTE),
    "CARD_TYPE"           VARCHAR2(20 BYTE),
    "MAGNETIC_CODE"       VARCHAR2(20 BYTE),
    "CARD_EMBOSS_NUM"     VARCHAR2(50 BYTE),
    "INVOICE_INFORMATION" VARCHAR2(200 BYTE),
    "CARD_EXPIRY" DATE,
    "BLOCK_TYPE"   VARCHAR2(20 BYTE),
    "BLOCK_CODE"   VARCHAR2(20 BYTE),
    "BLOCK_ACTION" VARCHAR2(20 BYTE),
    "BLOCK_DATE" DATE,
    "BLOCK_TIME" TIMESTAMP (6),
    "BLOCK_LEVEL" VARCHAR2(20 BYTE),
    "MANUFACTURED_DATE" DATE,
    "ROUTEX_CUSTOMER_NUMBER" VARCHAR2(20 BYTE),
    "INVOICE_ADDR1"          VARCHAR2(200 BYTE),
    "INVOICE_ADDR2"          VARCHAR2(200 BYTE),
    "INVOICE_POSTAL_CODE"    VARCHAR2(20 BYTE),
    "INVOICE_CITY"           VARCHAR2(200 BYTE),
    "ADDR_SEQ"               VARCHAR2(20 BYTE),
    "INVOICE_COUNTRY"        VARCHAR2(20 BYTE),
    "INVOICE_ADDR_LEVEL"     VARCHAR2(20 BYTE),
    "INVOICE_ADDR_TYPE"      VARCHAR2(20 BYTE),
    "MODIFIED_BY"            VARCHAR2(100 BYTE),
    "MODIFIED_DATE" TIMESTAMP (6),
    "SOA_ERROR_CODE"    VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "SOA_ERROR_DESC"    VARCHAR2(300 BYTE),
    "EMAIL_FLAG"        NUMBER,
    "DELTA_RECIPT_FLAG" NUMBER,
    CONSTRAINT "ENGAGE_PALS_CARD_DTA_ERRO_PK" PRIMARY KEY ("DELTA_TS", "SOA_ERROR_CODE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SOACUSTOM" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SOACUSTOM" ;