
  CREATE TABLE "SOACUSTOM"."ENGAGE_SOA_CARDGROUP_ERRORLOG" 
   (	"DELTA_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"PARTNER_ID" VARCHAR2(20 BYTE), 
	"F_FORHOLD_HTP" VARCHAR2(20 BYTE), 
	"F_FORHOLD_UTP" VARCHAR2(20 BYTE), 
	"F_FORHOLD_LNR" VARCHAR2(20 BYTE), 
	"KONTO_ID" VARCHAR2(20 BYTE), 
	"F_FORHOLD_TX" VARCHAR2(50 BYTE), 
	"EMAILFLAG" NUMBER(*,0), 
	"SOA_ERROR_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SOA_ERROR_DESC" VARCHAR2(500 BYTE), 
	"DELTA_RECIPT_FLAG" NUMBER(*,0), 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_DATETIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 CONSTRAINT "ENGAGE_SOA_CARDGROUP_ERRO_PK" PRIMARY KEY ("DELTA_TS", "SOA_ERROR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOACUSTOM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOACUSTOM" ;

  CREATE OR REPLACE TRIGGER "SOACUSTOM"."CARDGROUP_ERRORLOG_TRIG" 
BEFORE INSERT OR UPDATE ON ENGAGE_SOA_CARDGROUP_ERRORLOG 
FOR EACH ROW 
BEGIN
:new.MODIFIED_DATETIME := CURRENT_TIMESTAMP;
:new.MODIFIED_BY := SYS_CONTEXT('USERENV','OS_USER');
END;
/
ALTER TRIGGER "SOACUSTOM"."CARDGROUP_ERRORLOG_TRIG" ENABLE;
