
  CREATE TABLE "SOACUSTOM"."ENGAGE_SOA_TXNHEADER_ERRORLOG" 
   (	"DELTA_TS" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PALS_COUNTRY_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"UREF_TRANSACTION_ID" VARCHAR2(20 BYTE), 
	"ORDER_ID" VARCHAR2(20 BYTE), 
	"PRELIM_ID" VARCHAR2(20 BYTE), 
	"PALS_ORDER_MAIN_TYPE" VARCHAR2(20 BYTE), 
	"PALS_ORDER_SUB_TYPE" VARCHAR2(20 BYTE), 
	"ORDER_BACKWARD_REF" VARCHAR2(20 BYTE), 
	"ORDER_FORWARD_REF" VARCHAR2(20 BYTE), 
	"ORDER_VALID_CODE" VARCHAR2(20 BYTE), 
	"ORDER_CREATE_CODE" VARCHAR2(20 BYTE), 
	"SITE_NUMBER" VARCHAR2(20 BYTE), 
	"PURCHASE_COUNTRY_CODE" VARCHAR2(20 BYTE), 
	"INVOICED_CARD_ID" VARCHAR2(20 BYTE), 
	"KSID" VARCHAR2(20 BYTE), 
	"CARD_1_ID" VARCHAR2(20 BYTE), 
	"CARD_ID_2_INFO" VARCHAR2(20 BYTE), 
	"CARD_2_ID" VARCHAR2(20 BYTE), 
	"ODOMETER" VARCHAR2(20 BYTE), 
	"TRANSACTION_DT" VARCHAR2(30 BYTE), 
	"TRANSACTION_TIME" VARCHAR2(30 BYTE), 
	"STATION_NAME" VARCHAR2(20 BYTE), 
	"ICC_INVOICE_NUMBER" VARCHAR2(20 BYTE), 
	"INVOICE_NUMBER_COLLECTIVE" VARCHAR2(20 BYTE), 
	"INVOICE_NUMBER_NON_COLLECTIVE" VARCHAR2(20 BYTE), 
	"INVOICING_DATE" VARCHAR2(20 BYTE), 
	"TERMINAL_ID" VARCHAR2(20 BYTE), 
	"TERMINAL_SEQ" VARCHAR2(20 BYTE), 
	"PURCHASE_CURRENCY" VARCHAR2(20 BYTE), 
	"EXCHANGE_RATE" VARCHAR2(20 BYTE), 
	"ICC_YN" VARCHAR2(20 BYTE), 
	"TRANSACTION_TYPE" VARCHAR2(20 BYTE), 
	"PRELIM_STATUS_CODE" VARCHAR2(20 BYTE), 
	"PARTNER_ID" VARCHAR2(20 BYTE), 
	"ACCOUNT_ID" VARCHAR2(20 BYTE), 
	"CARDGROUP_MAIN_TYPE" VARCHAR2(20 BYTE), 
	"CARDGROUP_SUB_TYPE" VARCHAR2(20 BYTE), 
	"CARDGROUP_SEQ" VARCHAR2(20 BYTE), 
	"INVOICE_FLAG" VARCHAR2(20 BYTE), 
	"WM_TRANS_REF_NUMBER" VARCHAR2(20 BYTE), 
	"PALS_MODIFIED_DATE" VARCHAR2(20 BYTE), 
	"CUSTOMER_SERVICE_ID" VARCHAR2(20 BYTE), 
	"MODIFIED_BY" VARCHAR2(60 BYTE), 
	"PORTAL_MODIFIED_DATE" VARCHAR2(30 BYTE), 
	"PREVIOUS_ODOMETER" VARCHAR2(20 BYTE), 
	"ODOMETER_PORTAL" VARCHAR2(20 BYTE), 
	"MODIFIED_DATETIME" TIMESTAMP (6), 
	"SOA_ERROR_CODE" VARCHAR2(20 BYTE), 
	"SOA_ERROR_DESC" VARCHAR2(1000 BYTE), 
	"EMAIL_FLAG" VARCHAR2(10 BYTE), 
	"DELTA_RECIPT_FLAG" VARCHAR2(10 BYTE), 
	 CONSTRAINT "ENGAGE_SOA_TXNHEADER_ERRO_PK" PRIMARY KEY ("DELTA_TS", "PALS_COUNTRY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOACUSTOM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOACUSTOM" ;

  CREATE OR REPLACE TRIGGER "SOACUSTOM"."ENGAGE_SOA_TXNHEADER_TRIG" 
BEFORE UPDATE ON ENGAGE_SOA_TXNHEADER_ERRORLOG 
FOR EACH ROW 
BEGIN
  :new.MODIFIED_DATETIME := CURRENT_TIMESTAMP;
  :new.MODIFIED_BY := SYS_CONTEXT('USERENV','OS_USER');
END;
/
ALTER TRIGGER "SOACUSTOM"."ENGAGE_SOA_TXNHEADER_TRIG" ENABLE;
