
  CREATE TABLE "SOACUSTOM"."ENGAGE_SOA_INV_PMT_ERRORLOG" 
   (	"DELTA_TS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"INVOICE_DOC_NUMBER" VARCHAR2(20 BYTE), 
	"INVOICE_DOC_TYPE" VARCHAR2(20 BYTE), 
	"PARTNER_ID" VARCHAR2(20 BYTE), 
	"COMPANY_TYPE" VARCHAR2(20 BYTE), 
	"CARDGROUP_MAIN_TYPE" VARCHAR2(20 BYTE), 
	"CARDGROUP_SUB_TYPE" VARCHAR2(20 BYTE), 
	"CARDGROUP_SEQ" VARCHAR2(20 BYTE), 
	"INVOICING_DATE" VARCHAR2(20 BYTE), 
	"INVOICING_DUE_DATE" VARCHAR2(20 BYTE), 
	"INVOICE_LEVEL" VARCHAR2(20 BYTE), 
	"PAYMENT_CODE" VARCHAR2(20 BYTE), 
	"ELECTRONIC_INVOICE_TYPE" VARCHAR2(20 BYTE), 
	"INVOICE_LANG_CODE" VARCHAR2(20 BYTE), 
	"GROUPING_INVOICE_TYPE" VARCHAR2(20 BYTE), 
	"PRINT_INVOICE" VARCHAR2(20 BYTE), 
	"PARTNER_SHORTNAME" VARCHAR2(100 BYTE), 
	"INVOICE_ADDR1" VARCHAR2(100 BYTE), 
	"INVOICE_ADDR2" VARCHAR2(100 BYTE), 
	"INVOICE_ADDR3" VARCHAR2(100 BYTE), 
	"INVOICE_COUNTRY" VARCHAR2(100 BYTE), 
	"INVOICE_RECEIVER" VARCHAR2(100 BYTE), 
	"COMPANY_NAME" VARCHAR2(100 BYTE), 
	"ERROR_CODE" VARCHAR2(20 BYTE), 
	"ERROR_DESC" VARCHAR2(2000 BYTE), 
	"EMAIL_FLAG" VARCHAR2(20 BYTE), 
	"DELTA_FLAG" VARCHAR2(20 BYTE), 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	 CONSTRAINT "ENGAGE_SOA_INV_PMT_ERRORL_PK" PRIMARY KEY ("DELTA_TS", "COUNTRY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOACUSTOM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOACUSTOM" ;

  CREATE OR REPLACE TRIGGER "SOACUSTOM"."INV_PAYMENT_ERRORLOG_TRG" 
BEFORE INSERT OR UPDATE ON ENGAGE_SOA_INV_PMT_ERRORLOG 
FOR EACH ROW 
BEGIN
  :new.MODIFIED_DATE := CURRENT_TIMESTAMP;
  :new.MODIFIED_BY       := SYS_CONTEXT('USERENV','OS_USER');
END;
/
ALTER TRIGGER "SOACUSTOM"."INV_PAYMENT_ERRORLOG_TRG" ENABLE;
