<!--To be run in portal DB-->

CREATE TABLE "WCPCUSTOM"."SOA_PRT_CARD_TEMP"
  (
    "DELTA_TS"            VARCHAR2(40 BYTE),
    "COUNTRY_CODE"        VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "PARTNER_ID"          VARCHAR2(8 BYTE) NOT NULL ENABLE,
    "ACCOUNT_ID"          VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "CARDGROUP_MAIN_TYPE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "CARDGROUP_SUB_TYPE"  VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "CARDGROUP_SEQ"       VARCHAR2(5 BYTE) NOT NULL ENABLE,
    "PRT_CARD_PK"         VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "CARD_IDENTIFIER"     VARCHAR2(3 BYTE),
    "CARD_TYPE"           VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "MAGNETIC_CODE"       VARCHAR2(3 BYTE),
    "CARD_EMBOSS_NUM"     VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "INVOICE_INFORMATION" VARCHAR2(90 BYTE),
    "CARD_EXPIRY" DATE,
    "BLOCK_TYPE"   VARCHAR2(3 BYTE),
    "BLOCK_CODE"   VARCHAR2(3 BYTE),
    "BLOCK_ACTION" VARCHAR2(1 BYTE),
    "BLOCK_DATE" DATE,
    "BLOCK_TIME" TIMESTAMP (6),
    "BLOCK_LEVEL" VARCHAR2(3 BYTE),
    "MANUFACTURED_DATE" DATE,
    "ROUTEX_CUSTOMER_NUMBER" VARCHAR2(6 BYTE),
    "INVOICE_ADDR1"          VARCHAR2(60 BYTE),
    "INVOICE_ADDR2"          VARCHAR2(60 BYTE),
    "INVOICE_POSTAL_CODE"    VARCHAR2(10 BYTE),
    "INVOICE_CITY"           VARCHAR2(60 BYTE),
    "ADDR_SEQ"               VARCHAR2(5 BYTE),
    "INVOICE_COUNTRY"        VARCHAR2(2 BYTE),
    "INVOICE_ADDR_LEVEL"     VARCHAR2(3 BYTE),
    "INVOICE_ADDR_TYPE"      VARCHAR2(3 BYTE),
    "MODIFIED_BY"            VARCHAR2(25 BYTE) NOT NULL ENABLE,
    "MODIFIED_DATE" TIMESTAMP (6) NOT NULL ENABLE
  )
  SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "WCPCUSTOM" ;