<!--To be run in portal DB-->
create or replace
PROCEDURE SOA_MERGE_PRT_CARD 
(
  COUNTRYCODE IN VARCHAR2  
, PRTCARDPK IN VARCHAR2  
, CARDTYPE IN VARCHAR2  
, PARTNERID IN VARCHAR2  
, CARDGROUPMAINTYPE IN VARCHAR2  
, CARDGROUPSUBTYPE IN VARCHAR2  
, CARDGROUPSEQ IN VARCHAR2  
, CARDEMBOSSNO IN VARCHAR2
, CARDIDENTIFIER IN VARCHAR2
, MAGNETICCODE IN VARCHAR2
, INVOICEINFORMATION IN VARCHAR2
, CARDEXPIRY IN DATE
, BLOCKTYPE  IN VARCHAR2
, BLOCKCODE IN VARCHAR2
, BLOCKACTION IN VARCHAR2
, BLOCKDATE IN DATE
, BLOCKTIME IN TIMESTAMP
, BLOCKLEVEL IN VARCHAR2
, MANUFACTUREDDATE IN DATE
, ROUTEXCUSTOMERNUMBER IN VARCHAR2
, INVOICEADDR1 IN VARCHAR2
, INVOICEADDR2 IN VARCHAR2
, INVOICEPOSTALCODE IN VARCHAR2
, INVOICECITY IN VARCHAR2
, ADDRSEQ IN VARCHAR2
, INVOICECOUNTRY VARCHAR2
, INNVOICEADDRLEVEL IN VARCHAR2
, INNVOICEADDRTYPE IN VARCHAR2
, MODIFIEDBY IN VARCHAR2
, MODIFIEDDATE IN TIMESTAMP
, RESPONSE OUT VARCHAR2
) IS 
BEGIN
  RESPONSE := 'success';
  MERGE into PRT_CARD
  using (select COUNTRYCODE cc, PRTCARDPK ppk, CARDTYPE ctyp , PARTNERID pid ,CARDGROUPMAINTYPE cgmt, CARDGROUPSUBTYPE cgst, CARDGROUPSEQ cgs, CARDEMBOSSNO cen, CARDIDENTIFIER crdid, MAGNETICCODE mgcd, INVOICEINFORMATION invi, CARDEXPIRY crdex, BLOCKTYPE blktp, BLOCKCODE blkcd, BLOCKACTION blkac, BLOCKDATE blkdt, BLOCKTIME blkt, BLOCKLEVEL blkl, MANUFACTUREDDATE mfd, ROUTEXCUSTOMERNUMBER rtctn, INVOICEADDR1 invad1, INVOICEADDR2 invad2, INVOICEPOSTALCODE invpc, INVOICECITY invct, ADDRSEQ adsq, INVOICECOUNTRY invcnt, INNVOICEADDRLEVEL invadl, INNVOICEADDRTYPE invadt, MODIFIEDBY mdb, MODIFIEDDATE mdt  from DUAL) d on (PRT_CARD.COUNTRY_CODE = d.cc and PRT_CARD.PRT_CARD_PK= d.ppk)
  when matched then update set CARD_TYPE=d.ctyp,PARTNER_ID=d.pid,CARDGROUP_MAIN_TYPE=d.cgmt,CARDGROUP_SUB_TYPE=d.cgst,CARDGROUP_SEQ=d.cgs,CARD_EMBOSS_NUM=d.cen,
 CARD_IDENTIFIER=d.crdid, MAGNETIC_CODE=d.mgcd, INVOICE_INFORMATION=d.invi, CARD_EXPIRY=d.crdex, BLOCK_TYPE=d.blktp, BLOCK_CODE=d.blkcd, BLOCK_ACTION=d.blkac,
 BLOCK_DATE=d.blkdt, BLOCK_TIME=d.blkt, BLOCK_LEVEL=d.blkl, MANUFACTURED_DATE=d.mfd, ROUTEX_CUSTOMER_NUMBER=d.rtctn, INVOICE_ADDR1=d.invad1, INVOICE_ADDR2=d.invad2, INVOICE_POSTAL_CODE=d.invpc, INVOICE_CITY=d.invct, ADDR_SEQ=d.adsq, INVOICE_COUNTRY=d.invcnt, INVOICE_ADDR_LEVEL=d.invadl, INVOICE_ADDR_TYPE=d.invadt, MODIFIED_BY=d.mdb, MODIFIED_DATE=d.mdt
  when not matched then insert( COUNTRY_CODE,PARTNER_ID,CARDGROUP_MAIN_TYPE,CARDGROUP_SUB_TYPE,CARDGROUP_SEQ,PRT_CARD_PK,CARD_EMBOSS_NUM,CARD_TYPE,MODIFIED_BY,MODIFIED_DATE,ACCOUNT_ID,
  CARD_IDENTIFIER, MAGNETIC_CODE, INVOICE_INFORMATION, CARD_EXPIRY, BLOCK_TYPE, BLOCK_CODE, BLOCK_ACTION, BLOCK_DATE, BLOCK_TIME, BLOCK_LEVEL, MANUFACTURED_DATE, ROUTEX_CUSTOMER_NUMBER, INVOICE_ADDR1, INVOICE_ADDR2, INVOICE_POSTAL_CODE, INVOICE_CITY, ADDR_SEQ, INVOICE_COUNTRY, INVOICE_ADDR_LEVEL,  INVOICE_ADDR_TYPE) values(d.cc,d.pid,d.cgmt,d.cgst,d.cgs,d.ppk,d.cen,d.ctyp,d.mdb,d.mdt,(select ACCOUNT_ID from PRT_CARDGROUP prtcg where (prtcg.partner_id = PARTNERID AND prtcg.cardgroup_main_type=CARDGROUPMAINTYPE AND prtcg.CARDGROUP_SUB_TYPE=CARDGROUPSUBTYPE AND prtcg.CARDGROUP_SEQ=CARDGROUPSEQ AND prtcg.COUNTRY_CODE = COUNTRYCODE)), d.crdid, d.mgcd, d.invi, d.crdex, d.blktp, d.blkcd, d.blkac, d.blkdt, d.blkt, d.blkl, d.mfd, d.rtctn, d.invad1, d.invad2, d.invpc, d.invct, d.adsq, d.invcnt, d.invadl, d.invadt);
  END SOA_MERGE_PRT_CARD;