package com.sfr.engage.model.queries.uvo;

import com.sfr.engage.model.entities.PrtNotificationEOImpl;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 13 12:23:35 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrtNotifiacationCopyPcmVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CountryCode {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getCountryCode();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setCountryCode((String)value);
            }
        }
        ,
        NotiId {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getNotiId();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setNotiId((DBSequence)value);
            }
        }
        ,
        RuleId {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getRuleId();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setRuleId((String)value);
            }
        }
        ,
        RuleIsenabled {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getRuleIsenabled();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setRuleIsenabled((String)value);
            }
        }
        ,
        SubId {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getSubId();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setSubId((String)value);
            }
        }
        ,
        UserId {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getUserId();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setUserId((String)value);
            }
        }
        ,
        Partner {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getPartner();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setPartner((String)value);
            }
        }
        ,
        AccountId {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getAccountId();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setAccountId((String)value);
            }
        }
        ,
        CardgroupMain {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getCardgroupMain();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setCardgroupMain((String)value);
            }
        }
        ,
        CardgroupSub {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getCardgroupSub();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setCardgroupSub((String)value);
            }
        }
        ,
        CardgroupSeq {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getCardgroupSeq();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setCardgroupSeq((String)value);
            }
        }
        ,
        CardPk {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getCardPk();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setCardPk((String)value);
            }
        }
        ,
        EmbossCardNum {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getEmbossCardNum();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setEmbossCardNum((String)value);
            }
        }
        ,
        TransactionTime {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getTransactionTime();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setTransactionTime((Timestamp)value);
            }
        }
        ,
        NotiCreated {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getNotiCreated();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setNotiCreated((Date)value);
            }
        }
        ,
        NotiCategory {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getNotiCategory();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setNotiCategory((String)value);
            }
        }
        ,
        NotiSubcategory {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getNotiSubcategory();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setNotiSubcategory((String)value);
            }
        }
        ,
        ShowFlag {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getShowFlag();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setShowFlag((String)value);
            }
        }
        ,
        NotiDescription {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getNotiDescription();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setNotiDescription((String)value);
            }
        }
        ,
        ModifiedBy {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getModifiedBy();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setModifiedBy((String)value);
            }
        }
        ,
        ModifiedDate {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setModifiedDate((Timestamp)value);
            }
        }
        ,
        NotiDescriptionLocalised {
            public Object get(PrtNotifiacationCopyPcmVORowImpl obj) {
                return obj.getNotiDescriptionLocalised();
            }

            public void put(PrtNotifiacationCopyPcmVORowImpl obj, Object value) {
                obj.setNotiDescriptionLocalised((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PrtNotifiacationCopyPcmVORowImpl object);

        public abstract void put(PrtNotifiacationCopyPcmVORowImpl object, Object value);

        public int index() {
            return PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.firstIndex() + PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int COUNTRYCODE = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.CountryCode.index();
    public static final int NOTIID = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.NotiId.index();
    public static final int RULEID = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.RuleId.index();
    public static final int RULEISENABLED = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.RuleIsenabled.index();
    public static final int SUBID = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.SubId.index();
    public static final int USERID = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.UserId.index();
    public static final int PARTNER = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.Partner.index();
    public static final int ACCOUNTID = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.AccountId.index();
    public static final int CARDGROUPMAIN = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.CardgroupMain.index();
    public static final int CARDGROUPSUB = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.CardgroupSub.index();
    public static final int CARDGROUPSEQ = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.CardgroupSeq.index();
    public static final int CARDPK = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.CardPk.index();
    public static final int EMBOSSCARDNUM = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.EmbossCardNum.index();
    public static final int TRANSACTIONTIME = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.TransactionTime.index();
    public static final int NOTICREATED = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.NotiCreated.index();
    public static final int NOTICATEGORY = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.NotiCategory.index();
    public static final int NOTISUBCATEGORY = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.NotiSubcategory.index();
    public static final int SHOWFLAG = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.ShowFlag.index();
    public static final int NOTIDESCRIPTION = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.NotiDescription.index();
    public static final int MODIFIEDBY = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.ModifiedDate.index();
    public static final int NOTIDESCRIPTIONLOCALISED = PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.NotiDescriptionLocalised.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrtNotifiacationCopyPcmVORowImpl() {
    }

    /**
     * Gets PrtNotificationEO entity object.
     * @return the PrtNotificationEO
     */
    public PrtNotificationEOImpl getPrtNotificationEO() {
        return (PrtNotificationEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @return the COUNTRY_CODE
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @param value value to set the COUNTRY_CODE
     */
    public void setCountryCode(String value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for NOTI_ID using the alias name NotiId.
     * @return the NOTI_ID
     */
    public DBSequence getNotiId() {
        return (DBSequence)getAttributeInternal(NOTIID);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTI_ID using the alias name NotiId.
     * @param value value to set the NOTI_ID
     */
    public void setNotiId(DBSequence value) {
        setAttributeInternal(NOTIID, value);
    }

    /**
     * Gets the attribute value for RULE_ID using the alias name RuleId.
     * @return the RULE_ID
     */
    public String getRuleId() {
        return (String) getAttributeInternal(RULEID);
    }

    /**
     * Sets <code>value</code> as attribute value for RULE_ID using the alias name RuleId.
     * @param value value to set the RULE_ID
     */
    public void setRuleId(String value) {
        setAttributeInternal(RULEID, value);
    }

    /**
     * Gets the attribute value for RULE_ISENABLED using the alias name RuleIsenabled.
     * @return the RULE_ISENABLED
     */
    public String getRuleIsenabled() {
        return (String) getAttributeInternal(RULEISENABLED);
    }

    /**
     * Sets <code>value</code> as attribute value for RULE_ISENABLED using the alias name RuleIsenabled.
     * @param value value to set the RULE_ISENABLED
     */
    public void setRuleIsenabled(String value) {
        setAttributeInternal(RULEISENABLED, value);
    }

    /**
     * Gets the attribute value for SUB_ID using the alias name SubId.
     * @return the SUB_ID
     */
    public String getSubId() {
        return (String) getAttributeInternal(SUBID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_ID using the alias name SubId.
     * @param value value to set the SUB_ID
     */
    public void setSubId(String value) {
        setAttributeInternal(SUBID, value);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public String getUserId() {
        return (String) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(String value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for PARTNER using the alias name Partner.
     * @return the PARTNER
     */
    public String getPartner() {
        return (String) getAttributeInternal(PARTNER);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTNER using the alias name Partner.
     * @param value value to set the PARTNER
     */
    public void setPartner(String value) {
        setAttributeInternal(PARTNER, value);
    }

    /**
     * Gets the attribute value for ACCOUNT_ID using the alias name AccountId.
     * @return the ACCOUNT_ID
     */
    public String getAccountId() {
        return (String) getAttributeInternal(ACCOUNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNT_ID using the alias name AccountId.
     * @param value value to set the ACCOUNT_ID
     */
    public void setAccountId(String value) {
        setAttributeInternal(ACCOUNTID, value);
    }

    /**
     * Gets the attribute value for CARDGROUP_MAIN using the alias name CardgroupMain.
     * @return the CARDGROUP_MAIN
     */
    public String getCardgroupMain() {
        return (String) getAttributeInternal(CARDGROUPMAIN);
    }

    /**
     * Sets <code>value</code> as attribute value for CARDGROUP_MAIN using the alias name CardgroupMain.
     * @param value value to set the CARDGROUP_MAIN
     */
    public void setCardgroupMain(String value) {
        setAttributeInternal(CARDGROUPMAIN, value);
    }

    /**
     * Gets the attribute value for CARDGROUP_SUB using the alias name CardgroupSub.
     * @return the CARDGROUP_SUB
     */
    public String getCardgroupSub() {
        return (String) getAttributeInternal(CARDGROUPSUB);
    }

    /**
     * Sets <code>value</code> as attribute value for CARDGROUP_SUB using the alias name CardgroupSub.
     * @param value value to set the CARDGROUP_SUB
     */
    public void setCardgroupSub(String value) {
        setAttributeInternal(CARDGROUPSUB, value);
    }

    /**
     * Gets the attribute value for CARDGROUP_SEQ using the alias name CardgroupSeq.
     * @return the CARDGROUP_SEQ
     */
    public String getCardgroupSeq() {
        return (String) getAttributeInternal(CARDGROUPSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for CARDGROUP_SEQ using the alias name CardgroupSeq.
     * @param value value to set the CARDGROUP_SEQ
     */
    public void setCardgroupSeq(String value) {
        setAttributeInternal(CARDGROUPSEQ, value);
    }

    /**
     * Gets the attribute value for CARD_PK using the alias name CardPk.
     * @return the CARD_PK
     */
    public String getCardPk() {
        return (String) getAttributeInternal(CARDPK);
    }

    /**
     * Sets <code>value</code> as attribute value for CARD_PK using the alias name CardPk.
     * @param value value to set the CARD_PK
     */
    public void setCardPk(String value) {
        setAttributeInternal(CARDPK, value);
    }

    /**
     * Gets the attribute value for EMBOSS_CARD_NUM using the alias name EmbossCardNum.
     * @return the EMBOSS_CARD_NUM
     */
    public String getEmbossCardNum() {
        return (String) getAttributeInternal(EMBOSSCARDNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for EMBOSS_CARD_NUM using the alias name EmbossCardNum.
     * @param value value to set the EMBOSS_CARD_NUM
     */
    public void setEmbossCardNum(String value) {
        setAttributeInternal(EMBOSSCARDNUM, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_TIME using the alias name TransactionTime.
     * @return the TRANSACTION_TIME
     */
    public Timestamp getTransactionTime() {
        return (Timestamp) getAttributeInternal(TRANSACTIONTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_TIME using the alias name TransactionTime.
     * @param value value to set the TRANSACTION_TIME
     */
    public void setTransactionTime(Timestamp value) {
        setAttributeInternal(TRANSACTIONTIME, value);
    }

    /**
     * Gets the attribute value for NOTI_CREATED using the alias name NotiCreated.
     * @return the NOTI_CREATED
     */
    public Date getNotiCreated() {
        return (Date) getAttributeInternal(NOTICREATED);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTI_CREATED using the alias name NotiCreated.
     * @param value value to set the NOTI_CREATED
     */
    public void setNotiCreated(Date value) {
        setAttributeInternal(NOTICREATED, value);
    }

    /**
     * Gets the attribute value for NOTI_CATEGORY using the alias name NotiCategory.
     * @return the NOTI_CATEGORY
     */
    public String getNotiCategory() {
        return (String) getAttributeInternal(NOTICATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTI_CATEGORY using the alias name NotiCategory.
     * @param value value to set the NOTI_CATEGORY
     */
    public void setNotiCategory(String value) {
        setAttributeInternal(NOTICATEGORY, value);
    }

    /**
     * Gets the attribute value for NOTI_SUBCATEGORY using the alias name NotiSubcategory.
     * @return the NOTI_SUBCATEGORY
     */
    public String getNotiSubcategory() {
        return (String) getAttributeInternal(NOTISUBCATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTI_SUBCATEGORY using the alias name NotiSubcategory.
     * @param value value to set the NOTI_SUBCATEGORY
     */
    public void setNotiSubcategory(String value) {
        setAttributeInternal(NOTISUBCATEGORY, value);
    }

    /**
     * Gets the attribute value for SHOW_FLAG using the alias name ShowFlag.
     * @return the SHOW_FLAG
     */
    public String getShowFlag() {
        return (String) getAttributeInternal(SHOWFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for SHOW_FLAG using the alias name ShowFlag.
     * @param value value to set the SHOW_FLAG
     */
    public void setShowFlag(String value) {
        setAttributeInternal(SHOWFLAG, value);
    }

    /**
     * Gets the attribute value for NOTI_DESCRIPTION using the alias name NotiDescription.
     * @return the NOTI_DESCRIPTION
     */
    public String getNotiDescription() {
        return (String) getAttributeInternal(NOTIDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTI_DESCRIPTION using the alias name NotiDescription.
     * @param value value to set the NOTI_DESCRIPTION
     */
    public void setNotiDescription(String value) {
        setAttributeInternal(NOTIDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Timestamp getModifiedDate() {
        return (Timestamp) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Timestamp value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for NOTI_DESCRIPTION_LOCALISED using the alias name NotiDescriptionLocalised.
     * @return the NOTI_DESCRIPTION_LOCALISED
     */
    public String getNotiDescriptionLocalised() {
        return (String) getAttributeInternal(NOTIDESCRIPTIONLOCALISED);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTI_DESCRIPTION_LOCALISED using the alias name NotiDescriptionLocalised.
     * @param value value to set the NOTI_DESCRIPTION_LOCALISED
     */
    public void setNotiDescriptionLocalised(String value) {
        setAttributeInternal(NOTIDESCRIPTIONLOCALISED, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.firstIndex()) && (index < PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.count())) {
            return PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.staticValues()[index - PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.firstIndex()) && (index < PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.count())) {
            PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.staticValues()[index - PrtNotifiacationCopyPcmVORowImpl.AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
